export const NEXT_PUBLIC_API_HITPAY = "https://api.staging.hit-pay.com";
export const NEXT_PUBLIC_DASHBOARD_HITPAY = "https://dashboard.staging.hit-pay.com";

export const paymentOptions = [
  {
    label: "on_booking_option",
    value: "ON_BOOKING",
  },
];

export const supportedPaymentMethods = [
  "paynow",
  "grabpay",
  "shopeepay",
  "zip",
  "fpx",
  "visa",
  "master",
  "american_express",
  "alipay",
  "atome",
  "unionpay",
  "gcash",
  "qrph",
  "billease",
  "seveneleven",
  "cebuana",
  "palawa",
  "ovo",
  "gopay",
  "linkaja",
  "dana",
  "kredivo",
  "akulakupaylater",
  "akulaku",
  "indomaret",
  "alfamart",
  "bri",
  "cimb",
  "sbpl",
  "payid",
  "qris",
  "bdo",
  "bpi",
  "duitnow",
  "wechatpay",
  "qr_promptpay",
  "line_pay",
  "truemoney_pay",
];
