export const currencyOptions = [
  { label: "United States dollar (USD)", value: "usd" },
  { label: "Singapore dollar (SGD)", value: "sgd" },
  { label: "Malaysian ringgit (MYR)", value: "myr" },
  { label: "Indonesian rupiah (IDR)", value: "idr" },
  { label: "Japanese yen (JPY)", value: "jpy" },
  { label: "Hong Kong dollar (HKD)", value: "hkd" },
  { label: "Thai baht (THB)", value: "thb" },
  { label: "Australian dollar (AUD)", value: "aud" },
  { label: "New Zealand dollar (NZD)", value: "nzd" },
  { label: "British pound sterling (GBP)", value: "gbp" },
  { label: "Philippine peso (PHP)", value: "php" },
  { label: "Indian rupee (INR)", value: "inr" },
  { label: "Chinese yuan (CNY)", value: "cny" },
  { label: "Euro (EUR)", value: "eur" },
  { label: "Swiss franc (CHF)", value: "chf" },
  { label: "Danish krone (DKK)", value: "dkk" },
  { label: "Swedish krona (SEK)", value: "sek" },
  { label: "Norwegian krone (NOK)", value: "nok" },
  { label: "Vietnamese đồng (VND)", value: "vnd" },
  { label: "Canadian dollar (CAD)", value: "cad" },
  { label: "South Korean won (KRW)", value: "krw" },
];
