import type { BriefingOutput } from "@calcom/features/bookings/lib/generateBriefing";

function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}

const labelStyle =
  "margin:0 0 8px;font-size:11px;text-transform:uppercase;letter-spacing:0.08em;color:#6b7280;font-weight:600";
const bodyStyle = "margin:0;font-size:14px;color:#111827;line-height:1.6";
const hr = '<hr style="border:none;border-top:1px solid #e5e7eb;margin:24px 0">';

export function bookingBriefTemplate(params: {
  organizerName: string;
  attendeeName: string;
  eventTitle: string;
  startTime: Date;
  timeZone: string;
  briefing: BriefingOutput;
}): { subject: string; html: string } {
  const { attendeeName, eventTitle, startTime, timeZone, briefing } = params;
  const subject = `Booking Brief: ${attendeeName} \u2013 ${eventTitle}`;
  const when = escapeHtml(
    startTime.toLocaleString("en-US", {
      weekday: "long",
      month: "long",
      day: "numeric",
      hour: "numeric",
      minute: "2-digit",
      timeZone,
      timeZoneName: "short",
    })
  );
  const agendaLines = briefing.suggestedAgenda
    .map(
      (item, i) =>
        `<p style="margin:0 0 6px;font-size:14px;color:#111827;line-height:1.6">${i + 1}. ${escapeHtml(item)}</p>`
    )
    .join("");
  const html = `<!DOCTYPE html><html><body style="margin:0;padding:24px 16px;background:#ffffff;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif"><table role="presentation" cellpadding="0" cellspacing="0" style="max-width:600px;margin:0 auto;width:100%"><tr><td>
<p style="${labelStyle}">BOOKING BRIEF</p>
<h1 style="margin:0 0 8px;font-size:20px;font-weight:700;color:#111827;line-height:1.3">${escapeHtml(eventTitle)}</h1>
<p style="${bodyStyle}">${when}</p>
${hr}
<p style="${labelStyle}">WHO YOU'RE MEETING</p>
<p style="margin:0 0 4px;font-size:14px;color:#111827;line-height:1.6;font-weight:600">${escapeHtml(attendeeName)}</p>
<p style="${bodyStyle}">${escapeHtml(briefing.attendeeSummary)}</p>
${hr}
<p style="${labelStyle}">AGENDA</p>
${agendaLines}
${hr}
<p style="${labelStyle}">OPENING QUESTION</p>
<p style="${bodyStyle}">${escapeHtml(briefing.openingQuestion)}</p>
${hr}
<p style="${labelStyle}">PREP TIP</p>
<p style="${bodyStyle}">${escapeHtml(briefing.prepTip)}</p>
${hr}
<p style="margin:0;padding:16px;font-size:11px;color:#6b7280;line-height:1.5;background:#f9fafb">Generated by Booking Brief · Cal.com</p>
</td></tr></table></body></html>`;

  return { subject, html };
}
