import type { TrpcSessionUser } from "@calcom/trpc/server/trpc";
import type { TGetInputSchema } from "./get.schema";
type GetOptions = {
    ctx: {
        user: NonNullable<TrpcSessionUser>;
    };
    input: TGetInputSchema;
};
export declare const getHandler: ({ ctx, input }: GetOptions) => Promise<{
    id: number;
    userId: number | null;
    teamId: number | null;
    team: {
        id: number;
        slug: string | null;
        name: string;
        isOrganization: boolean;
        members: {
            id: number;
            userId: number;
            teamId: number;
            role: import(".prisma/client").$Enums.MembershipRole;
            disableImpersonation: boolean;
            accepted: boolean;
        }[];
    } | null;
    time: number | null;
    name: string;
    isActiveOnAll: boolean;
    trigger: import(".prisma/client").$Enums.WorkflowTriggerEvents;
    timeUnit: import(".prisma/client").$Enums.TimeUnit | null;
    activeOn: {
        eventType: {
            length: number;
            id: number;
            title: string;
            slug: string;
            description: string | null;
            position: number;
            locations: import(".prisma/client").Prisma.JsonValue;
            offsetStart: number;
            hidden: boolean;
            userId: number | null;
            profileId: number | null;
            teamId: number | null;
            eventName: string | null;
            parentId: number | null;
            bookingFields: import(".prisma/client").Prisma.JsonValue;
            timeZone: string | null;
            periodType: import(".prisma/client").$Enums.PeriodType;
            periodStartDate: Date | null;
            periodEndDate: Date | null;
            periodDays: number | null;
            periodCountCalendarDays: boolean | null;
            lockTimeZoneToggleOnBookingPage: boolean;
            requiresConfirmation: boolean;
            requiresConfirmationWillBlockSlot: boolean;
            requiresBookerEmailVerification: boolean;
            recurringEvent: import(".prisma/client").Prisma.JsonValue;
            disableGuests: boolean;
            hideCalendarNotes: boolean;
            minimumBookingNotice: number;
            beforeEventBuffer: number;
            afterEventBuffer: number;
            seatsPerTimeSlot: number | null;
            onlyShowFirstAvailableSlot: boolean;
            seatsShowAttendees: boolean | null;
            seatsShowAvailabilityCount: boolean | null;
            schedulingType: import(".prisma/client").$Enums.SchedulingType | null;
            scheduleId: number | null;
            price: number;
            currency: string;
            slotInterval: number | null;
            metadata: import(".prisma/client").Prisma.JsonValue;
            successRedirectUrl: string | null;
            forwardParamsSuccessRedirect: boolean | null;
            bookingLimits: import(".prisma/client").Prisma.JsonValue;
            durationLimits: import(".prisma/client").Prisma.JsonValue;
            isInstantEvent: boolean;
            instantMeetingExpiryTimeOffsetInSeconds: number;
            instantMeetingScheduleId: number | null;
            assignAllTeamMembers: boolean;
            useEventTypeDestinationCalendarEmail: boolean;
            isRRWeightsEnabled: boolean;
            eventTypeColor: import(".prisma/client").Prisma.JsonValue;
            rescheduleWithSameRoundRobinHost: boolean;
            secondaryEmailId: number | null;
        };
    }[];
    activeOnTeams: {
        team: {
            id: number;
            slug: string | null;
            parentId: number | null;
            timeZone: string;
            metadata: import(".prisma/client").Prisma.JsonValue;
            name: string;
            bio: string | null;
            weekStart: string;
            hideBranding: boolean;
            theme: string | null;
            timeFormat: number | null;
            brandColor: string | null;
            darkBrandColor: string | null;
            smsLockState: import(".prisma/client").$Enums.SMSLockState;
            smsLockReviewedByAdmin: boolean;
            createdAt: Date;
            logoUrl: string | null;
            calVideoLogo: string | null;
            appLogo: string | null;
            appIconLogo: string | null;
            isPrivate: boolean;
            hideBookATeamMember: boolean;
            bannerUrl: string | null;
            isOrganization: boolean;
            pendingPayment: boolean;
            isPlatform: boolean;
            createdByOAuthClientId: string | null;
        };
    }[];
    steps: {
        id: number;
        workflowId: number;
        stepNumber: number;
        action: import(".prisma/client").$Enums.WorkflowActions;
        sendTo: string | null;
        reminderBody: string | null;
        emailSubject: string | null;
        template: import(".prisma/client").$Enums.WorkflowTemplates;
        numberRequired: boolean | null;
        sender: string | null;
        numberVerificationPending: boolean;
        includeCalendarEvent: boolean;
    }[];
} | null>;
export {};
