export const currencyOptions = [
  { label: "Indian Rupee", value: "INR" },
  { label: "United States Dollar", value: "USD" },
  { label: "Albanian Lek", value: "ALL" },
  { label: "Algerian Dinar", value: "DZD" },
  { label: "Armenian Dram", value: "AMD" },
  { label: "Aruban Florin", value: "AWG" },
  { label: "Australian Dollar", value: "AUD" },
  { label: "Azerbaijan Manat", value: "AZN" },
  { label: "Bahamian Dollar", value: "BSD" },
  { label: "Bahraini Dinar", value: "BHD" },
  { label: "Bangladeshi Taka", value: "BDT" },
  { label: "Barbadian Dollar", value: "BBD" },
  { label: "Belize Dollar", value: "BZD" },
  { label: "Bermudian Dollar", value: "BMD" },
  { label: "Bhutanese Ngultrum", value: "BTN" },
  { label: "Bolivian Boliviano", value: "BOB" },
  { label: "Botswana Pula", value: "BWP" },
  { label: "Brazilian Real", value: "BRL" },
  { label: "Brunei Dollar", value: "BND" },
  { label: "Bulgarian Lev", value: "BGN" },
  { label: "Burundi Franc", value: "BIF" },
  { label: "Cabo Verde Escudo", value: "CVE" },
  { label: "Cambodian Riel", value: "KHR" },
  { label: "Canadian Dollar", value: "CAD" },
  { label: "Cayman Islands Dollar", value: "KYD" },
  { label: "CFA Franc BEAC", value: "XAF" },
  { label: "CFA Franc BCEAO", value: "XOF" },
  { label: "CFP Franc", value: "XPF" },
  { label: "Chilean Peso", value: "CLP" },
  { label: "Chinese Yuan Renminbi", value: "CNY" },
  { label: "Colombian Peso", value: "COP" },
  { label: "Comorian Franc", value: "KMF" },
  { label: "Convertible Mark", value: "BAM" },
  { label: "Costa Rican Colon", value: "CRC" },
  { label: "Croatian Kuna", value: "HRK" },
  { label: "Cuban Peso", value: "CUP" },
  { label: "Czech Koruna", value: "CZK" },
  { label: "Danish Krone", value: "DKK" },
  { label: "Djibouti Franc", value: "DJF" },
  { label: "Dominican Peso", value: "DOP" },
  { label: "East Caribbean Dollar", value: "XCD" },
  { label: "Egyptian Pound", value: "EGP" },
  { label: "Ethiopian Birr", value: "ETB" },
  { label: "European Euro", value: "EUR" },
  { label: "Fijian Dollar", value: "FJD" },
  { label: "Gambian Dalasi", value: "GMD" },
  { label: "Ghanaian Cedi", value: "GHS" },
  { label: "Gibraltar Pound", value: "GIP" },
  { label: "Guatemalan Quetzal", value: "GTQ" },
  { label: "Guinean Franc", value: "GNF" },
  { label: "Guyanese Dollar", value: "GYD" },
  { label: "Haitian Gourde", value: "HTG" },
  { label: "Honduran Lempira", value: "HNL" },
  { label: "Hong Kong Dollar", value: "HKD" },
  { label: "Hungarian Forint", value: "HUF" },
  { label: "Iceland Krona", value: "ISK" },
  { label: "Indonesian Rupiah", value: "IDR" },
  { label: "Iraqi Dinar", value: "IQD" },
  { label: "Israeli New Shekel", value: "ILS" },
  { label: "Jamaican Dollar", value: "JMD" },
  { label: "Japanese Yen", value: "JPY" },
  { label: "Jordanian Dinar", value: "JOD" },
  { label: "Kazakhstani Tenge", value: "KZT" },
  { label: "Kenyan Shilling", value: "KES" },
  { label: "Korean Won", value: "KRW" },
  { label: "Kuwaiti Dinar", value: "KWD" },
  { label: "Kyrgyzstani Som", value: "KGS" },
  { label: "Lao Kip", value: "LAK" },
  { label: "Lesotho Loti", value: "LSL" },
  { label: "Liberian Dollar", value: "LRD" },
  { label: "Macanese Pataca", value: "MOP" },
  { label: "Macedonian Denar", value: "MKD" },
  { label: "Malagasy Ariary", value: "MGA" },
  { label: "Malawian Kwacha", value: "MWK" },
  { label: "Malaysian Ringgit", value: "MYR" },
  { label: "Maldivian Rufiyaa", value: "MVR" },
  { label: "Mauritian Rupee", value: "MUR" },
  { label: "Mexican Peso", value: "MXN" },
  { label: "Moldovan Leu", value: "MDL" },
  { label: "Mongolian Tugrik", value: "MNT" },
  { label: "Moroccan Dirham", value: "MAD" },
  { label: "Mozambique Metical", value: "MZN" },
  { label: "Myanmar Kyat", value: "MMK" },
  { label: "Namibian Dollar", value: "NAD" },
  { label: "Nepalese Rupee", value: "NPR" },
  { label: "New Taiwan Dollar", value: "TWD" },
  { label: "New Zealand Dollar", value: "NZD" },
  { label: "Nicaraguan Cordoba", value: "NIO" },
  { label: "Nigerian Naira", value: "NGN" },
  { label: "Norwegian Krone", value: "NOK" },
  { label: "Pakistani Rupee", value: "PKR" },
  { label: "Papua New Guinean Kina", value: "PGK" },
  { label: "Paraguayan Guarani", value: "PYG" },
  { label: "Peruvian Sol", value: "PEN" },
  { label: "Philippine Peso", value: "PHP" },
  { label: "Polish Zloty", value: "PLN" },
  { label: "Pound Sterling", value: "GBP" },
  { label: "Qatari Riyal", value: "QAR" },
  { label: "Rial Omani", value: "OMR" },
  { label: "Romanian Leu", value: "RON" },
  { label: "Russian Ruble", value: "RUB" },
  { label: "Rwanda Franc", value: "RWF" },
  { label: "Salvadoran Colón", value: "SVC" },
  { label: "Saudi Arabian Riyal", value: "SAR" },
  { label: "Serbian Dinar", value: "RSD" },
  { label: "Seychellois Rupee", value: "SCR" },
  { label: "Sierra Leonean Leone", value: "SLL" },
  { label: "Singapore Dollar", value: "SGD" },
  { label: "Somali Shilling", value: "SOS" },
  { label: "South African Rand", value: "ZAR" },
  { label: "Sri Lankan Rupee", value: "LKR" },
  { label: "Swazi Lilangeni", value: "SZL" },
  { label: "Swedish Krona", value: "SEK" },
  { label: "Swiss Franc", value: "CHF" },
  { label: "Tanzanian Shilling", value: "TZS" },
  { label: "Thai Baht", value: "THB" },
  { label: "Trinidad and Tobago Dollar", value: "TTD" },
  { label: "Tunisian Dinar", value: "TND" },
  { label: "Turkish Lira", value: "TRY" },
  { label: "Uganda Shilling", value: "UGX" },
  { label: "Ukrainian Hryvnia", value: "UAH" },
  { label: "United Arab Emirates Dirham", value: "AED" },
  { label: "Uruguayan Peso", value: "UYU" },
  { label: "Uzbekistani So'm", value: "UZS" },
  { label: "Vatu", value: "VUV" },
  { label: "Vietnamese Dong", value: "VND" },
  { label: "Yemeni Rial", value: "YER" },
  { label: "Zambian Kwacha", value: "ZMW" },
] as const;

type CurrencyCode = (typeof currencyOptions)[number]["value"];

// NOTE: No longer being used to create currency symbol, as this contains non standard currency symbols.
export const currencySymbols: Record<CurrencyCode, string> = {
  INR: "₹",
  USD: "$",
  ALL: "L",
  DZD: "دج",
  AMD: "֏",
  AWG: "ƒ",
  AUD: "$",
  AZN: "₼",
  BSD: "$",
  BHD: ".د.ب",
  BDT: "৳",
  BBD: "$",
  BZD: "$",
  BMD: "$",
  BTN: "Nu.",
  BOB: "Bs.",
  BWP: "P",
  BRL: "R$",
  BND: "$",
  BGN: "лв",
  BIF: "FBu",
  CVE: "Esc",
  KHR: "៛",
  CAD: "$",
  KYD: "$",
  XAF: "FCFA",
  XOF: "CFA",
  XPF: "₣",
  CLP: "$",
  CNY: "¥",
  COP: "$",
  KMF: "CF",
  BAM: "KM",
  CRC: "₡",
  HRK: "kn",
  CUP: "$",
  CZK: "Kč",
  DKK: "kr",
  DJF: "Fdj",
  DOP: "$",
  XCD: "$",
  EGP: "£",
  ETB: "Br",
  EUR: "€",
  FJD: "$",
  GMD: "D",
  GHS: "₵",
  GIP: "£",
  GTQ: "Q",
  GNF: "FG",
  GYD: "$",
  HTG: "G",
  HNL: "L",
  HKD: "$",
  HUF: "Ft",
  ISK: "kr",
  IDR: "Rp",
  IQD: "ع.د",
  ILS: "₪",
  JMD: "$",
  JPY: "¥",
  JOD: "JD",
  KZT: "₸",
  KES: "Sh",
  KRW: "₩",
  KWD: "د.ك",
  KGS: "с",
  LAK: "₭",
  LSL: "L",
  LRD: "$",
  MOP: "P",
  MKD: "ден",
  MGA: "Ar",
  MWK: "MK",
  MYR: "RM",
  MVR: "Rf",
  MUR: "₨",
  MXN: "$",
  MDL: "L",
  MNT: "₮",
  MAD: "د.م.",
  MZN: "MT",
  MMK: "Ks",
  NAD: "$",
  NPR: "Rs",
  TWD: "NT$",
  NZD: "$",
  NIO: "C$",
  NGN: "₦",
  NOK: "kr",
  PKR: "₨",
  PGK: "K",
  PYG: "₲",
  PEN: "S/",
  PHP: "₱",
  PLN: "zł",
  GBP: "£",
  QAR: "﷼",
  OMR: "ر.ع.",
  RON: "lei",
  RUB: "₽",
  RWF: "FRw",
  SVC: "₡",
  SAR: "﷼",
  RSD: "din.",
  SCR: "₨",
  SLL: "Le",
  SGD: "$",
  SOS: "Sh",
  ZAR: "R",
  LKR: "Rs",
  SZL: "L",
  SEK: "kr",
  CHF: "Fr",
  TZS: "Sh",
  THB: "฿",
  TTD: "$",
  TND: "د.ت",
  TRY: "₺",
  UGX: "Sh",
  UAH: "₴",
  AED: "د.إ",
  UYU: "$",
  UZS: "soʻm",
  VUV: "VT",
  VND: "₫",
  YER: "﷼",
  ZMW: "ZK",
};

export function isAcceptedCurrencyCode(currencyCode: string): currencyCode is CurrencyCode {
  return Object.keys(currencySymbols).includes(currencyCode);
}
