export const currencyOptions = [
  { label: "United States dollar", value: "USD" },
  { label: "Indian rupee", value: "INR" },
  { label: "Australian dollar", value: "AUD" },
  { label: "Brazilian real 2", value: "BRL" },
  { label: "Canadian dollar", value: "CAD" },
  { label: "Chinese Renmenbi 3", value: "CNY" },
  { label: "Czech koruna", value: "CZK" },
  { label: "Danish krone", value: "DKK" },
  { label: "Euro", value: "EUR" },
  { label: "Hong Kong dollar", value: "HKD" },
  { label: "Hungarian forint 1", value: "HUF" },
  { label: "Israeli new shekel", value: "ILS" },
  { label: "Japanese yen 1", value: "JPY" },
  { label: "Malaysian ringgit 3", value: "MYR" },
  { label: "Mexican peso", value: "MXN" },
  // { label: "New Taiwan dollar 1", value: "TWD" }, // This doesn't exist in razorpay's currency list from docs.
  { label: "New Zealand dollar", value: "NZD" },
  { label: "Norwegian krone", value: "NOK" },
  { label: "Philippine peso", value: "PHP" },
  // { label: "Polish złoty", value: "PLN" }, // This doesn't exist in razorpay's currency list from docs.
  { label: "Pound sterling", value: "GBP" },
  { label: "Russian ruble", value: "RUB" },
  { label: "Singapore dollar", value: "SGD" },
  { label: "Swedish krona", value: "SEK" },
  { label: "Swiss franc", value: "CHF" },
  { label: "Thai baht", value: "THB" },
  { label: "United Arab Emirates Dirham", value: "AED" },
  // There are many more supported currencies in razorpay, but these are the most common ones
  // Other currencies can be added as needed

  { label: "Albanian lek", value: "ALL" },
  { label: "Armenian dram", value: "AMD" },
  { label: "Argentine peso", value: "ARS" },
  { label: "Aruban florin", value: "AWG" },
  { label: "Barbadian dollar", value: "BBD" },
  { label: "Bangladeshi taka", value: "BDT" },
  { label: "Bermudian dollar", value: "BMD" },
  { label: "Brunei dollar", value: "BND" },
  { label: "Bolivian boliviano", value: "BOB" },
  { label: "Bahamian dollar", value: "BSD" },
  { label: "Botswana pula", value: "BWP" },
  { label: "Belize dollar", value: "BZD" },
  { label: "Colombian peso", value: "COP" },
  { label: "Costa Rican colon", value: "CRC" },
  { label: "Cuban peso", value: "CUP" },
  { label: "Dominican peso", value: "DOP" },
  { label: "Algerian dinar", value: "DZD" },
  { label: "Egyptian pound", value: "EGP" },
  { label: "Ethiopian birr", value: "ETB" },
  { label: "Fijian dollar", value: "FJD" },
  { label: "Ghanian cedi", value: "GHS" },
  { label: "Gibraltar pound", value: "GIP" },
  { label: "Gambian dalasi", value: "GMD" },
  { label: "Guatemalan quetzal", value: "GTQ" },
  { label: "Guyanese dollar", value: "GYD" },
  { label: "Honduran lempira", value: "HNL" },
  { label: "Croatian kuna", value: "HRK" },
  { label: "Haitian gourde", value: "HTG" },
  { label: "Indonesian rupiah", value: "IDR" },
  { label: "Jamaican dollar", value: "JMD" },
  { label: "Kenyan shilling", value: "KES" },
  { label: "Kyrgyzstani som", value: "KGS" },
  { label: "Cambodian riel", value: "KHR" },
  { label: "Cayman Islands dollar", value: "KYD" },
  { label: "Kazakhstani tenge", value: "KZT" },
  { label: "Lao kip", value: "LAK" },
  { label: "Sri Lankan rupee", value: "LKR" },
  { label: "Liberian dollar", value: "LRD" },
  { label: "Lesotho loti", value: "LSL" },
  { label: "Moroccan dirham", value: "MAD" },
  { label: "Moldovan leu", value: "MDL" },
  { label: "Macedonian denar", value: "MKD" },
  { label: "Myanmar kyat", value: "MMK" },
  { label: "Mongolian tugrik", value: "MNT" },
  { label: "Macanese pataca", value: "MOP" },
  { label: "Mauritian rupee", value: "MUR" },
  { label: "Maldivian rufiyaa", value: "MVR" },
  { label: "Malawian kwacha", value: "MWK" },
  { label: "Namibian dollar", value: "NAD" },
  { label: "Nigerian naira", value: "NGN" },
  { label: "Nicaraguan cordoba", value: "NIO" },
  { label: "Nepalese rupee", value: "NPR" },
  { label: "Peruvian sol", value: "PEN" },
  { label: "Papua New Guinean kina", value: "PGK" },
  { label: "Pakistani rupee", value: "PKR" },
  { label: "Qatari riyal", value: "QAR" },
  { label: "Saudi Arabian riyal", value: "SAR" },
  { label: "Seychellois rupee", value: "SCR" },
  { label: "Sierra Leonean leone", value: "SLL" },
  { label: "Somali shilling", value: "SOS" },
  { label: "South Sudanese pound", value: "SSP" },
  { label: "Salvadoran colón", value: "SVC" },
  { label: "Swazi lilangeni", value: "SZL" },
  { label: "Trinidad and Tobago dollar", value: "TTD" },
  { label: "Tanzanian shilling", value: "TZS" },
  { label: "Uruguayan peso", value: "UYU" },
  { label: "Uzbekistani so'm", value: "UZS" },
  { label: "Yemeni rial", value: "YER" },
  { label: "South African rand", value: "ZAR" },
  { label: "Turkish lira", value: "TRY" },
] as const;

type CurrencyCode = (typeof currencyOptions)[number]["value"];

// NOTE: No longer being used to create currency symbol, as this contains non standard currency symbols.
export const currencySymbols: Record<CurrencyCode, string> = {
  AED: "د.إ",
  USD: "$",
  AUD: "$",
  BRL: "R$",
  CAD: "$",
  CNY: "¥",
  CZK: "Kč",
  DKK: "kr",
  EUR: "€",
  HKD: "$",
  HUF: "Ft",
  ILS: "₪",
  JPY: "¥",
  MYR: "RM",
  MXN: "$",
  TWD: "$",
  NZD: "$",
  NOK: "kr",
  PHP: "₱",
  PLN: "zł",
  GBP: "£",
  RUB: "₽",
  SGD: "$",
  SEK: "kr",
  CHF: "Fr",
  THB: "฿",
  INR: "₹",

  ALL: "L",
  AMD: "֏",
  ARS: "$",
  AWG: "ƒ",
  BBD: "$",
  BDT: "৳",
  BMD: "$",
  BND: "$",
  BOB: "Bs.",
  BSD: "$",
  BWP: "P",
  BZD: "$",
  COP: "$",
  CRC: "₡",
  CUP: "$",
  DOP: "$",
  DZD: "دج",
  EGP: "£",
  ETB: "Br",
  FJD: "$",
  GHS: "₵",
  GIP: "£",
  GMD: "D",
  GTQ: "Q",
  GYD: "$",
  HNL: "L",
  HRK: "kn",
  HTG: "G",
  IDR: "Rp",
  JMD: "$",
  KES: "Sh",
  KGS: "с",
  KHR: "៛",
  KYD: "$",
  KZT: "₸",
  LAK: "₭",
  LKR: "Rs",
  LRD: "$",
  LSL: "L",
  MAD: "د.م.",
  MDL: "L",
  MKD: "ден",
  MMK: "Ks",
  MNT: "₮",
  MOP: "P",
  MUR: "₨",
  MVR: "Rf",
  MWK: "MK",
  NAD: "$",
  NGN: "₦",
  NIO: "C$",
  NPR: "Rs",
  PEN: "S/",
  PGK: "K",
  PKR: "₨",
  QAR: "﷼",
  SAR: "﷼",
  SCR: "₨",
  SLL: "Le",
  SOS: "Sh",
  SSP: "£",
  SVC: "₡",
  SZL: "L",
  TTD: "$",
  TZS: "Sh",
  UYU: "$",
  UZS: "soʻm",
  YER: "﷼",
  ZAR: "R",
  TRY: "₺",
};

export function isAcceptedCurrencyCode(currencyCode: string): currencyCode is CurrencyCode {
  return Object.keys(currencySymbols).includes(currencyCode);
}
