import getConfig from "next/config";

const { publicRuntimeConfig } = getConfig();

const {
  NEXT_PUBLIC_WEBAPP_URL,
  NEXT_PUBLIC_WEBSITE_URL,
  NEXT_PUBLIC_APP_NAME,
  NEXT_PUBLIC_SUPPORT_MAIL_ADDRESS,
  NEXT_PUBLIC_COMPANY_NAME,
  NEXT_PUBLIC_SENDER_ID,
  NEXT_PUBLIC_SENDGRID_SENDER_NAME,
  NEXT_PUBLIC_IS_E2E,
  NEXT_PUBLIC_STRIPE_PREMIUM_PLAN_PRICE_MONTHLY,
  NEXT_PUBLIC_SENTRY_DSN,
  NEXT_PUBLIC_DEBUG,
  NEXT_PUBLIC_DISABLE_SIGNUP,
} = publicRuntimeConfig;

export const AppConfig = {
  env: {
    NEXT_PUBLIC_WEBAPP_URL,
    NEXT_PUBLIC_WEBSITE_URL,
    NEXT_PUBLIC_APP_NAME,
    NEXT_PUBLIC_SUPPORT_MAIL_ADDRESS,
    NEXT_PUBLIC_COMPANY_NAME,
    NEXT_PUBLIC_SENDER_ID,
    NEXT_PUBLIC_SENDGRID_SENDER_NAME,
    NEXT_PUBLIC_IS_E2E,
    NEXT_PUBLIC_STRIPE_PREMIUM_PLAN_PRICE_MONTHLY,
    NEXT_PUBLIC_SENTRY_DSN,
    NEXT_PUBLIC_DEBUG,
    NEXT_PUBLIC_DISABLE_SIGNUP,
    WEBAPP_URL: NEXT_PUBLIC_WEBAPP_URL,
  },
};
