/* tslint:disable */
/* eslint-disable */
/**
 * @calcom/api: Public API for Cal.com
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddTeamRequest
 */
export interface AddTeamRequest {
    /**
     * Name of the team
     * @type {string}
     * @memberof AddTeamRequest
     */
    name: string;
    /**
     * A unique slug that works as path for the team public page
     * @type {string}
     * @memberof AddTeamRequest
     */
    slug: string;
}

/**
 * Check if a given object implements the AddTeamRequest interface.
 */
export function instanceOfAddTeamRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "slug" in value;

    return isInstance;
}

export function AddTeamRequestFromJSON(json: any): AddTeamRequest {
    return AddTeamRequestFromJSONTyped(json, false);
}

export function AddTeamRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddTeamRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'slug': json['slug'],
    };
}

export function AddTeamRequestToJSON(value?: AddTeamRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'slug': value.slug,
    };
}

