/* tslint:disable */
/* eslint-disable */
/**
 * @calcom/api: Public API for Cal.com
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditAttendeeByIdRequest
 */
export interface EditAttendeeByIdRequest {
    /**
     * 
     * @type {string}
     * @memberof EditAttendeeByIdRequest
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof EditAttendeeByIdRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof EditAttendeeByIdRequest
     */
    timeZone?: string;
}

/**
 * Check if a given object implements the EditAttendeeByIdRequest interface.
 */
export function instanceOfEditAttendeeByIdRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EditAttendeeByIdRequestFromJSON(json: any): EditAttendeeByIdRequest {
    return EditAttendeeByIdRequestFromJSONTyped(json, false);
}

export function EditAttendeeByIdRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditAttendeeByIdRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'timeZone': !exists(json, 'timeZone') ? undefined : json['timeZone'],
    };
}

export function EditAttendeeByIdRequestToJSON(value?: EditAttendeeByIdRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'name': value.name,
        'timeZone': value.timeZone,
    };
}

