/** Number of months to check for booking conflicts */
export const CONFLICT_CHECK_MONTHS = 3;

/** Number of days to cache holiday data */
export const HOLIDAY_CACHE_DAYS = 7;

/**
 * Google Calendar IDs for religious holiday calendars.
 * These are separate from country-specific holidays.
 */
export const GOOGLE_RELIGIOUS_HOLIDAY_CALENDARS: Record<string, { name: string; calendarId: string }> = {
  CHRISTIAN: { name: "Christian Holidays", calendarId: "en.christian#holiday@group.v.calendar.google.com" },
  HINDU: { name: "Hindu Holidays", calendarId: "en.hinduism#holiday@group.v.calendar.google.com" },
  JEWISH: { name: "Jewish Holidays", calendarId: "en.judaism#holiday@group.v.calendar.google.com" },
  MUSLIM: { name: "Muslim Holidays", calendarId: "en.islamic#holiday@group.v.calendar.google.com" },
  ORTHODOX: {
    name: "Orthodox Holidays",
    calendarId: "en.orthodox_christianity#holiday@group.v.calendar.google.com",
  },
};

/**
 * Google Calendar IDs for public holiday calendars by country.
 * Source: Google Calendar API
 */
export const GOOGLE_HOLIDAY_CALENDARS: Record<string, { name: string; calendarId: string }> = {
  ...GOOGLE_RELIGIOUS_HOLIDAY_CALENDARS,

  // Countries A-Z
  AF: { name: "Afghanistan", calendarId: "en.af.official#holiday@group.v.calendar.google.com" },
  AL: { name: "Albania", calendarId: "en.al.official#holiday@group.v.calendar.google.com" },
  DZ: { name: "Algeria", calendarId: "en.dz.official#holiday@group.v.calendar.google.com" },
  AS: { name: "American Samoa", calendarId: "en.as.official#holiday@group.v.calendar.google.com" },
  AD: { name: "Andorra", calendarId: "en.ad.official#holiday@group.v.calendar.google.com" },
  AO: { name: "Angola", calendarId: "en.ao.official#holiday@group.v.calendar.google.com" },
  AI: { name: "Anguilla", calendarId: "en.ai.official#holiday@group.v.calendar.google.com" },
  AG: { name: "Antigua & Barbuda", calendarId: "en.ag.official#holiday@group.v.calendar.google.com" },
  AR: { name: "Argentina", calendarId: "en.ar.official#holiday@group.v.calendar.google.com" },
  AM: { name: "Armenia", calendarId: "en.am.official#holiday@group.v.calendar.google.com" },
  AW: { name: "Aruba", calendarId: "en.aw.official#holiday@group.v.calendar.google.com" },
  AU: { name: "Australia", calendarId: "en.australian.official#holiday@group.v.calendar.google.com" },
  AT: { name: "Austria", calendarId: "en.austrian.official#holiday@group.v.calendar.google.com" },
  AZ: { name: "Azerbaijan", calendarId: "en.az.official#holiday@group.v.calendar.google.com" },
  BS: { name: "Bahamas", calendarId: "en.bs.official#holiday@group.v.calendar.google.com" },
  BH: { name: "Bahrain", calendarId: "en.bh.official#holiday@group.v.calendar.google.com" },
  BD: { name: "Bangladesh", calendarId: "en.bd.official#holiday@group.v.calendar.google.com" },
  BB: { name: "Barbados", calendarId: "en.bb.official#holiday@group.v.calendar.google.com" },
  BY: { name: "Belarus", calendarId: "en.by.official#holiday@group.v.calendar.google.com" },
  BE: { name: "Belgium", calendarId: "en.be.official#holiday@group.v.calendar.google.com" },
  BZ: { name: "Belize", calendarId: "en.bz.official#holiday@group.v.calendar.google.com" },
  BJ: { name: "Benin", calendarId: "en.bj.official#holiday@group.v.calendar.google.com" },
  BM: { name: "Bermuda", calendarId: "en.bm.official#holiday@group.v.calendar.google.com" },
  BT: { name: "Bhutan", calendarId: "en.bt.official#holiday@group.v.calendar.google.com" },
  BO: { name: "Bolivia", calendarId: "en.bo.official#holiday@group.v.calendar.google.com" },
  BA: { name: "Bosnia & Herzegovina", calendarId: "en.ba.official#holiday@group.v.calendar.google.com" },
  BW: { name: "Botswana", calendarId: "en.bw.official#holiday@group.v.calendar.google.com" },
  BR: { name: "Brazil", calendarId: "en.brazilian.official#holiday@group.v.calendar.google.com" },
  VG: { name: "British Virgin Islands", calendarId: "en.vg.official#holiday@group.v.calendar.google.com" },
  BN: { name: "Brunei", calendarId: "en.bn.official#holiday@group.v.calendar.google.com" },
  BG: { name: "Bulgaria", calendarId: "en.bulgarian.official#holiday@group.v.calendar.google.com" },
  BF: { name: "Burkina Faso", calendarId: "en.bf.official#holiday@group.v.calendar.google.com" },
  BI: { name: "Burundi", calendarId: "en.bi.official#holiday@group.v.calendar.google.com" },
  KH: { name: "Cambodia", calendarId: "en.kh.official#holiday@group.v.calendar.google.com" },
  CM: { name: "Cameroon", calendarId: "en.cm.official#holiday@group.v.calendar.google.com" },
  CA: { name: "Canada", calendarId: "en.canadian.official#holiday@group.v.calendar.google.com" },
  CV: { name: "Cape Verde", calendarId: "en.cv.official#holiday@group.v.calendar.google.com" },
  KY: { name: "Cayman Islands", calendarId: "en.ky.official#holiday@group.v.calendar.google.com" },
  CF: { name: "Central African Republic", calendarId: "en.cf.official#holiday@group.v.calendar.google.com" },
  TD: { name: "Chad", calendarId: "en.td.official#holiday@group.v.calendar.google.com" },
  CL: { name: "Chile", calendarId: "en.cl.official#holiday@group.v.calendar.google.com" },
  CN: { name: "China", calendarId: "en.china.official#holiday@group.v.calendar.google.com" },
  CO: { name: "Colombia", calendarId: "en.co.official#holiday@group.v.calendar.google.com" },
  KM: { name: "Comoros", calendarId: "en.km.official#holiday@group.v.calendar.google.com" },
  CG: { name: "Congo - Brazzaville", calendarId: "en.cg.official#holiday@group.v.calendar.google.com" },
  CD: { name: "Congo - Kinshasa", calendarId: "en.cd.official#holiday@group.v.calendar.google.com" },
  CK: { name: "Cook Islands", calendarId: "en.ck.official#holiday@group.v.calendar.google.com" },
  CR: { name: "Costa Rica", calendarId: "en.cr.official#holiday@group.v.calendar.google.com" },
  CI: { name: "Côte d'Ivoire", calendarId: "en.ci.official#holiday@group.v.calendar.google.com" },
  HR: { name: "Croatia", calendarId: "en.croatian.official#holiday@group.v.calendar.google.com" },
  CU: { name: "Cuba", calendarId: "en.cu.official#holiday@group.v.calendar.google.com" },
  CW: { name: "Curaçao", calendarId: "en.cw.official#holiday@group.v.calendar.google.com" },
  CY: { name: "Cyprus", calendarId: "en.cy.official#holiday@group.v.calendar.google.com" },
  CZ: { name: "Czechia", calendarId: "en.czech.official#holiday@group.v.calendar.google.com" },
  DK: { name: "Denmark", calendarId: "en.danish.official#holiday@group.v.calendar.google.com" },
  DJ: { name: "Djibouti", calendarId: "en.dj.official#holiday@group.v.calendar.google.com" },
  DM: { name: "Dominica", calendarId: "en.dm.official#holiday@group.v.calendar.google.com" },
  DO: { name: "Dominican Republic", calendarId: "en.do.official#holiday@group.v.calendar.google.com" },
  EC: { name: "Ecuador", calendarId: "en.ec.official#holiday@group.v.calendar.google.com" },
  EG: { name: "Egypt", calendarId: "en.eg.official#holiday@group.v.calendar.google.com" },
  SV: { name: "El Salvador", calendarId: "en.sv.official#holiday@group.v.calendar.google.com" },
  GQ: { name: "Equatorial Guinea", calendarId: "en.gq.official#holiday@group.v.calendar.google.com" },
  ER: { name: "Eritrea", calendarId: "en.er.official#holiday@group.v.calendar.google.com" },
  EE: { name: "Estonia", calendarId: "en.ee.official#holiday@group.v.calendar.google.com" },
  SZ: { name: "Eswatini", calendarId: "en.sz.official#holiday@group.v.calendar.google.com" },
  ET: { name: "Ethiopia", calendarId: "en.et.official#holiday@group.v.calendar.google.com" },
  FK: {
    name: "Falkland Islands (Islas Malvinas)",
    calendarId: "en.fk.official#holiday@group.v.calendar.google.com",
  },
  FO: { name: "Faroe Islands", calendarId: "en.fo.official#holiday@group.v.calendar.google.com" },
  FJ: { name: "Fiji", calendarId: "en.fj.official#holiday@group.v.calendar.google.com" },
  FI: { name: "Finland", calendarId: "en.finnish.official#holiday@group.v.calendar.google.com" },
  FR: { name: "France", calendarId: "en.french.official#holiday@group.v.calendar.google.com" },
  GF: { name: "French Guiana", calendarId: "en.gf.official#holiday@group.v.calendar.google.com" },
  PF: { name: "French Polynesia", calendarId: "en.pf.official#holiday@group.v.calendar.google.com" },
  GA: { name: "Gabon", calendarId: "en.ga.official#holiday@group.v.calendar.google.com" },
  GM: { name: "Gambia", calendarId: "en.gm.official#holiday@group.v.calendar.google.com" },
  GE: { name: "Georgia", calendarId: "en.ge.official#holiday@group.v.calendar.google.com" },
  DE: { name: "Germany", calendarId: "en.german.official#holiday@group.v.calendar.google.com" },
  GH: { name: "Ghana", calendarId: "en.gh.official#holiday@group.v.calendar.google.com" },
  GI: { name: "Gibraltar", calendarId: "en.gi.official#holiday@group.v.calendar.google.com" },
  GR: { name: "Greece", calendarId: "en.greek.official#holiday@group.v.calendar.google.com" },
  GL: { name: "Greenland", calendarId: "en.gl.official#holiday@group.v.calendar.google.com" },
  GD: { name: "Grenada", calendarId: "en.gd.official#holiday@group.v.calendar.google.com" },
  GP: { name: "Guadeloupe", calendarId: "en.gp.official#holiday@group.v.calendar.google.com" },
  GU: { name: "Guam", calendarId: "en.gu.official#holiday@group.v.calendar.google.com" },
  GT: { name: "Guatemala", calendarId: "en.gt.official#holiday@group.v.calendar.google.com" },
  GG: { name: "Guernsey", calendarId: "en.gg.official#holiday@group.v.calendar.google.com" },
  GN: { name: "Guinea", calendarId: "en.gn.official#holiday@group.v.calendar.google.com" },
  GW: { name: "Guinea-Bissau", calendarId: "en.gw.official#holiday@group.v.calendar.google.com" },
  GY: { name: "Guyana", calendarId: "en.gy.official#holiday@group.v.calendar.google.com" },
  HT: { name: "Haiti", calendarId: "en.ht.official#holiday@group.v.calendar.google.com" },
  HN: { name: "Honduras", calendarId: "en.hn.official#holiday@group.v.calendar.google.com" },
  HK: { name: "Hong Kong", calendarId: "en.hong_kong.official#holiday@group.v.calendar.google.com" },
  HU: { name: "Hungary", calendarId: "en.hungarian.official#holiday@group.v.calendar.google.com" },
  IS: { name: "Iceland", calendarId: "en.is.official#holiday@group.v.calendar.google.com" },
  IN: { name: "India", calendarId: "en.indian.official#holiday@group.v.calendar.google.com" },
  ID: { name: "Indonesia", calendarId: "en.indonesian.official#holiday@group.v.calendar.google.com" },
  IR: { name: "Iran", calendarId: "en.ir.official#holiday@group.v.calendar.google.com" },
  IQ: { name: "Iraq", calendarId: "en.iq.official#holiday@group.v.calendar.google.com" },
  IE: { name: "Ireland", calendarId: "en.irish.official#holiday@group.v.calendar.google.com" },
  IM: { name: "Isle of Man", calendarId: "en.im.official#holiday@group.v.calendar.google.com" },
  IL: { name: "Israel", calendarId: "en.jewish.official#holiday@group.v.calendar.google.com" },
  IT: { name: "Italy", calendarId: "en.italian.official#holiday@group.v.calendar.google.com" },
  JM: { name: "Jamaica", calendarId: "en.jm.official#holiday@group.v.calendar.google.com" },
  JP: { name: "Japan", calendarId: "en.japanese.official#holiday@group.v.calendar.google.com" },
  JE: { name: "Jersey", calendarId: "en.je.official#holiday@group.v.calendar.google.com" },
  JO: { name: "Jordan", calendarId: "en.jo.official#holiday@group.v.calendar.google.com" },
  KZ: { name: "Kazakhstan", calendarId: "en.kz.official#holiday@group.v.calendar.google.com" },
  KE: { name: "Kenya", calendarId: "en.ke.official#holiday@group.v.calendar.google.com" },
  KI: { name: "Kiribati", calendarId: "en.ki.official#holiday@group.v.calendar.google.com" },
  XK: { name: "Kosovo", calendarId: "en.xk.official#holiday@group.v.calendar.google.com" },
  KW: { name: "Kuwait", calendarId: "en.kw.official#holiday@group.v.calendar.google.com" },
  KG: { name: "Kyrgyzstan", calendarId: "en.kg.official#holiday@group.v.calendar.google.com" },
  LA: { name: "Laos", calendarId: "en.la.official#holiday@group.v.calendar.google.com" },
  LV: { name: "Latvia", calendarId: "en.latvian.official#holiday@group.v.calendar.google.com" },
  LB: { name: "Lebanon", calendarId: "en.lb.official#holiday@group.v.calendar.google.com" },
  LS: { name: "Lesotho", calendarId: "en.ls.official#holiday@group.v.calendar.google.com" },
  LR: { name: "Liberia", calendarId: "en.lr.official#holiday@group.v.calendar.google.com" },
  LY: { name: "Libya", calendarId: "en.ly.official#holiday@group.v.calendar.google.com" },
  LI: { name: "Liechtenstein", calendarId: "en.li.official#holiday@group.v.calendar.google.com" },
  LT: { name: "Lithuania", calendarId: "en.lithuanian.official#holiday@group.v.calendar.google.com" },
  LU: { name: "Luxembourg", calendarId: "en.lu.official#holiday@group.v.calendar.google.com" },
  MO: { name: "Macao", calendarId: "en.mo.official#holiday@group.v.calendar.google.com" },
  MG: { name: "Madagascar", calendarId: "en.mg.official#holiday@group.v.calendar.google.com" },
  MW: { name: "Malawi", calendarId: "en.mw.official#holiday@group.v.calendar.google.com" },
  MY: { name: "Malaysia", calendarId: "en.malaysia.official#holiday@group.v.calendar.google.com" },
  MV: { name: "Maldives", calendarId: "en.mv.official#holiday@group.v.calendar.google.com" },
  ML: { name: "Mali", calendarId: "en.ml.official#holiday@group.v.calendar.google.com" },
  MT: { name: "Malta", calendarId: "en.mt.official#holiday@group.v.calendar.google.com" },
  MH: { name: "Marshall Islands", calendarId: "en.mh.official#holiday@group.v.calendar.google.com" },
  MQ: { name: "Martinique", calendarId: "en.mq.official#holiday@group.v.calendar.google.com" },
  MR: { name: "Mauritania", calendarId: "en.mr.official#holiday@group.v.calendar.google.com" },
  MU: { name: "Mauritius", calendarId: "en.mu.official#holiday@group.v.calendar.google.com" },
  YT: { name: "Mayotte", calendarId: "en.yt.official#holiday@group.v.calendar.google.com" },
  MX: { name: "Mexico", calendarId: "en.mexican.official#holiday@group.v.calendar.google.com" },
  FM: { name: "Micronesia", calendarId: "en.fm.official#holiday@group.v.calendar.google.com" },
  MD: { name: "Moldova", calendarId: "en.md.official#holiday@group.v.calendar.google.com" },
  MC: { name: "Monaco", calendarId: "en.mc.official#holiday@group.v.calendar.google.com" },
  MN: { name: "Mongolia", calendarId: "en.mn.official#holiday@group.v.calendar.google.com" },
  ME: { name: "Montenegro", calendarId: "en.me.official#holiday@group.v.calendar.google.com" },
  MS: { name: "Montserrat", calendarId: "en.ms.official#holiday@group.v.calendar.google.com" },
  MA: { name: "Morocco", calendarId: "en.ma.official#holiday@group.v.calendar.google.com" },
  MZ: { name: "Mozambique", calendarId: "en.mz.official#holiday@group.v.calendar.google.com" },
  MM: { name: "Myanmar (Burma)", calendarId: "en.mm.official#holiday@group.v.calendar.google.com" },
  NA: { name: "Namibia", calendarId: "en.na.official#holiday@group.v.calendar.google.com" },
  NR: { name: "Nauru", calendarId: "en.nr.official#holiday@group.v.calendar.google.com" },
  NP: { name: "Nepal", calendarId: "en.np.official#holiday@group.v.calendar.google.com" },
  NL: { name: "Netherlands", calendarId: "en.dutch.official#holiday@group.v.calendar.google.com" },
  NC: { name: "New Caledonia", calendarId: "en.nc.official#holiday@group.v.calendar.google.com" },
  NZ: { name: "New Zealand", calendarId: "en.new_zealand.official#holiday@group.v.calendar.google.com" },
  NI: { name: "Nicaragua", calendarId: "en.ni.official#holiday@group.v.calendar.google.com" },
  NE: { name: "Niger", calendarId: "en.ne.official#holiday@group.v.calendar.google.com" },
  NG: { name: "Nigeria", calendarId: "en.ng.official#holiday@group.v.calendar.google.com" },
  MP: { name: "Northern Mariana Islands", calendarId: "en.mp.official#holiday@group.v.calendar.google.com" },
  KP: { name: "North Korea", calendarId: "en.kp.official#holiday@group.v.calendar.google.com" },
  MK: { name: "North Macedonia", calendarId: "en.mk.official#holiday@group.v.calendar.google.com" },
  NO: { name: "Norway", calendarId: "en.norwegian.official#holiday@group.v.calendar.google.com" },
  OM: { name: "Oman", calendarId: "en.om.official#holiday@group.v.calendar.google.com" },
  PK: { name: "Pakistan", calendarId: "en.pk.official#holiday@group.v.calendar.google.com" },
  PW: { name: "Palau", calendarId: "en.pw.official#holiday@group.v.calendar.google.com" },
  PA: { name: "Panama", calendarId: "en.pa.official#holiday@group.v.calendar.google.com" },
  PG: { name: "Papua New Guinea", calendarId: "en.pg.official#holiday@group.v.calendar.google.com" },
  PY: { name: "Paraguay", calendarId: "en.py.official#holiday@group.v.calendar.google.com" },
  PE: { name: "Peru", calendarId: "en.pe.official#holiday@group.v.calendar.google.com" },
  PH: { name: "Philippines", calendarId: "en.philippines.official#holiday@group.v.calendar.google.com" },
  PL: { name: "Poland", calendarId: "en.polish.official#holiday@group.v.calendar.google.com" },
  PT: { name: "Portugal", calendarId: "en.portuguese.official#holiday@group.v.calendar.google.com" },
  PR: { name: "Puerto Rico", calendarId: "en.pr.official#holiday@group.v.calendar.google.com" },
  QA: { name: "Qatar", calendarId: "en.qa.official#holiday@group.v.calendar.google.com" },
  RE: { name: "Réunion", calendarId: "en.re.official#holiday@group.v.calendar.google.com" },
  RO: { name: "Romania", calendarId: "en.romanian.official#holiday@group.v.calendar.google.com" },
  RU: { name: "Russia", calendarId: "en.russian.official#holiday@group.v.calendar.google.com" },
  RW: { name: "Rwanda", calendarId: "en.rw.official#holiday@group.v.calendar.google.com" },
  WS: { name: "Samoa", calendarId: "en.ws.official#holiday@group.v.calendar.google.com" },
  SM: { name: "San Marino", calendarId: "en.sm.official#holiday@group.v.calendar.google.com" },
  ST: { name: "São Tomé & Príncipe", calendarId: "en.st.official#holiday@group.v.calendar.google.com" },
  SA: { name: "Saudi Arabia", calendarId: "en.saudiarabian.official#holiday@group.v.calendar.google.com" },
  SN: { name: "Senegal", calendarId: "en.sn.official#holiday@group.v.calendar.google.com" },
  RS: { name: "Serbia", calendarId: "en.rs.official#holiday@group.v.calendar.google.com" },
  SC: { name: "Seychelles", calendarId: "en.sc.official#holiday@group.v.calendar.google.com" },
  SL: { name: "Sierra Leone", calendarId: "en.sl.official#holiday@group.v.calendar.google.com" },
  SG: { name: "Singapore", calendarId: "en.singapore.official#holiday@group.v.calendar.google.com" },
  SX: { name: "Sint Maarten", calendarId: "en.sx.official#holiday@group.v.calendar.google.com" },
  SK: { name: "Slovakia", calendarId: "en.slovak.official#holiday@group.v.calendar.google.com" },
  SI: { name: "Slovenia", calendarId: "en.slovenian.official#holiday@group.v.calendar.google.com" },
  SB: { name: "Solomon Islands", calendarId: "en.sb.official#holiday@group.v.calendar.google.com" },
  SO: { name: "Somalia", calendarId: "en.so.official#holiday@group.v.calendar.google.com" },
  ZA: { name: "South Africa", calendarId: "en.sa.official#holiday@group.v.calendar.google.com" },
  KR: { name: "South Korea", calendarId: "en.south_korea.official#holiday@group.v.calendar.google.com" },
  SS: { name: "South Sudan", calendarId: "en.ss.official#holiday@group.v.calendar.google.com" },
  ES: { name: "Spain", calendarId: "en.spain.official#holiday@group.v.calendar.google.com" },
  LK: { name: "Sri Lanka", calendarId: "en.lk.official#holiday@group.v.calendar.google.com" },
  BL: { name: "St. Barthélemy", calendarId: "en.bl.official#holiday@group.v.calendar.google.com" },
  SH: { name: "St. Helena", calendarId: "en.sh.official#holiday@group.v.calendar.google.com" },
  KN: { name: "St. Kitts & Nevis", calendarId: "en.kn.official#holiday@group.v.calendar.google.com" },
  LC: { name: "St. Lucia", calendarId: "en.lc.official#holiday@group.v.calendar.google.com" },
  MF: { name: "St. Martin", calendarId: "en.mf.official#holiday@group.v.calendar.google.com" },
  PM: { name: "St. Pierre & Miquelon", calendarId: "en.pm.official#holiday@group.v.calendar.google.com" },
  VC: { name: "St. Vincent & Grenadines", calendarId: "en.vc.official#holiday@group.v.calendar.google.com" },
  SD: { name: "Sudan", calendarId: "en.sd.official#holiday@group.v.calendar.google.com" },
  SR: { name: "Suriname", calendarId: "en.sr.official#holiday@group.v.calendar.google.com" },
  SE: { name: "Sweden", calendarId: "en.swedish.official#holiday@group.v.calendar.google.com" },
  CH: { name: "Switzerland", calendarId: "en.ch.official#holiday@group.v.calendar.google.com" },
  SY: { name: "Syria", calendarId: "en.sy.official#holiday@group.v.calendar.google.com" },
  TW: { name: "Taiwan", calendarId: "en.taiwan.official#holiday@group.v.calendar.google.com" },
  TJ: { name: "Tajikistan", calendarId: "en.tj.official#holiday@group.v.calendar.google.com" },
  TZ: { name: "Tanzania", calendarId: "en.tz.official#holiday@group.v.calendar.google.com" },
  TH: { name: "Thailand", calendarId: "en.th.official#holiday@group.v.calendar.google.com" },
  TL: { name: "Timor-Leste", calendarId: "en.tl.official#holiday@group.v.calendar.google.com" },
  TG: { name: "Togo", calendarId: "en.tg.official#holiday@group.v.calendar.google.com" },
  TO: { name: "Tonga", calendarId: "en.to.official#holiday@group.v.calendar.google.com" },
  TT: { name: "Trinidad & Tobago", calendarId: "en.tt.official#holiday@group.v.calendar.google.com" },
  TN: { name: "Tunisia", calendarId: "en.tn.official#holiday@group.v.calendar.google.com" },
  TR: { name: "Turkey", calendarId: "en.turkish.official#holiday@group.v.calendar.google.com" },
  TM: { name: "Turkmenistan", calendarId: "en.tm.official#holiday@group.v.calendar.google.com" },
  TC: { name: "Turks & Caicos Islands", calendarId: "en.tc.official#holiday@group.v.calendar.google.com" },
  TV: { name: "Tuvalu", calendarId: "en.tv.official#holiday@group.v.calendar.google.com" },
  VI: { name: "U.S. Virgin Islands", calendarId: "en.vi.official#holiday@group.v.calendar.google.com" },
  UG: { name: "Uganda", calendarId: "en.ug.official#holiday@group.v.calendar.google.com" },
  UA: { name: "Ukraine", calendarId: "en.ukrainian.official#holiday@group.v.calendar.google.com" },
  AE: { name: "United Arab Emirates", calendarId: "en.ae.official#holiday@group.v.calendar.google.com" },
  GB: { name: "United Kingdom", calendarId: "en.uk.official#holiday@group.v.calendar.google.com" },
  US: { name: "United States", calendarId: "en.usa.official#holiday@group.v.calendar.google.com" },
  UY: { name: "Uruguay", calendarId: "en.uy.official#holiday@group.v.calendar.google.com" },
  UZ: { name: "Uzbekistan", calendarId: "en.uz.official#holiday@group.v.calendar.google.com" },
  VU: { name: "Vanuatu", calendarId: "en.vu.official#holiday@group.v.calendar.google.com" },
  VA: { name: "Vatican City", calendarId: "en.va.official#holiday@group.v.calendar.google.com" },
  VE: { name: "Venezuela", calendarId: "en.ve.official#holiday@group.v.calendar.google.com" },
  VN: { name: "Vietnam", calendarId: "en.vietnamese.official#holiday@group.v.calendar.google.com" },
  WF: { name: "Wallis & Futuna", calendarId: "en.wf.official#holiday@group.v.calendar.google.com" },
  YE: { name: "Yemen", calendarId: "en.ye.official#holiday@group.v.calendar.google.com" },
  ZM: { name: "Zambia", calendarId: "en.zm.official#holiday@group.v.calendar.google.com" },
  ZW: { name: "Zimbabwe", calendarId: "en.zw.official#holiday@group.v.calendar.google.com" },
};
