# Actionlint configuration for custom self-hosted runner labels
self-hosted-runner:
  labels:
    - buildjet-2vcpu-ubuntu-2204
    - buildjet-4vcpu-ubuntu-2204
    - buildjet-8vcpu-ubuntu-2204
    - buildjet-16vcpu-ubuntu-2204
