nodeLinker: node-modules
enableGlobalCache: true

logFilters:
  - code: YN0002 # Ignore peer dependency warnings
    level: discard
  - code: YN0060 # Ignore peer dependency version mismatches
    level: discard

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.4.1.cjs

packageExtensions:
  "typescript@*":
    dependencies:
      "typescript": "5.4.2"
