[phases.install]
onlyIncludeFiles = [
  ".npmrc",
  "package.json",
  "yarn.lock",
  ".yarnrc.yml",
	".yarn/patches/dayjs-npm-1.11.2-644b12fe04.patch",
	".yarn/patches/dayjs-npm-1.11.4-97921cd375.patch",
	".yarn/patches/libphonenumber-js-npm-1.10.51-4ff79b15f8.patch",
	".yarn/patches/next-i18next-npm-13.3.0-bf25b0943c.patch",
	".yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs",
	".yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs",
	".yarn/releases/yarn-3.4.1.cjs",
  "package.json",
  "packages/ui/package.json",
  "packages/types/package.json",
  "packages/core/package.json",
  "packages/app-store/package.json",
  "packages/app-store-cli/package.json",
  "packages/app-store/dailyvideo/package.json",
  "packages/app-store/office365video/package.json",
  "packages/app-store/zoomvideo/package.json",
  "packages/config/package.json",
  "packages/trpc/package.json",
  "packages/tsconfig/package.json",
  "packages/emails/package.json",
  "packages/platform/atoms/package.json",
  "packages/platform/types/package.json",
  "packages/platform/constants/package.json",
  "packages/platform/libraries/package.json",
  "packages/platform/utils/package.json",
  "packages/platform/sdk/package.json",
  "packages/platform/examples/base/package.json",
  "packages/debugging/package.json",
  "packages/features/auth/package.json",
  "packages/features/ee/package.json",
  "packages/features/package.json",
  "packages/prisma/package.json",
  "packages/lib/package.json",
  "packages/dayjs/package.json",
  "packages/kysely/package.json",
  "packages/embeds/embed-snippet/package.json",
  "packages/embeds/embed-react/package.json",
  "packages/embeds/embed-core/package.json",
  "packages/eslint-plugin/package.json",
  "apps/storybook/package.json",
  "apps/swagger/package.json",
  "apps/web/package.json",
  "apps/ai/package.json",
  "apps/api/v1/package.json",
  "apps/api/v2/package.json",
  "apps/api/package.json",
  "packages/prisma/schema.prisma",
]
