[phases.install]
onlyIncludeFiles = [
  ".npmrc",
  "package.json",
  "yarn.lock",
  "turbo.json",
  ".yarnrc.yml",
	".yarn",
  "packages/ui/package.json",
  "packages/types/package.json",
  "packages/core/package.json",
  "packages/app-store/package.json",
  "packages/app-store-cli",
  "packages/app-store/dailyvideo/package.json",
  "packages/app-store/office365video/package.json",
  "packages/app-store/zoomvideo/package.json",
  "packages/config",
  "packages/trpc/package.json",
  "packages/tsconfig",
  "packages/emails/package.json",
  "packages/platform",
  "packages/debugging/package.json",
  "packages/features/auth/package.json",
  "packages/features/ee/package.json",
  "packages/features/package.json",
  "packages/prisma",
  "packages/lib/package.json",
  "packages/dayjs/package.json",
  "packages/kysely/package.json",
  "packages/embeds/embed-snippet/package.json",
  "packages/embeds/embed-react/package.json",
  "packages/embeds/embed-core/package.json",
  "packages/eslint-plugin/package.json",
  "apps/storybook/package.json",
  "apps/swagger/package.json",
  "apps/web/package.json",
  "apps/ai/package.json",
  "apps/api/v1/package.json",
  "apps/api/v2/package.json",
  "apps/api/package.json",
]
