[phases.install]
onlyIncludeFiles = [
  ".npmrc",
  "package.json",
  "yarn.lock",
  ".yarnrc.yml",
	".yarn/patches/dayjs-npm-1.11.2-644b12fe04.patch",
	".yarn/patches/dayjs-npm-1.11.4-97921cd375.patch",
	".yarn/patches/libphonenumber-js-npm-1.10.51-4ff79b15f8.patch",
	".yarn/patches/next-i18next-npm-13.3.0-bf25b0943c.patch",
	".yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs",
	".yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs",
	".yarn/releases/yarn-3.4.1.cjs",
  "package.json",
  "packages/ui/package.json",
  "packages/types/package.json",
  "packages/core/package.json",
  "packages/app-store-cli/package.json",
  "packages/config/package.json",
  "packages/trpc/package.json",
  "packages/tsconfig/package.json",
  "packages/emails/package.json",
  "packages/platform/atoms/package.json",
  "packages/platform/types/package.json",
  "packages/platform/constants/package.json",
  "packages/platform/libraries/package.json",
  "packages/platform/utils/package.json",
  "packages/platform/sdk/package.json",
  "packages/platform/examples/base/package.json",
  "packages/debugging/package.json",
  "packages/features/auth/package.json",
  "packages/features/ee/package.json",
  "packages/features/package.json",
  "packages/prisma/package.json",
  "packages/app-store/googlevideo/package.json",
  "packages/app-store/mock-payment-app/package.json",
  "packages/app-store/around/package.json",
  "packages/app-store/weather_in_your_calendar/package.json",
  "packages/app-store/riverside/package.json",
  "packages/app-store/zohocalendar/package.json",
  "packages/app-store/caldavcalendar/package.json",
  "packages/app-store/ping/package.json",
  "packages/app-store/demodesk/package.json",
  "packages/app-store/exchange2016calendar/package.json",
  "packages/app-store/discord/package.json",
  "packages/app-store/basecamp3/package.json",
  "packages/app-store/plausible/package.json",
  "packages/app-store/zoomvideo/package.json",
  "packages/app-store/wordpress/package.json",
  "packages/app-store/feishucalendar/package.json",
  "packages/app-store/sirius_video/package.json",
  "packages/app-store/sendgrid/package.json",
  "packages/app-store/shimmervideo/package.json",
  "packages/app-store/exchangecalendar/package.json",
  "packages/app-store/zapier/package.json",
  "packages/app-store/huddle01video/package.json",
  "packages/app-store/jitsivideo/package.json",
  "packages/app-store/stripepayment/package.json",
  "packages/app-store/vital/package.json",
  "packages/app-store/amie/package.json",
  "packages/app-store/office365video/package.json",
  "packages/app-store/linear/package.json",
  "packages/app-store/office365calendar/package.json",
  "packages/app-store/sylapsvideo/package.json",
  "packages/app-store/roam/package.json",
  "packages/app-store/salesroom/package.json",
  "packages/app-store/intercom/package.json",
  "packages/app-store/vimcal/package.json",
  "packages/app-store/jelly/package.json",
  "packages/app-store/giphy/package.json",
  "packages/app-store/tandemvideo/package.json",
  "packages/app-store/alby/package.json",
  "packages/app-store/deel/package.json",
  "packages/app-store/typeform/package.json",
  "packages/app-store/pipedream/package.json",
  "packages/app-store/hubspot/package.json",
  "packages/app-store/metapixel/package.json",
  "packages/app-store/ga4/package.json",
  "packages/app-store/mirotalk/package.json",
  "packages/app-store/n8n/package.json",
  "packages/app-store/zoho-bigin/package.json",
  "packages/app-store/autocheckin/package.json",
  "packages/app-store/campfire/package.json",
  "packages/app-store/package.json",
  "packages/app-store/webex/package.json",
  "packages/app-store/pipedrive-crm/package.json",
  "packages/app-store/make/package.json",
  "packages/app-store/paypal/package.json",
  "packages/app-store/raycast/package.json",
  "packages/app-store/telegram/package.json",
  "packages/app-store/closecom/package.json",
  "packages/app-store/fathom/package.json",
  "packages/app-store/cal-ai/package.json",
  "packages/app-store/facetime/package.json",
  "packages/app-store/whereby/package.json",
  "packages/app-store/templates/booking-pages-tag/package.json",
  "packages/app-store/templates/basic/package.json",
  "packages/app-store/templates/event-type-location-video-static/package.json",
  "packages/app-store/templates/link-as-an-app/package.json",
  "packages/app-store/templates/general-app-settings/package.json",
  "packages/app-store/templates/event-type-app-card/package.json",
  "packages/app-store/eightxeight/package.json",
  "packages/app-store/salesforce/package.json",
  "packages/app-store/routing-forms/package.json",
  "packages/app-store/googlecalendar/package.json",
  "packages/app-store/larkcalendar/package.json",
  "packages/app-store/dailyvideo/package.json",
  "packages/app-store/gtm/package.json",
  "packages/app-store/wipemycalother/package.json",
  "packages/app-store/applecalendar/package.json",
  "packages/app-store/qr_code/package.json",
  "packages/app-store/exchange2013calendar/package.json",
  "packages/app-store/signal/package.json",
  "packages/app-store/whatsapp/package.json",
  "packages/app-store/cron/package.json",
  "packages/app-store/matomo/package.json",
  "packages/app-store/ics-feedcalendar/package.json",
  "packages/app-store/zohocrm/package.json",
  "packages/app-store/element-call/package.json",
  "packages/lib/package.json",
  "packages/dayjs/package.json",
  "packages/kysely/package.json",
  "packages/embeds/embed-snippet/package.json",
  "packages/embeds/embed-react/package.json",
  "packages/embeds/embed-core/package.json",
  "packages/eslint-plugin/package.json",
  "apps/storybook/package.json",
  "apps/swagger/package.json",
  "apps/web/package.json",
  "apps/ai/package.json",
  "apps/api/v1/package.json",
  "apps/api/v2/package.json",
  "apps/api/package.json",
]
