name: Install playwright binaries
description: "Install playwright, cache and restore if necessary"
runs:
  using: "composite"
  steps:
    - name: Get installed Playwright version
      shell: bash
      id: playwright-version
      run: |
        echo "PLAYWRIGHT_VERSION=$(node -p 'require("./package.json").devDependencies?.["@playwright/test"] ?? require("./package.json").dependencies?.["@playwright/test"]')" >> "$GITHUB_ENV"
    - name: Cache playwright binaries
      id: playwright-cache
      uses: buildjet/cache@v4
      with:
        path: |
          ~/Library/Caches/ms-playwright
          ~/.cache/ms-playwright
          ${{ github.workspace }}/node_modules/playwright
        key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}-
          ${{ runner.os }}-playwright-
    - name: Install playwright binaries only if cache miss
      if: ${{ steps.playwright-cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        echo "Playwright cache miss, installing binaries..."
        yarn playwright install --with-deps
        
    - name: Playwright binaries restored from cache successfully
      if: ${{ steps.playwright-cache.outputs.cache-hit == 'true' }}
      shell: bash
      run: echo "Playwright binaries restored from cache successfully"
