name: Install playwright binaries
description: "Install playwright, cache and restore if necessary"
runs:
  using: "composite"
  steps:
    - name: Cache playwright binaries
      id: playwright-cache
      uses: buildjet/cache@v4
      with:
        path: |
          ~/Library/Caches/ms-playwright
          ~/.cache/ms-playwright
          ${{ github.workspace }}/node_modules/playwright
        key: cache-playwright-${{ hashFiles('**/yarn.lock') }}
        restore-keys: cache-playwright-
    - name: Yarn playwright install
      shell: bash
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: yarn playwright install
