// Replace the existing mappings with the correct webhook enum values
const zapierActionToWebhookTrigger: { [key: string]: WebhookTriggerEvents } = {
  // ...
  'no-show': 'BOOKING_NO_SHOW_UPDATED',
  // ...
};
