-- CreateEnum
CREATE TYPE "AuditLogTriggerTargets" AS ENUM ('BOOKING', 'SYSTEM', 'WEBHOOKS', 'API_KEYS', 'SCHEDULE', 'EVENT_TYPES', 'TEAMS', 'USER_PROFILE', 'PASSWORD', 'IMPERSONATION', 'APPS', 'ROUTING_FORMS', 'WORKFLOWS', 'SETTINGS');

-- CreateEnum
CREATE TYPE "AuditLogSystemTriggerEvents" AS ENUM ('SYSTEM_PING', 'SYSTEM_CREDENTIALS_UPDATED', 'SYSTEM_MISC', 'SYSTEM_EVENT_OFF', 'SYSTEM_EVENT_ON');

-- CreateEnum
CREATE TYPE "AuditLogBookingTriggerEvents" AS ENUM ('BOOKING_CREATED', 'BOOKING_CONFIRMED', 'BOOKING_PAYMENT_INITIATED', 'BOOKING_PAID', 'BOOKING_RESCHEDULED', 'BOOKING_REQUESTED', 'BOOKING_CANCELLED', 'BOOKING_REJECTED');

-- CreateEnum
CREATE TYPE "AuditLogAppTriggerEvents" AS ENUM ('APP_KEYS_UPDATED');