export const envSchema = {
  type: "object",
  required: [
    "NODE_ENV",
    "PORT",
    "HOST",
    "JWT_SECRET",
    "JWT_EXPIRES_IN",
    "CORS_ORIGIN",
    "DATABASE_URL",
    "LOG_LEVEL",
    "API_KEY_PREFIX",
    "UNKEY_ROOT_KEY",
    "UNKEY_NAMESPACE",
    "PATH_PREFIX",
  ],
  properties: {
    NODE_ENV: { type: "string", enum: ["development", "production", "test"] },
    PORT: { type: "number", default: 3000 },
    HOST: { type: "string", default: "127.0.0.1" },
    JWT_SECRET: { type: "string" },
    JWT_EXPIRES_IN: { type: "string", default: "24h" },
    CORS_ORIGIN: { type: "string" },
    DATABASE_URL: { type: "string" },
    LOG_LEVEL: {
      type: "string",
      enum: ["fatal", "error", "warn", "info", "debug", "trace", "silent"],
      default: "info",
    },
    API_KEY_PREFIX: { type: "string" },
    UNKEY_ROOT_KEY: { type: "string" },
    UNKEY_NAMESPACE: { type: "string" },
    PATH_PREFIX: { type: "string", default: "/" },
  },
};
