import { Prisma } from "@calcom/prisma/client";

export const eventTypeSelect = Prisma.validator<Prisma.EventTypeSelect>()({
  id: true,
  teamId: true,
  schedulingType: true,
  userId: true,
  metadata: true,
  description: true,
  hidden: true,
  slug: true,
  length: true,
  title: true,
  requiresConfirmation: true,
  requiresConfirmationWillBlockSlot: true,
  autoTranslateDescriptionEnabled: true,
  position: true,
  offsetStart: true,
  profileId: true,
  eventName: true,
  parentId: true,
  timeZone: true,
  periodType: true,
  periodStartDate: true,
  periodEndDate: true,
  periodDays: true,
  periodCountCalendarDays: true,
  lockTimeZoneToggleOnBookingPage: true,
  requiresBookerEmailVerification: true,
  disableGuests: true,
  hideCalendarNotes: true,
  minimumBookingNotice: true,
  beforeEventBuffer: true,
  afterEventBuffer: true,
  seatsPerTimeSlot: true,
  onlyShowFirstAvailableSlot: true,
  seatsShowAttendees: true,
  seatsShowAvailabilityCount: true,
  scheduleId: true,
  instantMeetingScheduleId: true,
  price: true,
  currency: true,
  slotInterval: true,
  successRedirectUrl: true,
  isInstantEvent: true,
  instantMeetingExpiryTimeOffsetInSeconds: true,
  instantMeetingParameters: true,
  aiPhoneCallConfig: true,
  assignAllTeamMembers: true,
  isRRWeightsEnabled: true,
  rescheduleWithSameRoundRobinHost: true,
  recurringEvent: true,
  locations: true,
  bookingFields: true,
  useEventTypeDestinationCalendarEmail: true,
  secondaryEmailId: true,
  bookingLimits: true,
  durationLimits: true,
  eventTypeColor: true,
  hideCalendarEventDetails: true,
  rrSegmentQueryValue: true,
  assignRRMembersUsingSegment: true,
  maxLeadThreshold: true,
  useEventLevelSelectedCalendars: true,
});

// I don't see any strong reason other than performance to not include all scalar fields here(and that might not be realistically impacted)
// We could just use `eventTypeSelect`
export const eventTypeSelectForBookingPage = Prisma.validator<Prisma.EventTypeSelect>()({
  id: true,
  slug: true,
  minimumBookingNotice: true,
  length: true,
  offsetStart: true,
  seatsPerTimeSlot: true,
  timeZone: true,
  slotInterval: true,
  beforeEventBuffer: true,
  afterEventBuffer: true,
  bookingLimits: true,
  durationLimits: true,
  assignAllTeamMembers: true,
  schedulingType: true,
  periodType: true,
  periodStartDate: true,
  periodEndDate: true,
  onlyShowFirstAvailableSlot: true,
  periodCountCalendarDays: true,
  rescheduleWithSameRoundRobinHost: true,
  periodDays: true,
  metadata: true,
  assignRRMembersUsingSegment: true,
  rrSegmentQueryValue: true,
  maxLeadThreshold: true,
  useEventLevelSelectedCalendars: true,
});
