import {
  APPS_READ,
  APPS_WRITE,
  BOOKING_READ,
  BOOKING_WRITE,
  EVENT_TYPE_READ,
  EVENT_TYPE_WRITE,
  PROFILE_READ,
  PROFILE_WRITE,
  SCHEDULE_READ,
  SCHEDULE_WRITE,
} from "@calcom/platform-constants";
import type { AccessScope } from "@calcom/prisma/enums";

const TEAM_EVENT_TYPE_READ = 1024; // 2^10
const TEAM_EVENT_TYPE_WRITE = 2048; // 2^11
const TEAM_BOOKING_READ = 4096; // 2^12
const TEAM_BOOKING_WRITE = 8192; // 2^13
const TEAM_SCHEDULE_READ = 16384; // 2^14
const TEAM_SCHEDULE_WRITE = 32768; // 2^15
const TEAM_PROFILE_READ = 65536; // 2^16
const TEAM_PROFILE_WRITE = 131072; // 2^17
const TEAM_MEMBERSHIP_READ = 262144; // 2^18
const TEAM_MEMBERSHIP_WRITE = 524288; // 2^19
const ORG_EVENT_TYPE_READ = 1048576; // 2^20
const ORG_EVENT_TYPE_WRITE = 2097152; // 2^21
const ORG_BOOKING_READ = 4194304; // 2^22
const ORG_BOOKING_WRITE = 8388608; // 2^23
const ORG_SCHEDULE_READ = 16777216; // 2^24
const ORG_SCHEDULE_WRITE = 33554432; // 2^25
const ORG_PROFILE_READ = 67108864; // 2^26
const ORG_PROFILE_WRITE = 134217728; // 2^27

export type NewAccessScope = Exclude<AccessScope, "READ_BOOKING" | "READ_PROFILE">;

export const INDIVIDUAL_SCOPES: NewAccessScope[] = [
  "EVENT_TYPE_READ",
  "EVENT_TYPE_WRITE",
  "BOOKING_READ",
  "BOOKING_WRITE",
  "SCHEDULE_READ",
  "SCHEDULE_WRITE",
  "APPS_READ",
  "APPS_WRITE",
  "PROFILE_READ",
  "PROFILE_WRITE",
];

export const TEAM_SCOPES: NewAccessScope[] = [
  "TEAM_EVENT_TYPE_READ",
  "TEAM_EVENT_TYPE_WRITE",
  "TEAM_BOOKING_READ",
  "TEAM_BOOKING_WRITE",
  "TEAM_SCHEDULE_READ",
  "TEAM_SCHEDULE_WRITE",
  "TEAM_PROFILE_READ",
  "TEAM_PROFILE_WRITE",
  "TEAM_MEMBERSHIP_READ",
  "TEAM_MEMBERSHIP_WRITE",
];

export const ORG_SCOPES: NewAccessScope[] = [
  "ORG_EVENT_TYPE_READ",
  "ORG_EVENT_TYPE_WRITE",
  "ORG_BOOKING_READ",
  "ORG_BOOKING_WRITE",
  "ORG_SCHEDULE_READ",
  "ORG_SCHEDULE_WRITE",
  "ORG_PROFILE_READ",
  "ORG_PROFILE_WRITE",
];

export type ScopeCategory = {
  labelKey: string;
  scopes: NewAccessScope[];
};

export const OAUTH_SCOPE_CATEGORIES: ScopeCategory[] = [
  { labelKey: "oauth_scope_category_user", scopes: INDIVIDUAL_SCOPES },
  { labelKey: "oauth_scope_category_team", scopes: TEAM_SCOPES },
  { labelKey: "oauth_scope_category_organization", scopes: ORG_SCOPES },
];

export const OAUTH_SCOPES: NewAccessScope[] = [...INDIVIDUAL_SCOPES, ...TEAM_SCOPES, ...ORG_SCOPES];

export const SCOPE_EXCEEDS_CLIENT_REGISTRATION_ERROR =
  "Requested scope exceeds the client's registered scopes";

export function parseScopeParam(scopeParam: string | null | undefined): string[] {
  if (!scopeParam) {
    return [];
  }
  return scopeParam.split(/[, ]+/).filter(Boolean);
}

export function isLegacyScope(scope: string): boolean {
  return scope === "READ_BOOKING" || scope === "READ_PROFILE";
}

export function isLegacyClient(clientScopes: string[]): boolean {
  return clientScopes.length === 0 || clientScopes.every(isLegacyScope);
}

export const SCOPE_TO_PERMISSION: Record<NewAccessScope, number> = {
  EVENT_TYPE_READ: EVENT_TYPE_READ,
  EVENT_TYPE_WRITE: EVENT_TYPE_WRITE,
  BOOKING_READ: BOOKING_READ,
  BOOKING_WRITE: BOOKING_WRITE,
  SCHEDULE_READ: SCHEDULE_READ,
  SCHEDULE_WRITE: SCHEDULE_WRITE,
  APPS_READ: APPS_READ,
  APPS_WRITE: APPS_WRITE,
  PROFILE_READ: PROFILE_READ,
  PROFILE_WRITE: PROFILE_WRITE,
  TEAM_EVENT_TYPE_READ: TEAM_EVENT_TYPE_READ,
  TEAM_EVENT_TYPE_WRITE: TEAM_EVENT_TYPE_WRITE,
  TEAM_BOOKING_READ: TEAM_BOOKING_READ,
  TEAM_BOOKING_WRITE: TEAM_BOOKING_WRITE,
  TEAM_SCHEDULE_READ: TEAM_SCHEDULE_READ,
  TEAM_SCHEDULE_WRITE: TEAM_SCHEDULE_WRITE,
  TEAM_PROFILE_READ: TEAM_PROFILE_READ,
  TEAM_PROFILE_WRITE: TEAM_PROFILE_WRITE,
  TEAM_MEMBERSHIP_READ: TEAM_MEMBERSHIP_READ,
  TEAM_MEMBERSHIP_WRITE: TEAM_MEMBERSHIP_WRITE,
  ORG_EVENT_TYPE_READ: ORG_EVENT_TYPE_READ,
  ORG_EVENT_TYPE_WRITE: ORG_EVENT_TYPE_WRITE,
  ORG_BOOKING_READ: ORG_BOOKING_READ,
  ORG_BOOKING_WRITE: ORG_BOOKING_WRITE,
  ORG_SCHEDULE_READ: ORG_SCHEDULE_READ,
  ORG_SCHEDULE_WRITE: ORG_SCHEDULE_WRITE,
  ORG_PROFILE_READ: ORG_PROFILE_READ,
  ORG_PROFILE_WRITE: ORG_PROFILE_WRITE,
};

export const PERMISSION_TO_SCOPE: Record<number, NewAccessScope> = {
  [EVENT_TYPE_READ]: "EVENT_TYPE_READ",
  [EVENT_TYPE_WRITE]: "EVENT_TYPE_WRITE",
  [BOOKING_READ]: "BOOKING_READ",
  [BOOKING_WRITE]: "BOOKING_WRITE",
  [SCHEDULE_READ]: "SCHEDULE_READ",
  [SCHEDULE_WRITE]: "SCHEDULE_WRITE",
  [APPS_READ]: "APPS_READ",
  [APPS_WRITE]: "APPS_WRITE",
  [PROFILE_READ]: "PROFILE_READ",
  [PROFILE_WRITE]: "PROFILE_WRITE",
  [TEAM_EVENT_TYPE_READ]: "TEAM_EVENT_TYPE_READ",
  [TEAM_EVENT_TYPE_WRITE]: "TEAM_EVENT_TYPE_WRITE",
  [TEAM_BOOKING_READ]: "TEAM_BOOKING_READ",
  [TEAM_BOOKING_WRITE]: "TEAM_BOOKING_WRITE",
  [TEAM_SCHEDULE_READ]: "TEAM_SCHEDULE_READ",
  [TEAM_SCHEDULE_WRITE]: "TEAM_SCHEDULE_WRITE",
  [TEAM_PROFILE_READ]: "TEAM_PROFILE_READ",
  [TEAM_PROFILE_WRITE]: "TEAM_PROFILE_WRITE",
  [TEAM_MEMBERSHIP_READ]: "TEAM_MEMBERSHIP_READ",
  [TEAM_MEMBERSHIP_WRITE]: "TEAM_MEMBERSHIP_WRITE",
  [ORG_EVENT_TYPE_READ]: "ORG_EVENT_TYPE_READ",
  [ORG_EVENT_TYPE_WRITE]: "ORG_EVENT_TYPE_WRITE",
  [ORG_BOOKING_READ]: "ORG_BOOKING_READ",
  [ORG_BOOKING_WRITE]: "ORG_BOOKING_WRITE",
  [ORG_SCHEDULE_READ]: "ORG_SCHEDULE_READ",
  [ORG_SCHEDULE_WRITE]: "ORG_SCHEDULE_WRITE",
  [ORG_PROFILE_READ]: "ORG_PROFILE_READ",
  [ORG_PROFILE_WRITE]: "ORG_PROFILE_WRITE",
};
