import { qualifiedHostsModule } from "@calcom/features/qualifiedHosts/di/module";
import { redisModule } from "@calcom/features/redis/di/redisModule";
import { createContainer } from "@calcom/lib/di/di";
import { availableSlotsModule } from "@calcom/lib/di/modules/AvailableSlots";
import { bookingRepositoryModule } from "@calcom/lib/di/modules/Booking";
import { busyTimesModule } from "@calcom/lib/di/modules/BusyTimes";
import { cacheModule } from "@calcom/lib/di/modules/Cache";
import { checkBookingLimitsModule } from "@calcom/lib/di/modules/CheckBookingLimits";
import { eventTypeRepositoryModule } from "@calcom/lib/di/modules/EventType";
import { featuresRepositoryModule } from "@calcom/lib/di/modules/Features";
import { filterHostsModule } from "@calcom/lib/di/modules/FilterHosts";
import { getUserAvailabilityModule } from "@calcom/lib/di/modules/GetUserAvailability";
import { membershipRepositoryModule } from "@calcom/lib/di/modules/Membership";
import { noSlotsNotificationModule } from "@calcom/lib/di/modules/NoSlotsNotification";
import { oooRepositoryModule } from "@calcom/lib/di/modules/Ooo";
import { routingFormResponseRepositoryModule } from "@calcom/lib/di/modules/RoutingFormResponse";
import { scheduleRepositoryModule } from "@calcom/lib/di/modules/Schedule";
import { selectedSlotsRepositoryModule } from "@calcom/lib/di/modules/SelectedSlots";
import { teamRepositoryModule } from "@calcom/lib/di/modules/Team";
import { userRepositoryModule } from "@calcom/lib/di/modules/User";
import { DI_TOKENS } from "@calcom/lib/di/tokens";
import { prismaModule } from "@calcom/prisma/prisma.module";
import type { AvailableSlotsService } from "@calcom/trpc/server/routers/viewer/slots/util";

const container = createContainer();
container.load(DI_TOKENS.REDIS_CLIENT, redisModule);
container.load(DI_TOKENS.PRISMA_MODULE, prismaModule);
container.load(DI_TOKENS.OOO_REPOSITORY_MODULE, oooRepositoryModule);
container.load(DI_TOKENS.SCHEDULE_REPOSITORY_MODULE, scheduleRepositoryModule);
container.load(DI_TOKENS.SELECTED_SLOT_REPOSITORY_MODULE, selectedSlotsRepositoryModule);
container.load(DI_TOKENS.TEAM_REPOSITORY_MODULE, teamRepositoryModule);
container.load(DI_TOKENS.MEMBERSHIP_REPOSITORY_MODULE, membershipRepositoryModule);
container.load(DI_TOKENS.USER_REPOSITORY_MODULE, userRepositoryModule);
container.load(DI_TOKENS.BOOKING_REPOSITORY_MODULE, bookingRepositoryModule);
container.load(DI_TOKENS.EVENT_TYPE_REPOSITORY_MODULE, eventTypeRepositoryModule);
container.load(DI_TOKENS.ROUTING_FORM_RESPONSE_REPOSITORY_MODULE, routingFormResponseRepositoryModule);
container.load(DI_TOKENS.FEATURES_REPOSITORY_MODULE, featuresRepositoryModule);
container.load(DI_TOKENS.CACHE_SERVICE_MODULE, cacheModule);
container.load(DI_TOKENS.CHECK_BOOKING_LIMITS_SERVICE_MODULE, checkBookingLimitsModule);
container.load(DI_TOKENS.AVAILABLE_SLOTS_SERVICE_MODULE, availableSlotsModule);
container.load(DI_TOKENS.GET_USER_AVAILABILITY_SERVICE_MODULE, getUserAvailabilityModule);
container.load(DI_TOKENS.BUSY_TIMES_SERVICE_MODULE, busyTimesModule);
container.load(DI_TOKENS.BUSY_TIMES_SERVICE_MODULE, busyTimesModule);
container.load(DI_TOKENS.FILTER_HOSTS_SERVICE_MODULE, filterHostsModule);
container.load(DI_TOKENS.QUALIFIED_HOSTS_SERVICE_MODULE, qualifiedHostsModule);
container.load(DI_TOKENS.NO_SLOTS_NOTIFICATION_SERVICE_MODULE, noSlotsNotificationModule);

export function getAvailableSlotsService() {
  return container.get<AvailableSlotsService>(DI_TOKENS.AVAILABLE_SLOTS_SERVICE);
}
