-- CreateEnum
CREATE TYPE "UserPlan" AS ENUM ('INDIVIDUALS', 'TEAMS', 'ORGANIZATIONS', 'ENTERPRISE', 'PLATFORM_STARTER', 'PLATFORM_ESSENTIALS', 'PLATFORM_SCALE', 'PLATFORM_ENTERPRISE');

-- AlterTable
ALTER TABLE "users" ADD COLUMN     "plan" "UserPlan";
