blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/onehashai/Cal-ID/discussions
    about: Need help selfhosting or ask a general question about the project? Open a discussion
