name: Build production binaries
description: "Build the web app using Turbo Remote Caching"
inputs:
  node_version:
    required: false
    default: v18.x
runs:
  using: "composite"
  steps:
    - run: |
        export NODE_OPTIONS="--max_old_space_size=8192"
        yarn build
      shell: bash
