name: Cache production build binaries
description: "Cache or restore if necessary"
runs:
  using: "composite"
  steps:
    - name: Generate cache key
      id: cache-key
      uses: ./.github/actions/cache-build-key
      with:
        branch_key: ${{ github.head_ref || github.ref_name }}
    - name: Clean up cache targets before restore
      shell: bash
      run: |
        rm -rf apps/web/.next apps/web/public/embed
        find . -name ".turbo" -type d -exec rm -rf {} + 2>/dev/null || true
        find . -name "dist" -type d -not -path "*/node_modules/*" -exec rm -rf {} + 2>/dev/null || true
    - name: Cache production build
      uses: actions/cache@v4
      id: cache-build
      with:
        path: |
          ${{ github.workspace }}/apps/web/.next
          ${{ github.workspace }}/apps/web/public/embed
          **/.turbo/**
          **/dist/**
        key: ${{ steps.cache-key.outputs.key }}
    - run: |
        export NODE_OPTIONS="--max_old_space_size=8192"
        yarn build
      if: steps.cache-build.outputs.cache-hit != 'true'
      shell: bash
