name: Cache production build binaries
description: "Cache or restore if necessary"
inputs:
  node_version:
    required: false
    default: v18.x
runs:
  using: "composite"
  steps:
    - name: Cache production build
      uses: actions/cache@v4
      id: cache-build
      env:
        cache-name: prod-build
        # Use branch name for cache scoping (head_ref for PRs, ref_name for pushes)
        branch-key: ${{ github.head_ref || github.ref_name }}
        # Hash yarn.lock for dependency changes
        lockfile-hash: ${{ hashFiles('yarn.lock') }}
        # Hash source files that affect the web build, excluding generated directories
        # This excludes packages/prisma/zod/*, packages/kysely/* which are generated
        source-hash: ${{ hashFiles('apps/web/**/*.[jt]s', 'apps/web/**/*.[jt]sx', 'apps/web/**/*.json', 'apps/web/**/*.css', 'packages/prisma/schema.prisma', 'packages/prisma/migrations/**/*.sql', 'packages/*/src/**/*.[jt]s', 'packages/*/src/**/*.[jt]sx', '!**/node_modules/**') }}
      with:
        path: |
          ${{ github.workspace }}/apps/web/.next
          ${{ github.workspace }}/apps/web/public/embed
          **/.turbo/**
          **/dist/**
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ inputs.node_version }}-${{ env.branch-key }}-${{ env.lockfile-hash }}-${{ env.source-hash }}
        restore-keys: |
          ${{ runner.os }}-${{ env.cache-name }}-${{ inputs.node_version }}-${{ env.branch-key }}-${{ env.lockfile-hash }}-
          ${{ runner.os }}-${{ env.cache-name }}-${{ inputs.node_version }}-${{ env.branch-key }}-
    - run: |
        export NODE_OPTIONS="--max_old_space_size=8192"
        yarn build
      if: steps.cache-build.outputs.cache-hit != 'true'
      shell: bash
