name: Cache production build binaries
description: "Cache or restore if necessary"
inputs:
  node_version:
    required: false
    default: v18.x
runs:
  using: "composite"
  steps:
    - run: |
        export NODE_OPTIONS="--max_old_space_size=8192"
        yarn build
      shell: bash
