name: Cache production build binaries
description: "Cache or restore if necessary"
inputs:
  node_version:
    required: false
    default: v18.x
runs:
  using: "composite"
  steps:
    - name: Cache production build
      uses: buildjet/cache@v4
      id: cache-build
      env:
        # WARN: Don't touch this cache key. Currently github.sha refers to the latest commit in main
        # and not the branch that's attempting to merge to main, which causes CI errors when merged
        # to main.
        # TODO: Fix this problem if intending to modify this cache key.
        cache-name: prod-build
        key-1: ${{ inputs.node_version }}-${{ hashFiles('yarn.lock') }}
        key-2: ${{ hashFiles('apps/**/**.[jt]s', 'apps/**/**.[jt]sx', 'packages/**/**.[jt]s', 'packages/**/**.[jt]sx', '!**/node_modules') }}
        key-3: ${{ github.event.pull_request.number || github.ref }}
        key-4: ${{ github.sha }}
      with:
        path: |
          ${{ github.workspace }}/apps/web/.next
          ${{ github.workspace }}/apps/web/public/embed
          **/.turbo/**
          **/dist/**
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.key-1 }}-${{ env.key-2 }}-${{ env.key-3 }}-${{ env.key-4 }}
    - run: |
        export NODE_OPTIONS="--max_old_space_size=8192"
        rm -rf \
          apps/web/app/future/event-types
          apps/web/app/future/settings/admin
          apps/web/app/future/apps/installed
          apps/web/app/future/apps/\[slug\]
          apps/web/app/future/apps/\[slug\]/setup
          apps/web/app/future/apps/categories
          apps/web/app/future/apps/categories/\[category\]
          apps/web/app/future/workflows
          apps/web/app/future/settings/teams
          apps/web/app/future/apps
          apps/web/app/future/bookings
          apps/web/app/future/video
          apps/web/app/future/teams
          apps/web/app/future/getting-started
          apps/web/app/future/[user]\
          apps/web/app/future/auth\
          apps/web/app/future/booking\
          apps/web/app/future/connect-and-join\
          apps/web/app/future/d\
          apps/web/app/future/enterprise\
          apps/web/app/future/insights\
          apps/web/app/future/maintenance\
          apps/web/app/future/more\
          apps/web/app/future/org\
          apps/web/app/future/payment\
          apps/web/app/future/reschedule\
          apps/web/app/future/routing-forms\
          apps/web/app/future/signup\
          apps/web/app/future/team
        yarn build
      if: steps.cache-build.outputs.cache-hit != 'true'
      shell: bash
