name: Cache production build binaries
description: "Cache or restore if necessary"
inputs:
  node_version:
    required: false
    default: v18.x
runs:
  using: "composite"
  steps:
    - name: Clean cached directories to avoid conflicts
      run: |
        rm -rf apps/web/.next apps/web/public/embed
        # Clean turbo and dist directories to ensure clean cache restore
        find . -name ".turbo" -type d -exec rm -rf {} + 2>/dev/null || true
        find . -name "dist" -type d -not -path "*/node_modules/*" -exec rm -rf {} + 2>/dev/null || true
      shell: bash
    - name: Cache production build
      uses: actions/cache@v4
      id: cache-build
      env:
        cache-name: prod-build
        # Use branch name for cache scoping (head_ref for PRs, ref_name for pushes)
        branch-key: ${{ github.head_ref || github.ref_name }}
        # Hash yarn.lock for dependency changes
        lockfile-hash: ${{ hashFiles('yarn.lock') }}
        # Hash source files that affect the web build, excluding generated directories
        # Excludes packages/prisma/{generated,client,zod}/* and packages/kysely/* which are generated by prisma generate
        source-hash: ${{ hashFiles('apps/**/**.[jt]s', 'apps/**/**.[jt]sx', 'apps/**/*.json', 'apps/**/*.css', 'packages/**/**.[jt]s', 'packages/**/**.[jt]sx', 'packages/prisma/schema.prisma', 'packages/prisma/migrations/**/*.sql', '!**/node_modules/**', '!packages/prisma/generated/**', '!packages/prisma/client/**', '!packages/prisma/zod/**', '!packages/kysely/**') }}
      with:
        path: |
          ${{ github.workspace }}/apps/web/.next
          !${{ github.workspace }}/apps/web/.next/node_modules
          ${{ github.workspace }}/apps/web/public/embed
          **/.turbo/**
          **/dist/**
        key: ${{ runner.os }}-${{ env.cache-name }}-${{ inputs.node_version }}-${{ env.branch-key }}-${{ env.lockfile-hash }}-${{ env.source-hash }}
    - run: |
        export NODE_OPTIONS="--max_old_space_size=8192"
        yarn build
      if: steps.cache-build.outputs.cache-hit != 'true'
      shell: bash
