import { Prisma } from "@prisma/client";

export const availabilityUserSelect = Prisma.validator<Prisma.UserSelect>()({
  credentials: true,
  timeZone: true,
  bufferTime: true,
  availability: true,
  id: true,
  startTime: true,
  username: true,
  endTime: true,
  selectedCalendars: true,
  schedules: {
    select: {
      availability: true,
      timeZone: true,
      id: true,
    },
  },
  defaultScheduleId: true,
});

export const baseUserSelect = Prisma.validator<Prisma.UserSelect>()({
  email: true,
  name: true,
  destinationCalendar: true,
  locale: true,
  plan: true,
  avatar: true,
  hideBranding: true,
  theme: true,
  brandColor: true,
  darkBrandColor: true,
  emailVerified: true,
  password: true,
  bio: true,
  weekStart: true,
  createdDate: true,
  trialEndsAt: true,
  completedOnboarding: true,
  timeFormat: true,
  twoFactorSecret: true,
  twoFactorEnabled: true,
  identityProvider: true,
  identityProviderId: true,
  invitedTo: true,
  away: true,
  allowDynamicBooking: true,
  metadata: true,
  verified: true,
  role: true,
  disableImpersonation: true,
  ...availabilityUserSelect,
});

export const userSelect = Prisma.validator<Prisma.UserArgs>()({
  select: {
    email: true,
    name: true,
    allowDynamicBooking: true,
    destinationCalendar: true,
    locale: true,
    plan: true,
    avatar: true,
    hideBranding: true,
    theme: true,
    brandColor: true,
    darkBrandColor: true,
    ...availabilityUserSelect,
  },
});
