# coding: utf-8

"""
    @calcom/api: Public API for Cal.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.memberships_api import MembershipsApi


class TestMembershipsApi(unittest.TestCase):
    """MembershipsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MembershipsApi()

    def tearDown(self) -> None:
        pass

    def test_memberships_get(self) -> None:
        """Test case for memberships_get

        Find all memberships
        """
        pass

    def test_memberships_post(self) -> None:
        """Test case for memberships_post

        Creates a new membership
        """
        pass

    def test_memberships_user_id_team_id_delete(self) -> None:
        """Test case for memberships_user_id_team_id_delete

        Remove an existing membership
        """
        pass

    def test_memberships_user_id_team_id_get(self) -> None:
        """Test case for memberships_user_id_team_id_get

        Find a membership by userID and teamID
        """
        pass

    def test_memberships_user_id_team_id_patch(self) -> None:
        """Test case for memberships_user_id_team_id_patch

        Edit an existing membership
        """
        pass


if __name__ == '__main__':
    unittest.main()
