# coding: utf-8

"""
    @calcom/api: Public API for Cal.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.add_team_request import AddTeamRequest

class TestAddTeamRequest(unittest.TestCase):
    """AddTeamRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddTeamRequest:
        """Test AddTeamRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddTeamRequest`
        """
        model = AddTeamRequest()
        if include_optional:
            return AddTeamRequest(
                name = '',
                slug = ''
            )
        else:
            return AddTeamRequest(
                name = '',
                slug = '',
        )
        """

    def testAddTeamRequest(self):
        """Test AddTeamRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
