# coding: utf-8

"""
    @calcom/api: Public API for Cal.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.edit_attendee_by_id_request import EditAttendeeByIdRequest

class TestEditAttendeeByIdRequest(unittest.TestCase):
    """EditAttendeeByIdRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EditAttendeeByIdRequest:
        """Test EditAttendeeByIdRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EditAttendeeByIdRequest`
        """
        model = EditAttendeeByIdRequest()
        if include_optional:
            return EditAttendeeByIdRequest(
                email = '',
                name = '',
                time_zone = ''
            )
        else:
            return EditAttendeeByIdRequest(
        )
        """

    def testEditAttendeeByIdRequest(self):
        """Test EditAttendeeByIdRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
