# coding: utf-8

"""
    @calcom/api: Public API for Cal.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.selected_calendars_post_request import SelectedCalendarsPostRequest

class TestSelectedCalendarsPostRequest(unittest.TestCase):
    """SelectedCalendarsPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SelectedCalendarsPostRequest:
        """Test SelectedCalendarsPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SelectedCalendarsPostRequest`
        """
        model = SelectedCalendarsPostRequest()
        if include_optional:
            return SelectedCalendarsPostRequest(
                integration = '',
                external_id = ''
            )
        else:
            return SelectedCalendarsPostRequest(
                integration = '',
                external_id = '',
        )
        """

    def testSelectedCalendarsPostRequest(self):
        """Test SelectedCalendarsPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
