# coding: utf-8

"""
    @calcom/api: Public API for Cal.com

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.users_api import UsersApi


class TestUsersApi(unittest.TestCase):
    """UsersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersApi()

    def tearDown(self) -> None:
        pass

    def test_add_user(self) -> None:
        """Test case for add_user

        Creates a new user
        """
        pass

    def test_edit_user_by_id(self) -> None:
        """Test case for edit_user_by_id

        Edit an existing user
        """
        pass

    def test_get_user_by_id(self) -> None:
        """Test case for get_user_by_id

        Find a user, returns your user if regular user.
        """
        pass

    def test_list_users(self) -> None:
        """Test case for list_users

        Find all users.
        """
        pass

    def test_remove_user_by_id(self) -> None:
        """Test case for remove_user_by_id

        Remove an existing user
        """
        pass


if __name__ == '__main__':
    unittest.main()
