docker run -d -p 3000:3000 \
--restart always \
-e NEXTAUTH_URL='http://localhost:3000' \
-e NEXT_PUBLIC_WEBSITE_URL='http://localhost:3000' \
-e NEXT_PUBLIC_CONSOLE_URL='http://localhost:3000' \
-e NEXT_PUBLIC_EMBED_LIB_URL='http://localhost:3000/embed/embed.js' \
-e NEXT_PUBLIC_LICENSE_CONSENT=true \
-e CALCOM_TELEMETRY_DISABLED=1 \
-e DATABASE_URL="postgres://publicuser:mysecretpassword@192.168.1.14:5432/newdb20" \
-e DATABASE_DIRECT_URL="postgres://publicuser:mysecretpassword@192.168.1.14:5432/newdb20" \
-e ALLOWED_HOSTNAMES='"dashboard.alicexue.com","localhost:3000"' \
-e NEXTAUTH_SECRET='LKF3NfrA5NXDFKKzKiFBel7ATnXY3922U9vmuV+IOHM=' \
-e CALENDSO_ENCRYPTION_KEY='Ei+Q9JJOo1+BJvWYsUFW0qLpkgebN/j/Aji9YGUqnLo=' \
-e NEXT_PUBLIC_API_V2_URL=http://localhost:3000/api/v2 \
-e EMAIL_FROM=no-reply@nischay876.serv00.net \
-e EMAIL_SERVER_HOST=mail2.serv00.com \
-e EMAIL_SERVER_PORT=587 \
-e EMAIL_SERVER_USER=no-reply@nischay876.serv00.net \
-e EMAIL_SERVER_PASSWORD='NischaySH123*' \
-e API_KEY_PREFIX='cal_*' \
-e NEXT_PUBLIC_APP_NAME="Hamza" \
-e NEXT_PUBLIC_SUPPORT_MAIL_ADDRESS="help@hamza.com" \
-e NEXT_PUBLIC_COMPANY_NAME="Hamza, Inc." \
-e NEXT_PUBLIC_DISABLE_SIGNUP=true \
-e ORGANIZATIONS_ENABLED=false \
ghcr.io/nischay876/cal.com:latest
