name: Dangerous git Checkout
description: "Git Checkout from PR code so we can run checks from forks"
runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 2
