name: Dangerous git Checkout
description: "Git Checkout from PR code so we can run checks from forks"
runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 2
        sparse-checkout-cone-mode: false
        sparse-checkout: |
          /*
          !/example-apps/
          !**/*.mp4
          !/docs/images/
          !packages/app-store/*/static/*.png
          !packages/app-store/*/static/*.jpg
          !packages/app-store/*/static/*.jpeg
          !packages/app-store/*/static/*.gif
