declare const appStore: {
    alby: () => Promise<typeof import("./alby")>;
    applecalendar: () => Promise<typeof import("./applecalendar")>;
    aroundvideo: () => Promise<typeof import("./around")>;
    caldavcalendar: () => Promise<typeof import("./caldavcalendar")>;
    campsiteconferencing: () => Promise<typeof import("./campsite")>;
    closecom: () => Promise<typeof import("./closecom")>;
    dailyvideo: () => Promise<typeof import("./dailyvideo")>;
    googlecalendar: () => Promise<typeof import("./googlecalendar")>;
    googlevideo: () => Promise<typeof import("./googlevideo")>;
    hubspot: () => Promise<typeof import("./hubspot")>;
    huddle01video: () => Promise<typeof import("./huddle01video")>;
    "ics-feedcalendar": () => Promise<typeof import("./ics-feedcalendar")>;
    jellyconferencing: () => Promise<typeof import("./jelly")>;
    jitsivideo: () => Promise<typeof import("./jitsivideo")>;
    larkcalendar: () => Promise<typeof import("./larkcalendar")>;
    office365calendar: () => Promise<typeof import("./office365calendar")>;
    office365video: () => Promise<typeof import("./office365video")>;
    plausible: () => Promise<typeof import("./plausible")>;
    paypal: () => Promise<typeof import("./paypal")>;
    "pipedrive-crm": () => Promise<typeof import("./pipedrive-crm")>;
    salesforce: () => Promise<typeof import("./salesforce")>;
    zohocrm: () => Promise<typeof import("./zohocrm")>;
    sendgrid: () => Promise<typeof import("./sendgrid")>;
    stripepayment: () => Promise<typeof import("./stripepayment")>;
    tandemvideo: () => Promise<typeof import("./tandemvideo")>;
    vital: () => Promise<typeof import("./vital")>;
    zoomvideo: () => Promise<typeof import("./zoomvideo")>;
    wipemycalother: () => Promise<typeof import("./wipemycalother")>;
    webexvideo: () => Promise<typeof import("./webex")>;
    giphy: () => Promise<typeof import("./giphy")>;
    zapier: () => Promise<typeof import("./zapier")>;
    make: () => Promise<typeof import("./make")>;
    exchange2013calendar: () => Promise<typeof import("./exchange2013calendar")>;
    exchange2016calendar: () => Promise<typeof import("./exchange2016calendar")>;
    exchangecalendar: () => Promise<typeof import("./exchangecalendar")>;
    facetime: () => Promise<typeof import("./facetime")>;
    sylapsvideo: () => Promise<typeof import("./sylapsvideo")>;
    zohocalendar: () => Promise<typeof import("./zohocalendar")>;
    "zoho-bigin": () => Promise<typeof import("./zoho-bigin")>;
    basecamp3: () => Promise<typeof import("./basecamp3")>;
    telegramvideo: () => Promise<typeof import("./telegram")>;
    shimmervideo: () => Promise<typeof import("./shimmervideo")>;
};
declare const exportedAppStore: typeof appStore & {
    ["mock-payment-app"]?: () => Promise<typeof import("./mock-payment-app/index")>;
};
export default exportedAppStore;
//# sourceMappingURL=index.d.ts.map