export const BOOKING_AUDIT_DI_TOKENS = {
  BOOKING_AUDIT_VIEWER_SERVICE: Symbol("BookingAuditViewerService"),
  BOOKING_AUDIT_VIEWER_SERVICE_MODULE: Symbol("BookingAuditViewerServiceModule"),
  BOOKING_AUDIT_PRODUCER_SERVICE: Symbol("BookingAuditProducerService"),
  BOOKING_AUDIT_PRODUCER_SERVICE_MODULE: Symbol("BookingAuditProducerServiceModule"),
  BOOKING_AUDIT_TASK_CONSUMER: Symbol("BookingAuditTaskConsumer"),
  BOOKING_AUDIT_TASK_CONSUMER_MODULE: Symbol("BookingAuditTaskConsumerModule"),
  BOOKING_AUDIT_TASKER: Symbol("BookingAuditTasker"),
  BOOKING_AUDIT_TASKER_MODULE: Symbol("BookingAuditTaskerModule"),
  BOOKING_AUDIT_SYNC_TASKER: Symbol("BookingAuditSyncTasker"),
  BOOKING_AUDIT_SYNC_TASKER_MODULE: Symbol("BookingAuditSyncTaskerModule"),
  BOOKING_AUDIT_TRIGGER_TASKER: Symbol("BookingAuditTriggerTasker"),
  BOOKING_AUDIT_TRIGGER_TASKER_MODULE: Symbol("BookingAuditTriggerTaskerModule"),
  BOOKING_AUDIT_REPOSITORY: Symbol("BookingAuditRepository"),
  BOOKING_AUDIT_REPOSITORY_MODULE: Symbol("BookingAuditRepositoryModule"),
  AUDIT_ACTOR_REPOSITORY: Symbol("AuditActorRepository"),
  AUDIT_ACTOR_REPOSITORY_MODULE: Symbol("AuditActorRepositoryModule"),
  BOOKING_HISTORY_VIEWER_SERVICE: Symbol("BookingHistoryViewerService"),
  BOOKING_HISTORY_VIEWER_SERVICE_MODULE: Symbol("BookingHistoryViewerServiceModule"),
  BOOKING_AUDIT_ACTION_SERVICE_REGISTRY: Symbol("BookingAuditActionServiceRegistry"),
  BOOKING_AUDIT_ACTION_SERVICE_REGISTRY_MODULE: Symbol("BookingAuditActionServiceRegistryModule"),
};
