export const currencyOptions = [
  { label: "United States dollar", value: "USD", symbol: "$" },
  { label: "Australian dollar", value: "AUD", symbol: "$" },
  { label: "Brazilian real 2", value: "BRL", symbol: "R$" },
  { label: "Canadian dollar", value: "CAD", symbol: "$" },
  { label: "Chinese Renmenbi 3", value: "CNY", symbol: "¥" },
  { label: "Czech koruna", value: "CZK", symbol: "Kč" },
  { label: "Danish krone", value: "DKK", symbol: "kr" },
  { label: "Euro", value: "EUR", symbol: "€" },
  { label: "Hong Kong dollar", value: "HKD", symbol: "$" },
  { label: "Hungarian forint 1", value: "HUF", symbol: "Ft" },
  { label: "Israeli new shekel", value: "ILS", symbol: "₪" },
  { label: "Japanese yen 1", value: "JPY", symbol: "¥" },
  { label: "Malaysian ringgit 3", value: "MYR", symbol: "RM" },
  { label: "Mexican peso", value: "MXN", symbol: "$" },
  { label: "New Taiwan dollar 1", value: "TWD", symbol: "$" },
  { label: "New Zealand dollar", value: "NZD", symbol: "$" },
  { label: "Norwegian krone", value: "NOK", symbol: "kr" },
  { label: "Philippine peso", value: "PHP", symbol: "₱" },
  { label: "Polish złoty", value: "PLN", symbol: "zł" },
  { label: "Pound sterling", value: "GBP", symbol: "£" },
  { label: "Russian ruble", value: "RUB", symbol: "₽" },
  { label: "Singapore dollar", value: "SGD", symbol: "$" },
  { label: "Swedish krona", value: "SEK", symbol: "kr" },
  { label: "Swiss franc", value: "CHF", symbol: "Fr" },
  { label: "Thai baht", value: "THB", symbol: "฿" },
];
