export const currencyOptions = [
  { label: "United States Dollar", value: "usd" },
  { label: "Indian Rupee", value: "inr" },
  { label: "Afghan Afghani", value: "afn" },
  { label: "Albanian Lek", value: "all" },
  { label: "Algerian Dinar", value: "dzd" },
  { label: "Angolan Kwanza", value: "aoa" },
  { label: "Argentine Peso", value: "ars" },
  { label: "Armenian Dram", value: "amd" },
  { label: "Aruban Florin", value: "awg" },
  { label: "Australian Dollar", value: "aud" },
  { label: "Azerbaijani Manat", value: "azn" },
  { label: "Bahamian Dollar", value: "bsd" },
  { label: "Bangladeshi Taka", value: "bdt" },
  { label: "Barbadian Dollar", value: "bbd" },
  { label: "Belarusian Ruble", value: "byn" },
  { label: "Belize Dollar", value: "bzd" },
  { label: "Bermudian Dollar", value: "bmd" },
  { label: "Bolivian Boliviano", value: "bob" },
  { label: "Bosnia and Herzegovina Convertible Mark", value: "bam" },
  { label: "Botswana Pula", value: "bwp" },
  { label: "Brazilian Real", value: "brl" },
  { label: "British Pound Sterling", value: "gbp" },
  { label: "Brunei Dollar", value: "bnd" },
  { label: "Bulgarian Lev", value: "bgn" },
  { label: "Burundian Franc", value: "bif" },
  { label: "Cambodian Riel", value: "khr" },
  { label: "Canadian Dollar", value: "cad" },
  { label: "Cape Verdean Escudo", value: "cve" },
  { label: "Cayman Islands Dollar", value: "kyd" },
  { label: "Central African CFA Franc", value: "xaf" },
  { label: "CFP Franc", value: "xpf" },
  { label: "Chilean Peso", value: "clp" },
  { label: "Chinese Yuan", value: "cny" },
  { label: "Colombian Peso", value: "cop" },
  { label: "Comorian Franc", value: "kmf" },
  { label: "Congolese Franc", value: "cdf" },
  { label: "Costa Rican Colón", value: "crc" },
  { label: "Czech Koruna", value: "czk" },
  { label: "Danish Krone", value: "dkk" },
  { label: "Djiboutian Franc", value: "djf" },
  { label: "Dominican Peso", value: "dop" },
  { label: "East Caribbean Dollar", value: "xcd" },
  { label: "Egyptian Pound", value: "egp" },
  { label: "Ethiopian Birr", value: "etb" },
  { label: "Euro", value: "eur" },
  { label: "Falkland Islands Pound", value: "fkp" },
  { label: "Fijian Dollar", value: "fjd" },
  { label: "Gambian Dalasi", value: "gmd" },
  { label: "Georgian Lari", value: "gel" },
  { label: "Gibraltar Pound", value: "gip" },
  { label: "Guatemalan Quetzal", value: "gtq" },
  { label: "Guinean Franc", value: "gnf" },
  { label: "Guyanese Dollar", value: "gyd" },
  { label: "Haitian Gourde", value: "htg" },
  { label: "Honduran Lempira", value: "hnl" },
  { label: "Hong Kong Dollar", value: "hkd" },
  { label: "Hungarian Forint", value: "huf" },
  { label: "Icelandic Króna", value: "isk" },
  { label: "Indonesian Rupiah", value: "idr" },
  { label: "Israeli New Shekel", value: "ils" },
  { label: "Jamaican Dollar", value: "jmd" },
  { label: "Japanese Yen", value: "jpy" },
  { label: "Kazakhstani Tenge", value: "kzt" },
  { label: "Kenyan Shilling", value: "kes" },
  { label: "Kyrgyzstani Som", value: "kgs" },
  { label: "Laotian Kip", value: "lak" },
  { label: "Lebanese Pound", value: "lbp" },
  { label: "Lesotho Loti", value: "lsl" },
  { label: "Liberian Dollar", value: "lrd" },
  { label: "Macanese Pataca", value: "mop" },
  { label: "Macedonian Denar", value: "mkd" },
  { label: "Malagasy Ariary", value: "mga" },
  { label: "Malawian Kwacha", value: "mwk" },
  { label: "Malaysian Ringgit", value: "myr" },
  { label: "Maldivian Rufiyaa", value: "mvr" },
  { label: "Mauritian Rupee", value: "mur" },
  { label: "Mexican Peso", value: "mxn" },
  { label: "Moldovan Leu", value: "mdl" },
  { label: "Mongolian Tögrög", value: "mnt" },
  { label: "Moroccan Dirham", value: "mad" },
  { label: "Mozambican Metical", value: "mzn" },
  { label: "Myanmar Kyat", value: "mmk" },
  { label: "Namibian Dollar", value: "nad" },
  { label: "Nepalese Rupee", value: "npr" },
  { label: "Netherlands Antillean Guilder", value: "ang" },
  { label: "New Taiwan Dollar", value: "twd" },
  { label: "New Zealand Dollar", value: "nzd" },
  { label: "Nicaraguan Córdoba", value: "nio" },
  { label: "Nigerian Naira", value: "ngn" },
  { label: "Norwegian Krone", value: "nok" },
  { label: "Pakistani Rupee", value: "pkr" },
  { label: "Panamanian Balboa", value: "pab" },
  { label: "Papua New Guinean Kina", value: "pgk" },
  { label: "Paraguayan Guaraní", value: "pyg" },
  { label: "Peruvian Sol", value: "pen" },
  { label: "Philippine Peso", value: "php" },
  { label: "Polish Złoty", value: "pln" },
  { label: "Qatari Riyal", value: "qar" },
  { label: "Romanian Leu", value: "ron" },
  { label: "Russian Ruble", value: "rub" },
  { label: "Rwandan Franc", value: "rwf" },
  { label: "Saint Helena Pound", value: "shp" },
  { label: "Samoan Tala", value: "wst" },
  { label: "Saudi Riyal", value: "sar" },
  { label: "Serbian Dinar", value: "rsd" },
  { label: "Seychellois Rupee", value: "scr" },
  { label: "Sierra Leonean Leone", value: "sle" },
  { label: "Singapore Dollar", value: "sgd" },
  { label: "Solomon Islands Dollar", value: "sbd" },
  { label: "Somali Shilling", value: "sos" },
  { label: "South African Rand", value: "zar" },
  { label: "South Korean Won", value: "krw" },
  { label: "Sri Lankan Rupee", value: "lkr" },
  { label: "Surinamese Dollar", value: "srd" },
  { label: "Swazi Lilangeni", value: "szl" },
  { label: "Swedish Krona", value: "sek" },
  { label: "Swiss Franc", value: "chf" },
  { label: "São Tomé and Príncipe Dobra", value: "std" },
  { label: "Tajikistani Somoni", value: "tjs" },
  { label: "Tanzanian Shilling", value: "tzs" },
  { label: "Thai Baht", value: "thb" },
  { label: "Tongan Paʻanga", value: "top" },
  { label: "Trinidad and Tobago Dollar", value: "ttd" },
  { label: "Turkish Lira", value: "try" },
  { label: "Ugandan Shilling", value: "ugx" },
  { label: "Ukrainian Hryvnia", value: "uah" },
  { label: "United Arab Emirates Dirham", value: "aed" },
  { label: "Uruguayan Peso", value: "uyu" },
  { label: "Uzbekistan Som", value: "uzs" },
  { label: "Vanuatu Vatu", value: "vuv" },
  { label: "Vietnamese Đồng", value: "vnd" },
  { label: "West African CFA Franc", value: "xof" },
  { label: "Yemeni Rial", value: "yer" },
  { label: "Zambian Kwacha", value: "zmw" },
];
