name: "Get Dependencies Docker Image"
description: "Get the tag for pre-built Docker image with yarn and playwright dependencies"

outputs:
  image-tag:
    description: "The Docker image tag to use"
    value: ${{ steps.generate-tag.outputs.image-tag }}
  full-image:
    description: "The full Docker image name with tag"
    value: ${{ steps.generate-tag.outputs.full-image }}

runs:
  using: "composite"
  steps:
    - name: Generate image tag
      id: generate-tag
      shell: bash
      run: |
        YARN_LOCK_HASH=$(sha256sum yarn.lock | cut -d' ' -f1 | cut -c1-12)
        PLAYWRIGHT_VERSION=$(node -e "console.log(require('./package.json').devDependencies['@playwright/test'])")
        IMAGE_TAG="yarn-${YARN_LOCK_HASH}-playwright-${PLAYWRIGHT_VERSION}"
        echo "image-tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
        echo "full-image=ghcr.io/calcom/cal.com-deps:${IMAGE_TAG}" >> $GITHUB_OUTPUT
