/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
import process from "node:process";
export const AnalyticsServiceMap =
  process.env.NEXT_PUBLIC_IS_E2E === "1"
    ? {}
    : {
        dub: import("./dub/lib/AnalyticsService"),
      };
