/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
export const apiHandlers = {
  applecalendar: import("./applecalendar/api"),
  googlecalendar: import("./googlecalendar/api"),
  googlevideo: import("./googlevideo/api"),
  stripepayment: import("./stripepayment/api"),
  basic: import("./templates/basic/api"),
  "booking-pages-tag": import("./templates/booking-pages-tag/api"),
  "event-type-app-card": import("./templates/event-type-app-card/api"),
  "event-type-location-video-static": import("./templates/event-type-location-video-static/api"),
  "general-app-settings": import("./templates/general-app-settings/api"),
  zoomvideo: import("./zoomvideo/api"),
};
