/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
export const apiHandlers = {
  applecalendar: import("./applecalendar/api"),
  around: import("./around/api"),
  caldavcalendar: import("./caldavcalendar/api"),
  routing_forms: import("./ee/routing_forms/api"),
  exchange2013calendar: import("./exchange2013calendar/api"),
  exchange2016calendar: import("./exchange2016calendar/api"),
  giphy: import("./giphy/api"),
  googlecalendar: import("./googlecalendar/api"),
  hubspotothercalendar: import("./hubspotothercalendar/api"),
  huddle01video: import("./huddle01video/api"),
  jitsivideo: import("./jitsivideo/api"),
  larkcalendar: import("./larkcalendar/api"),
  metamask: import("./metamask/api"),
  office365calendar: import("./office365calendar/api"),
  office365video: import("./office365video/api"),
  ping: import("./ping/api"),
  riverside: import("./riverside/api"),
  slackmessaging: import("./slackmessaging/api"),
  stripepayment: import("./stripepayment/api"),
  tandemvideo: import("./tandemvideo/api"),
  typeform: import("./typeform/api"),
  vital: import("./vital/api"),
  whereby: import("./whereby/api"),
  wipemycalother: import("./wipemycalother/api"),
  zapier: import("./zapier/api"),
  zoomvideo: import("./zoomvideo/api"),
};
