/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/

// Static imports for dynamic imports
export const AppSettingsComponentsMap = {
  "general-app-settings": Generalappsettings,
  weather_in_your_calendar: Weather_in_your_calendar,
  zapier: Zapier,
};
