/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
import { appDataSchema as AlbyAppDataSchema } from "./alby/zod";
import { appDataSchema as Basecamp3AppDataSchema } from "./basecamp3/zod";
import { appDataSchema as ClosecomAppDataSchema } from "./closecom/zod";
import { appDataSchema as DailyvideoAppDataSchema } from "./dailyvideo/zod";
import { appDataSchema as FathomAppDataSchema } from "./fathom/zod";
import { appDataSchema as FeishucalendarAppDataSchema } from "./feishucalendar/zod";
import { appDataSchema as Ga4AppDataSchema } from "./ga4/zod";
import { appDataSchema as GiphyAppDataSchema } from "./giphy/zod";
import { appDataSchema as GooglecalendarAppDataSchema } from "./googlecalendar/zod";
import { appDataSchema as GooglevideoAppDataSchema } from "./googlevideo/zod";
import { appDataSchema as GtmAppDataSchema } from "./gtm/zod";
import { appDataSchema as HitpayAppDataSchema } from "./hitpay/zod";
import { appDataSchema as HubspotAppDataSchema } from "./hubspot/zod";
import { appDataSchema as InsihtsAppDataSchema } from "./insihts/zod";
import { appDataSchema as IntercomAppDataSchema } from "./intercom/zod";
import { appDataSchema as JellyAppDataSchema } from "./jelly/zod";
import { appDataSchema as JitsivideoAppDataSchema } from "./jitsivideo/zod";
import { appDataSchema as LarkcalendarAppDataSchema } from "./larkcalendar/zod";
import { appDataSchema as MakeAppDataSchema } from "./make/zod";
import { appDataSchema as MatomoAppDataSchema } from "./matomo/zod";
import { appDataSchema as MetapixelAppDataSchema } from "./metapixel/zod";
import { appDataSchema as MockpaymentappAppDataSchema } from "./mock-payment-app/zod";
import { appDataSchema as NextcloudtalkAppDataSchema } from "./nextcloudtalk/zod";
import { appDataSchema as Office365calendarAppDataSchema } from "./office365calendar/zod";
import { appDataSchema as Office365videoAppDataSchema } from "./office365video/zod";
import { appDataSchema as PaypalAppDataSchema } from "./paypal/zod";
import { appDataSchema as PipedrivecrmAppDataSchema } from "./pipedrive-crm/zod";
import { appDataSchema as PlausibleAppDataSchema } from "./plausible/zod";
import { appDataSchema as PosthogAppDataSchema } from "./posthog/zod";
import { appDataSchema as Qr_codeAppDataSchema } from "./qr_code/zod";
import { appDataSchema as RoutingformsAppDataSchema } from "./routing-forms/zod";
import { appDataSchema as SalesforceAppDataSchema } from "./salesforce/zod";
import { appDataSchema as ShimmervideoAppDataSchema } from "./shimmervideo/zod";
import { appDataSchema as StripepaymentAppDataSchema } from "./stripepayment/zod";
import { appDataSchema as TandemvideoAppDataSchema } from "./tandemvideo/zod";
import { appDataSchema as BookingpagestagAppDataSchema } from "./templates/booking-pages-tag/zod";
import { appDataSchema as EventtypeappcardAppDataSchema } from "./templates/event-type-app-card/zod";
import { appDataSchema as TwiplaAppDataSchema } from "./twipla/zod";
import { appDataSchema as UmamiAppDataSchema } from "./umami/zod";
import { appDataSchema as VitalAppDataSchema } from "./vital/zod";
import { appDataSchema as WebexAppDataSchema } from "./webex/zod";
import { appDataSchema as WordpressAppDataSchema } from "./wordpress/zod";
import { appDataSchema as ZapierAppDataSchema } from "./zapier/zod";
import { appDataSchema as ZohobiginAppDataSchema } from "./zoho-bigin/zod";
import { appDataSchema as ZohocalendarAppDataSchema } from "./zohocalendar/zod";
import { appDataSchema as ZohocrmAppDataSchema } from "./zohocrm/zod";
import { appDataSchema as ZoomvideoAppDataSchema } from "./zoomvideo/zod";

// Static imports for dynamic imports
export const appDataSchemas = {
  alby: AlbyAppDataSchema,
  basecamp3: Basecamp3AppDataSchema,
  closecom: ClosecomAppDataSchema,
  dailyvideo: DailyvideoAppDataSchema,
  fathom: FathomAppDataSchema,
  feishucalendar: FeishucalendarAppDataSchema,
  ga4: Ga4AppDataSchema,
  giphy: GiphyAppDataSchema,
  googlecalendar: GooglecalendarAppDataSchema,
  googlevideo: GooglevideoAppDataSchema,
  gtm: GtmAppDataSchema,
  hitpay: HitpayAppDataSchema,
  hubspot: HubspotAppDataSchema,
  insihts: InsihtsAppDataSchema,
  intercom: IntercomAppDataSchema,
  jelly: JellyAppDataSchema,
  jitsivideo: JitsivideoAppDataSchema,
  larkcalendar: LarkcalendarAppDataSchema,
  make: MakeAppDataSchema,
  matomo: MatomoAppDataSchema,
  metapixel: MetapixelAppDataSchema,
  "mock-payment-app": MockpaymentappAppDataSchema,
  nextcloudtalk: NextcloudtalkAppDataSchema,
  office365calendar: Office365calendarAppDataSchema,
  office365video: Office365videoAppDataSchema,
  paypal: PaypalAppDataSchema,
  "pipedrive-crm": PipedrivecrmAppDataSchema,
  plausible: PlausibleAppDataSchema,
  posthog: PosthogAppDataSchema,
  qr_code: Qr_codeAppDataSchema,
  "routing-forms": RoutingformsAppDataSchema,
  salesforce: SalesforceAppDataSchema,
  shimmervideo: ShimmervideoAppDataSchema,
  stripe: StripepaymentAppDataSchema,
  tandemvideo: TandemvideoAppDataSchema,
  "booking-pages-tag": BookingpagestagAppDataSchema,
  "event-type-app-card": EventtypeappcardAppDataSchema,
  twipla: TwiplaAppDataSchema,
  umami: UmamiAppDataSchema,
  vital: VitalAppDataSchema,
  webex: WebexAppDataSchema,
  wordpress: WordpressAppDataSchema,
  zapier: ZapierAppDataSchema,
  "zoho-bigin": ZohobiginAppDataSchema,
  zohocalendar: ZohocalendarAppDataSchema,
  zohocrm: ZohocrmAppDataSchema,
  zoomvideo: ZoomvideoAppDataSchema,
};
