/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/


import Alby from "./alby/components/EventTypeAppCardInterface";
import Basecamp3 from "./basecamp3/components/EventTypeAppCardInterface";
import Closecom from "./closecom/components/EventTypeAppCardInterface";
import Fathom from "./fathom/components/EventTypeAppCardInterface";
import Ga4 from "./ga4/components/EventTypeAppCardInterface";
import Giphy from "./giphy/components/EventTypeAppCardInterface";
import Gtm from "./gtm/components/EventTypeAppCardInterface";
import Hitpay from "./hitpay/components/EventTypeAppCardInterface";
import Hubspot from "./hubspot/components/EventTypeAppCardInterface";
import Insihts from "./insihts/components/EventTypeAppCardInterface";
import Matomo from "./matomo/components/EventTypeAppCardInterface";
import Metapixel from "./metapixel/components/EventTypeAppCardInterface";
import Mockpaymentapp from "./mock-payment-app/components/EventTypeAppCardInterface";
import Paypal from "./paypal/components/EventTypeAppCardInterface";
import Pipedrivecrm from "./pipedrive-crm/components/EventTypeAppCardInterface";
import Plausible from "./plausible/components/EventTypeAppCardInterface";
import Posthog from "./posthog/components/EventTypeAppCardInterface";
import Qr_code from "./qr_code/components/EventTypeAppCardInterface";
import Salesforce from "./salesforce/components/EventTypeAppCardInterface";
import Stripepayment from "./stripepayment/components/EventTypeAppCardInterface";
import Bookingpagestag from "./templates/booking-pages-tag/components/EventTypeAppCardInterface";
import Eventtypeappcard from "./templates/event-type-app-card/components/EventTypeAppCardInterface";
import Twipla from "./twipla/components/EventTypeAppCardInterface";
import Umami from "./umami/components/EventTypeAppCardInterface";
import Zohobigin from "./zoho-bigin/components/EventTypeAppCardInterface";
import Zohocrm from "./zohocrm/components/EventTypeAppCardInterface";

// Static imports for dynamic imports
export const EventTypeAddonMap = {
  alby: Alby,
  basecamp3: Basecamp3,
  closecom: Closecom,
  fathom: Fathom,
  ga4: Ga4,
  giphy: Giphy,
  gtm: Gtm,
  hitpay: Hitpay,
  hubspot: Hubspot,
  insihts: Insihts,
  matomo: Matomo,
  metapixel: Metapixel,
  "mock-payment-app": Mockpaymentapp,
  paypal: Paypal,
  "pipedrive-crm": Pipedrivecrm,
  plausible: Plausible,
  posthog: Posthog,
  qr_code: Qr_code,
  salesforce: Salesforce,
  stripepayment: Stripepayment,
  "booking-pages-tag": Bookingpagestag,
  "event-type-app-card": Eventtypeappcard,
  twipla: Twipla,
  umami: Umami,
  "zoho-bigin": Zohobigin,
  zohocrm: Zohocrm,
};
