/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
import { appKeysSchema as dailyvideo_keys_schema } from "./dailyvideo/zod";
import { appKeysSchema as routing_forms_keys_schema } from "./ee/routing-forms/zod";
import { appKeysSchema as fathom_keys_schema } from "./fathom/zod";
import { appKeysSchema as ga4_keys_schema } from "./ga4/zod";
import { appKeysSchema as giphy_keys_schema } from "./giphy/zod";
import { appKeysSchema as googlecalendar_keys_schema } from "./googlecalendar/zod";
import { appKeysSchema as hubspot_keys_schema } from "./hubspot/zod";
import { appKeysSchema as larkcalendar_keys_schema } from "./larkcalendar/zod";
import { appKeysSchema as office365calendar_keys_schema } from "./office365calendar/zod";
import { appKeysSchema as office365video_keys_schema } from "./office365video/zod";
import { appKeysSchema as plausible_keys_schema } from "./plausible/zod";
import { appKeysSchema as qr_code_keys_schema } from "./qr_code/zod";
import { appKeysSchema as rainbow_keys_schema } from "./rainbow/zod";
import { appKeysSchema as salesforce_keys_schema } from "./salesforce/zod";
import { appKeysSchema as stripepayment_keys_schema } from "./stripepayment/zod";
import { appKeysSchema as tandemvideo_keys_schema } from "./tandemvideo/zod";
import { appKeysSchema as vital_keys_schema } from "./vital/zod";
import { appKeysSchema as wordpress_keys_schema } from "./wordpress/zod";
import { appKeysSchema as zapier_keys_schema } from "./zapier/zod";
import { appKeysSchema as zoomvideo_keys_schema } from "./zoomvideo/zod";

export const appKeysSchemas = {
  dailyvideo: dailyvideo_keys_schema,
  "routing-forms": routing_forms_keys_schema,
  fathom: fathom_keys_schema,
  ga4: ga4_keys_schema,
  giphy: giphy_keys_schema,
  googlecalendar: googlecalendar_keys_schema,
  hubspot: hubspot_keys_schema,
  larkcalendar: larkcalendar_keys_schema,
  office365calendar: office365calendar_keys_schema,
  office365video: office365video_keys_schema,
  plausible: plausible_keys_schema,
  qr_code: qr_code_keys_schema,
  rainbow: rainbow_keys_schema,
  salesforce: salesforce_keys_schema,
  stripe: stripepayment_keys_schema,
  tandemvideo: tandemvideo_keys_schema,
  vital: vital_keys_schema,
  wordpress: wordpress_keys_schema,
  zapier: zapier_keys_schema,
  zoomvideo: zoomvideo_keys_schema,
};
