/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
import ApplecalendarCalendarService from "./applecalendar/lib/CalendarService";
import CaldavcalendarCalendarService from "./caldavcalendar/lib/CalendarService";
import Exchange2013calendarCalendarService from "./exchange2013calendar/lib/CalendarService";
import Exchange2016calendarCalendarService from "./exchange2016calendar/lib/CalendarService";
import ExchangecalendarCalendarService from "./exchangecalendar/lib/CalendarService";
import FeishucalendarCalendarService from "./feishucalendar/lib/CalendarService";
import GooglecalendarCalendarService from "./googlecalendar/lib/CalendarService";
import IcsfeedcalendarCalendarService from "./ics-feedcalendar/lib/CalendarService";
import LarkcalendarCalendarService from "./larkcalendar/lib/CalendarService";
import Office365calendarCalendarService from "./office365calendar/lib/CalendarService";
import ZohocalendarCalendarService from "./zohocalendar/lib/CalendarService";

// Static imports for dynamic imports
export const CalendarServiceMap = {
  applecalendar: ApplecalendarCalendarService,
  caldavcalendar: CaldavcalendarCalendarService,
  exchange2013calendar: Exchange2013calendarCalendarService,
  exchange2016calendar: Exchange2016calendarCalendarService,
  exchangecalendar: ExchangecalendarCalendarService,
  feishucalendar: FeishucalendarCalendarService,
  googlecalendar: GooglecalendarCalendarService,
  "ics-feedcalendar": IcsfeedcalendarCalendarService,
  larkcalendar: LarkcalendarCalendarService,
  office365calendar: Office365calendarCalendarService,
  zohocalendar: ZohocalendarCalendarService,
};
