/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
export declare const CalendarServiceMap: {
    applecalendar?: undefined;
    caldavcalendar?: undefined;
    exchange2013calendar?: undefined;
    exchange2016calendar?: undefined;
    exchangecalendar?: undefined;
    feishucalendar?: undefined;
    googlecalendar?: undefined;
    "ics-feedcalendar"?: undefined;
    larkcalendar?: undefined;
    office365calendar?: undefined;
    zohocalendar?: undefined;
} | {
    applecalendar: Promise<typeof import("./applecalendar/lib/CalendarService")>;
    caldavcalendar: Promise<typeof import("./caldavcalendar/lib/CalendarService")>;
    exchange2013calendar: Promise<typeof import("./exchange2013calendar/lib/CalendarService")>;
    exchange2016calendar: Promise<typeof import("./exchange2016calendar/lib/CalendarService")>;
    exchangecalendar: Promise<typeof import("./exchangecalendar/lib/CalendarService")>;
    feishucalendar: Promise<typeof import("./feishucalendar/lib/CalendarService")>;
    googlecalendar: Promise<typeof import("./googlecalendar/lib/CalendarService")>;
    "ics-feedcalendar": Promise<typeof import("./ics-feedcalendar/lib/CalendarService")>;
    larkcalendar: Promise<typeof import("./larkcalendar/lib/CalendarService")>;
    office365calendar: Promise<typeof import("./office365calendar/lib/CalendarService")>;
    zohocalendar: Promise<typeof import("./zohocalendar/lib/CalendarService")>;
};
