/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
import { VideoApiAdapter as DailyvideoVideoApiAdapter } from "./dailyvideo/lib";
import { VideoApiAdapter as Huddle01videoVideoApiAdapter } from "./huddle01video/lib";
import { VideoApiAdapter as JellyVideoApiAdapter } from "./jelly/lib";
import { VideoApiAdapter as JitsivideoVideoApiAdapter } from "./jitsivideo/lib";
import { VideoApiAdapter as NextcloudtalkVideoApiAdapter } from "./nextcloudtalk/lib";
import { VideoApiAdapter as Office365videoVideoApiAdapter } from "./office365video/lib";
import { VideoApiAdapter as ShimmervideoVideoApiAdapter } from "./shimmervideo/lib";
import { VideoApiAdapter as SylapsvideoVideoApiAdapter } from "./sylapsvideo/lib";
import { VideoApiAdapter as TandemvideoVideoApiAdapter } from "./tandemvideo/lib";
import { VideoApiAdapter as WebexVideoApiAdapter } from "./webex/lib";
import { VideoApiAdapter as ZoomvideoVideoApiAdapter } from "./zoomvideo/lib";

// Static imports for dynamic imports
export const ConferencingVideoAdapterMap = {
  dailyvideo: DailyvideoVideoApiAdapter,
  huddle01video: Huddle01videoVideoApiAdapter,
  jelly: JellyVideoApiAdapter,
  jitsivideo: JitsivideoVideoApiAdapter,
  nextcloudtalk: NextcloudtalkVideoApiAdapter,
  office365video: Office365videoVideoApiAdapter,
  shimmervideo: ShimmervideoVideoApiAdapter,
  sylapsvideo: SylapsvideoVideoApiAdapter,
  tandemvideo: TandemvideoVideoApiAdapter,
  webex: WebexVideoApiAdapter,
  zoomvideo: ZoomvideoVideoApiAdapter,
};
