/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
export const CrmServiceMap = {
  closecom: import("./closecom/dist/lib/CrmService.js"),
  hubspot: import("./hubspot/dist/lib/CrmService.js"),
  "pipedrive-crm": import("./pipedrive-crm/dist/lib/CrmService.js"),
  salesforce: import("./salesforce/dist/lib/CrmService.js"),
  "zoho-bigin": import("./zoho-bigin/lib/CrmService"),
  zohocrm: import("./zohocrm/lib/CrmService"),
};
