const appStore = {
  // example: (): Promise<typeof import("./example")> => import("./example"),
  applecalendar: (): Promise<typeof import("./applecalendar")> => import("./applecalendar"),
  caldavcalendar: (): Promise<typeof import("./caldavcalendar")> => import("./caldavcalendar"),
  closecom: (): Promise<typeof import("./closecom")> => import("./closecom"),
  dailyvideo: (): Promise<typeof import("./dailyvideo")> => import("./dailyvideo"),
  googlecalendar: (): Promise<typeof import("./googlecalendar")> => import("./googlecalendar"),
  googlevideo: (): Promise<typeof import("./googlevideo")> => import("./googlevideo"),
  hubspot: (): Promise<typeof import("./hubspot")> => import("./hubspot"),
  huddle01video: (): Promise<typeof import("./huddle01video")> => import("./huddle01video"),
  jitsivideo: (): Promise<typeof import("./jitsivideo")> => import("./jitsivideo"),
  larkcalendar: (): Promise<typeof import("./larkcalendar")> => import("./larkcalendar"),
  office365calendar: (): Promise<typeof import("./office365calendar")> => import("./office365calendar"),
  office365video: (): Promise<typeof import("./office365video")> => import("./office365video"),
  plausible: (): Promise<typeof import("./plausible")> => import("./plausible"),
  salesforce: (): Promise<typeof import("./salesforce")> => import("./salesforce"),
  zohocrm: (): Promise<typeof import("./zohocrm")> => import("./zohocrm"),
  sendgrid: (): Promise<typeof import("./sendgrid")> => import("./sendgrid"),
  stripepayment: (): Promise<typeof import("./stripepayment")> => import("./stripepayment"),
  tandemvideo: (): Promise<typeof import("./tandemvideo")> => import("./tandemvideo"),
  vital: (): Promise<typeof import("./vital")> => import("./vital"),
  zoomvideo: (): Promise<typeof import("./zoomvideo")> => import("./zoomvideo"),
  wipemycalother: (): Promise<typeof import("./wipemycalother")> => import("./wipemycalother"),
  giphy: (): Promise<typeof import("./giphy")> => import("./giphy"),
  zapier: (): Promise<typeof import("./zapier")> => import("./zapier"),
  exchange2013calendar: (): Promise<typeof import("./exchange2013calendar")> =>
    import("./exchange2013calendar"),
  exchange2016calendar: (): Promise<typeof import("./exchange2016calendar")> =>
    import("./exchange2016calendar"),
  exchangecalendar: (): Promise<typeof import("./exchangecalendar")> => import("./exchangecalendar"),
  facetime: (): Promise<typeof import("./facetime")> => import("./facetime"),
  sylapsvideo: (): Promise<typeof import("./sylapsvideo")> => import("./sylapsvideo"),
};

export default appStore;
