/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
export const LocationMetadataMap = {
  dailyvideo: import("./dailyvideo/_metadata"),
  googlevideo: import("./googlevideo/_metadata"),
  huddle01video: import("./huddle01video/_metadata"),
  jitsivideo: import("./jitsivideo/_metadata"),
  office365video: import("./office365video/_metadata"),
  tandemvideo: import("./tandemvideo/_metadata"),
  zoomvideo: import("./zoomvideo/_metadata"),
};
