/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
export const PaymentServiceMap = {
  alby: import("./alby/lib/PaymentService").catch(() => ({}) as any),
  btcpayserver: import("./btcpayserver/lib/PaymentService").catch(() => ({}) as any),
  hitpay: import("./hitpay/lib/PaymentService").catch(() => ({}) as any),
  "mock-payment-app": import("./mock-payment-app/lib/PaymentService").catch(() => ({}) as any),
  paypal: import("./paypal/lib/PaymentService").catch(() => ({}) as any),
  stripepayment: import("./stripepayment/lib/PaymentService").catch(() => ({}) as any),
};
