/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
import type { Prisma } from "@calcom/prisma/client";
import type { IAbstractPaymentService } from "@calcom/types/PaymentService";

type PaymentServiceConstructor = new (credentials: { key: Prisma.JsonValue }) => IAbstractPaymentService;
const importPaymentService = (path: string) =>
  import(path) as Promise<{ PaymentService: PaymentServiceConstructor }>;
export const PaymentServiceMap: Record<string, Promise<{ PaymentService: PaymentServiceConstructor }>> = {
  alby: importPaymentService("./alby/lib/PaymentService"),
  btcpayserver: importPaymentService("./btcpayserver/lib/PaymentService"),
  hitpay: importPaymentService("./hitpay/lib/PaymentService"),
  "mock-payment-app": importPaymentService("./mock-payment-app/lib/PaymentService"),
  paypal: importPaymentService("./paypal/lib/PaymentService"),
  stripepayment: importPaymentService("./stripepayment/lib/PaymentService"),
};
