/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
import * as Alby from "./alby/index";
import * as Hitpay from "./hitpay/index";
import * as Mockpaymentapp from "./mock-payment-app/index";
import * as Paypal from "./paypal/index";
import * as Stripepayment from "./stripepayment/index";

// Static imports for dynamic imports
export const PaymentAppMap = {
  alby: Alby,
  hitpay: Hitpay,
  "mock-payment-app": Mockpaymentapp,
  paypal: Paypal,
  stripepayment: Stripepayment,
};
