/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
import AlbyPaymentService from "./alby/lib/PaymentService";
import HitpayPaymentService from "./hitpay/lib/PaymentService";
import MockpaymentappPaymentService from "./mock-payment-app/lib/PaymentService";
import PaypalPaymentService from "./paypal/lib/PaymentService";
import StripepaymentPaymentService from "./stripepayment/lib/PaymentService";

// Static imports for dynamic imports
export const PaymentAppMap = {
  alby: AlbyPaymentService,
  hitpay: HitpayPaymentService,
  "mock-payment-app": MockpaymentappPaymentService,
  paypal: PaypalPaymentService,
  stripepayment: StripepaymentPaymentService,
};
