/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
export const PaymentAppMap = {
  alby: import("./alby/index"),
  hitpay: import("./hitpay/index"),
  "mock-payment-app": import("./mock-payment-app/index"),
  paypal: import("./paypal/index"),
  stripepayment: import("./stripepayment/index"),
};
