/**
    This file is autogenerated using the command `yarn app-store:build --watch`.
    Don't modify this file manually.
**/
export const VideoApiAdapterMap = process.env.NEXT_PUBLIC_IS_E2E
  ? {}
  : {
      dailyvideo: import("./dailyvideo/dist/lib/VideoApiAdapter.js"),
      huddle01video: import("./huddle01video/dist/lib/VideoApiAdapter.js"),
      jelly: import("./jelly/dist/lib/VideoApiAdapter.js"),
      jitsivideo: import("./jitsivideo/dist/lib/VideoApiAdapter.js"),
      nextcloudtalk: import("./nextcloudtalk/dist/lib/VideoApiAdapter.js"),
      office365video: import("./office365video/dist/lib/VideoApiAdapter.js"),
      shimmervideo: import("./shimmervideo/dist/lib/VideoApiAdapter.js"),
      sylapsvideo: import("./sylapsvideo/lib/VideoApiAdapter"),
      tandemvideo: import("./tandemvideo/lib/VideoApiAdapter"),
      webex: import("./webex/lib/VideoApiAdapter"),
      zoomvideo: import("./zoomvideo/lib/VideoApiAdapter"),
    };
