import { resolve } from "path";
import { defineConfig } from "vite";
import dts from "vite-plugin-dts";

export default defineConfig({
  plugins: [
    dts({
      exclude: [
        "**/*.test.*",
        "**/*.spec.*",
        "node_modules/**",
        "**/apps/**",
        "**/*.generated.*",
        "**/lib/**",
        "**/api/**",
        "**/components/**",
      ],
      include: [
        "./index.ts",
        "./calendar.ts",
        "./payment.ts",
        "./video.ts",
        "./crm.ts",
        "./analytics.ts",
        "./browser.ts",
        "./metadata.ts",
        "./utils.ts",
        "./_utils.ts",
        "./appStoreMetaData.ts",
      ],
      skipDiagnostics: true,
      rollupTypes: true,
    }),
  ],
  build: {
    target: "node18",
    lib: {
      entry: {
        index: resolve(__dirname, "./index.ts"),
        calendar: resolve(__dirname, "./calendar.ts"),
        payment: resolve(__dirname, "./payment.ts"),
        video: resolve(__dirname, "./video.ts"),
        crm: resolve(__dirname, "./crm.ts"),
        analytics: resolve(__dirname, "./analytics.ts"),
        browser: resolve(__dirname, "./browser.ts"),
        metadata: resolve(__dirname, "./metadata.ts"),
        utils: resolve(__dirname, "./utils.ts"),
        _utils: resolve(__dirname, "./_utils.ts"),
        appStoreMetaData: resolve(__dirname, "./appStoreMetaData.ts"),
      },
      formats: ["cjs", "es"],
      fileName: (format, entryName) => {
        const extension = format === "cjs" ? "cjs" : "js";
        return `${entryName}.${extension}`;
      },
    },
    rollupOptions: {
      external: [
        "crypto",
        "fs",
        "path",
        "stream",
        "util",
        "os",
        "events",
        "buffer",
        "url",
        "querystring",
        "http",
        "https",
        "net",
        "dns",
        "zlib",
        "child_process",
        "timers",
        "perf_hooks",
        "tls",
        "http2",
        "node:crypto",
        "node:fs",
        "node:path",
        "node:stream",
        "node:util",
        "node:os",
        "node:events",
        "node:buffer",
        "node:url",
        "node:querystring",
        "node:http",
        "node:https",
        "node:net",
        "node:dns",
        "node:zlib",
        "node:child_process",
        "node:timers",
        "node:perf_hooks",
        "node:tls",
        "node:http2",

        "react",
        "react-dom",
        "next",
        "next/router",
        "next/navigation",
        "next/dynamic",

        "@calcom/lib",
        "@calcom/types",
        "@calcom/prisma",
        "@calcom/features",
        "@calcom/ui",
        "@calcom/trpc",
        "@calcom/dailyvideo",
        "@calcom/dayjs",
        "@calcom/office365video",
        "@calcom/zoomvideo",
        "@calcom/emails",

        /^@calcom\/app-store\/.*/,

        "@prisma/client",
        "lodash",
        "qs-stringify",
        "react-i18next",
        "stripe",
        "axios",
        "zod",
        "jose",
        "jsonwebtoken",
        "nodemailer",
        "sharp",
        "jsdom",
        "@sentry/react",
        "@sentry/core",
        "@hubspot/api-client",
        "date-fns",
        "ics",
        "xml2js",
        "csv-parse",
        "jws",
        "@jimp/core",
        "@jsforce/jsforce-node",
        "tough-cookie",
        "agent-base",
        "fetch",
        "iconv-lite",
        "escape-string-regexp",
      ],
    },
  },
});
