import { Prisma } from "@prisma/client";
import type short from "short-uuid";
import type { CalendarEvent } from "@calcom/types/Calendar";
import type { TgetBookingDataSchema } from "../getBookingDataSchema";
import type { EventTypeId, AwaitedBookingData, NewBookingEventType, IsConfirmedByDefault, PaymentAppData, OriginalRescheduledBooking, AwaitedLoadUsers } from "./types";
type ReqBodyWithEnd = TgetBookingDataSchema & {
    end: string;
};
type CreateBookingParams = {
    originalRescheduledBooking: OriginalRescheduledBooking;
    evt: CalendarEvent;
    eventType: NewBookingEventType;
    eventTypeId: EventTypeId;
    eventTypeSlug: AwaitedBookingData["eventTypeSlug"];
    reqBodyUser: ReqBodyWithEnd["user"];
    reqBodyMetadata: ReqBodyWithEnd["metadata"];
    reqBodyRecurringEventId: ReqBodyWithEnd["recurringEventId"];
    uid: short.SUUID;
    responses: ReqBodyWithEnd["responses"] | null;
    isConfirmedByDefault: IsConfirmedByDefault;
    smsReminderNumber: AwaitedBookingData["smsReminderNumber"];
    organizerUser: AwaitedLoadUsers[number] & {
        isFixed?: boolean;
        metadata?: Prisma.JsonValue;
    };
    rescheduleReason: AwaitedBookingData["rescheduleReason"];
    bookerEmail: AwaitedBookingData["email"];
    paymentAppData: PaymentAppData;
    changedOrganizer: boolean;
};
export declare function createBooking({ originalRescheduledBooking, evt, eventTypeId, eventTypeSlug, reqBodyUser, reqBodyMetadata, reqBodyRecurringEventId, uid, responses, isConfirmedByDefault, smsReminderNumber, organizerUser, rescheduleReason, eventType, bookerEmail, paymentAppData, changedOrganizer, }: CreateBookingParams): Promise<{
    user: {
        name: string | null;
        email: string;
        username: string | null;
        timeZone: string;
    } | null;
    payment: {
        data: Prisma.JsonValue;
        id: number;
        uid: string;
        externalId: string;
        success: boolean;
        currency: string;
        bookingId: number;
        appId: string | null;
        amount: number;
        fee: number;
        refunded: boolean;
        paymentOption: import(".prisma/client").$Enums.PaymentOption | null;
    }[];
    references: {
        type: string;
        id: number;
        uid: string;
        credentialId: number | null;
        bookingId: number | null;
        meetingId: string | null;
        thirdPartyRecurringEventId: string | null;
        meetingPassword: string | null;
        meetingUrl: string | null;
        externalCalendarId: string | null;
        deleted: boolean | null;
    }[];
    attendees: {
        name: string;
        email: string;
        id: number;
        locale: string | null;
        timeZone: string;
        bookingId: number | null;
        noShow: boolean | null;
    }[];
} & {
    status: import(".prisma/client").$Enums.BookingStatus;
    id: number;
    description: string | null;
    startTime: Date;
    endTime: Date;
    metadata: Prisma.JsonValue;
    uid: string;
    idempotencyKey: string | null;
    userId: number | null;
    userPrimaryEmail: string | null;
    eventTypeId: number | null;
    title: string;
    customInputs: Prisma.JsonValue;
    responses: Prisma.JsonValue;
    location: string | null;
    createdAt: Date;
    updatedAt: Date | null;
    paid: boolean;
    destinationCalendarId: number | null;
    cancellationReason: string | null;
    rejectionReason: string | null;
    dynamicEventSlugRef: string | null;
    dynamicGroupSlugRef: string | null;
    rescheduled: boolean | null;
    fromReschedule: string | null;
    recurringEventId: string | null;
    smsReminderNumber: string | null;
    scheduledJobs: string[];
    isRecorded: boolean;
    iCalUID: string | null;
    iCalSequence: number;
    rating: number | null;
    ratingFeedback: string | null;
    noShowHost: boolean | null;
    cancelledBy: string | null;
    rescheduledBy: string | null;
}>;
export type Booking = Prisma.PromiseReturnType<typeof createBooking>;
export {};
//# sourceMappingURL=createBooking.d.ts.map