server_type = "cx23"
os_type     = "ubuntu-22.04"
location    = "nbg1"
ssh_public_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICPNsRzTUEvRJoJ2+TKVWaeBfGCwZSu2oHsyM5yGZqKu mail@leonliang.lu"
hcloud_token = ""
