import type { Attendee, Booking, BookingReference, Credential, DestinationCalendar, EventType, User } from "@prisma/client";
export declare const bookingsProcedure: import("@trpc/server/unstable-core-do-not-import").ProcedureBuilder<import("../../../createContext").InnerContext, object, {
    user: {
        avatar: string;
        organization: {
            id: number | null;
            isOrgAdmin: boolean;
            metadata: {
                requestedSlug?: string | null | undefined;
                paymentId?: string | undefined;
                subscriptionId?: string | null | undefined;
                subscriptionItemId?: string | null | undefined;
                orgSeats?: number | null | undefined;
                orgPricePerSeat?: number | null | undefined;
                migratedToOrgFrom?: {
                    teamSlug?: string | null | undefined;
                    lastMigrationTime?: string | undefined;
                    reverted?: boolean | undefined;
                    lastRevertTime?: string | undefined;
                } | undefined;
                billingPeriod?: import("@calcom/prisma/zod-utils").BillingPeriod | undefined;
            } | null;
            requestedSlug: string | null;
            organizationSettings?: {
                lockEventTypeCreationForUsers: boolean;
            } | null | undefined;
            name?: string | undefined;
            slug?: string | null | undefined;
            logoUrl?: string | null | undefined;
            calVideoLogo?: string | null | undefined;
            isPrivate?: boolean | undefined;
            bannerUrl?: string | null | undefined;
            isPlatform?: boolean | undefined;
            members?: {
                id: number;
                userId: number;
                teamId: number;
                role: import(".prisma/client").$Enums.MembershipRole;
                disableImpersonation: boolean;
                accepted: boolean;
            }[] | undefined;
        };
        organizationId: number | null;
        id: number;
        email: string;
        username: string | null;
        locale: string;
        defaultBookerLayouts: {
            enabledLayouts: import("@calcom/prisma/zod-utils").BookerLayouts[];
            defaultLayout: import("@calcom/prisma/zod-utils").BookerLayouts;
        } | null;
        destinationCalendar: {
            id: number;
            userId: number | null;
            eventTypeId: number | null;
            credentialId: number | null;
            integration: string;
            externalId: string;
            primaryEmail: string | null;
        } | null;
        name: string | null;
        startTime: number;
        endTime: number;
        metadata: import(".prisma/client").Prisma.JsonValue;
        timeZone: string;
        bio: string | null;
        hideBranding: boolean;
        theme: string | null;
        brandColor: string | null;
        darkBrandColor: string | null;
        timeFormat: number | null;
        weekStart: string;
        selectedCalendars: {
            integration: string;
            externalId: string;
        }[];
        emailVerified: Date | null;
        avatarUrl: string | null;
        bufferTime: number;
        appTheme: string | null;
        createdDate: Date;
        trialEndsAt: Date | null;
        defaultScheduleId: number | null;
        completedOnboarding: boolean;
        twoFactorEnabled: boolean;
        identityProvider: import(".prisma/client").$Enums.IdentityProvider;
        identityProviderId: string | null;
        allowDynamicBooking: boolean | null;
        allowSEOIndexing: boolean | null;
        receiveMonthlyDigestEmail: boolean | null;
        role: import(".prisma/client").$Enums.UserPermissionRole;
        disableImpersonation: boolean;
        movedToProfileId: number | null;
        profile: import("@calcom/types/UserProfile").UserAsPersonalProfile;
    } | {
        avatar: string;
        organization: {
            id: number | null;
            isOrgAdmin: boolean;
            metadata: {
                requestedSlug?: string | null | undefined;
                paymentId?: string | undefined;
                subscriptionId?: string | null | undefined;
                subscriptionItemId?: string | null | undefined;
                orgSeats?: number | null | undefined;
                orgPricePerSeat?: number | null | undefined;
                migratedToOrgFrom?: {
                    teamSlug?: string | null | undefined;
                    lastMigrationTime?: string | undefined;
                    reverted?: boolean | undefined;
                    lastRevertTime?: string | undefined;
                } | undefined;
                billingPeriod?: import("@calcom/prisma/zod-utils").BillingPeriod | undefined;
            } | null;
            requestedSlug: string | null;
            organizationSettings?: {
                lockEventTypeCreationForUsers: boolean;
            } | null | undefined;
            name?: string | undefined;
            slug?: string | null | undefined;
            logoUrl?: string | null | undefined;
            calVideoLogo?: string | null | undefined;
            isPrivate?: boolean | undefined;
            bannerUrl?: string | null | undefined;
            isPlatform?: boolean | undefined;
            members?: {
                id: number;
                userId: number;
                teamId: number;
                role: import(".prisma/client").$Enums.MembershipRole;
                disableImpersonation: boolean;
                accepted: boolean;
            }[] | undefined;
        };
        organizationId: number | null;
        id: number;
        email: string;
        username: string | null;
        locale: string;
        defaultBookerLayouts: {
            enabledLayouts: import("@calcom/prisma/zod-utils").BookerLayouts[];
            defaultLayout: import("@calcom/prisma/zod-utils").BookerLayouts;
        } | null;
        destinationCalendar: {
            id: number;
            userId: number | null;
            eventTypeId: number | null;
            credentialId: number | null;
            integration: string;
            externalId: string;
            primaryEmail: string | null;
        } | null;
        name: string | null;
        startTime: number;
        endTime: number;
        metadata: import(".prisma/client").Prisma.JsonValue;
        timeZone: string;
        bio: string | null;
        hideBranding: boolean;
        theme: string | null;
        brandColor: string | null;
        darkBrandColor: string | null;
        timeFormat: number | null;
        weekStart: string;
        selectedCalendars: {
            integration: string;
            externalId: string;
        }[];
        emailVerified: Date | null;
        avatarUrl: string | null;
        bufferTime: number;
        appTheme: string | null;
        createdDate: Date;
        trialEndsAt: Date | null;
        defaultScheduleId: number | null;
        completedOnboarding: boolean;
        twoFactorEnabled: boolean;
        identityProvider: import(".prisma/client").$Enums.IdentityProvider;
        identityProviderId: string | null;
        allowDynamicBooking: boolean | null;
        allowSEOIndexing: boolean | null;
        receiveMonthlyDigestEmail: boolean | null;
        role: import(".prisma/client").$Enums.UserPermissionRole;
        disableImpersonation: boolean;
        movedToProfileId: number | null;
        profile: {
            name: string | null;
            avatarUrl: string | null;
            startTime: number;
            endTime: number;
            bufferTime: number;
            username: string | null;
            upId: string;
            id: null;
            organizationId: null;
            organization: null;
        } | {
            name: string | null;
            avatarUrl: string | null;
            startTime: number;
            endTime: number;
            bufferTime: number;
            user: {
                name: string | null;
                id: number;
                startTime: number;
                endTime: number;
                email: string;
                locale: string | null;
                username: string | null;
                avatarUrl: string | null;
                bufferTime: number;
                defaultScheduleId: number | null;
                isPlatformManaged: boolean;
            };
            organization: {
                organizationSettings: {
                    lockEventTypeCreationForUsers: boolean;
                } | null;
                name: string;
                id: number;
                metadata: import(".prisma/client").Prisma.JsonValue;
                slug: string | null;
                logoUrl: string | null;
                calVideoLogo: string | null;
                isPrivate: boolean;
                bannerUrl: string | null;
                isPlatform: boolean;
                members: {
                    id: number;
                    userId: number;
                    teamId: number;
                    role: import(".prisma/client").$Enums.MembershipRole;
                    disableImpersonation: boolean;
                    accepted: boolean;
                }[];
            } & Omit<Pick<{
                id: number;
                name: string;
                slug: string | null;
                logoUrl: string | null;
                calVideoLogo: string | null;
                appLogo: string | null;
                appIconLogo: string | null;
                bio: string | null;
                hideBranding: boolean;
                isPrivate: boolean;
                hideBookATeamMember: boolean;
                createdAt: Date;
                metadata: import(".prisma/client").Prisma.JsonValue;
                theme: string | null;
                brandColor: string | null;
                darkBrandColor: string | null;
                bannerUrl: string | null;
                parentId: number | null;
                timeFormat: number | null;
                timeZone: string;
                weekStart: string;
                isOrganization: boolean;
                pendingPayment: boolean;
                isPlatform: boolean;
                createdByOAuthClientId: string | null;
                smsLockState: import(".prisma/client").$Enums.SMSLockState;
                smsLockReviewedByAdmin: boolean;
            }, "name" | "id" | "metadata" | "slug" | "logoUrl" | "calVideoLogo" | "bannerUrl" | "isPlatform">, "metadata"> & {
                requestedSlug: string | null;
                metadata: {
                    requestedSlug: string | null;
                    paymentId?: string | undefined;
                    subscriptionId?: string | null | undefined;
                    subscriptionItemId?: string | null | undefined;
                    orgSeats?: number | null | undefined;
                    orgPricePerSeat?: number | null | undefined;
                    migratedToOrgFrom?: {
                        teamSlug?: string | null | undefined;
                        lastMigrationTime?: string | undefined;
                        reverted?: boolean | undefined;
                        lastRevertTime?: string | undefined;
                    } | undefined;
                    billingPeriod?: import("@calcom/prisma/zod-utils").BillingPeriod | undefined;
                };
            };
            movedFromUser: {
                id: number;
            } | null;
            id: number;
            uid: string;
            userId: number;
            createdAt: Date & string;
            updatedAt: Date & string;
            organizationId: number;
            username: string;
            upId: string;
        };
    };
    booking: {
        eventType: {
            length: number;
            id: number;
            userId: number | null;
            title: string;
            description: string | null;
            metadata: import(".prisma/client").Prisma.JsonValue;
            timeZone: string | null;
            slug: string;
            position: number;
            locations: import(".prisma/client").Prisma.JsonValue;
            offsetStart: number;
            hidden: boolean;
            profileId: number | null;
            teamId: number | null;
            eventName: string | null;
            parentId: number | null;
            bookingFields: import(".prisma/client").Prisma.JsonValue;
            periodType: import(".prisma/client").$Enums.PeriodType;
            periodStartDate: Date | null;
            periodEndDate: Date | null;
            periodDays: number | null;
            periodCountCalendarDays: boolean | null;
            lockTimeZoneToggleOnBookingPage: boolean;
            requiresConfirmation: boolean;
            requiresConfirmationWillBlockSlot: boolean;
            requiresBookerEmailVerification: boolean;
            recurringEvent: import(".prisma/client").Prisma.JsonValue;
            disableGuests: boolean;
            hideCalendarNotes: boolean;
            minimumBookingNotice: number;
            beforeEventBuffer: number;
            afterEventBuffer: number;
            seatsPerTimeSlot: number | null;
            onlyShowFirstAvailableSlot: boolean;
            seatsShowAttendees: boolean | null;
            seatsShowAvailabilityCount: boolean | null;
            schedulingType: import(".prisma/client").$Enums.SchedulingType | null;
            scheduleId: number | null;
            price: number;
            currency: string;
            slotInterval: number | null;
            successRedirectUrl: string | null;
            forwardParamsSuccessRedirect: boolean | null;
            bookingLimits: import(".prisma/client").Prisma.JsonValue;
            durationLimits: import(".prisma/client").Prisma.JsonValue;
            isInstantEvent: boolean;
            instantMeetingExpiryTimeOffsetInSeconds: number;
            instantMeetingScheduleId: number | null;
            assignAllTeamMembers: boolean;
            useEventTypeDestinationCalendarEmail: boolean;
            isRRWeightsEnabled: boolean;
            eventTypeColor: import(".prisma/client").Prisma.JsonValue;
            rescheduleWithSameRoundRobinHost: boolean;
            secondaryEmailId: number | null;
        } | null;
        destinationCalendar: {
            id: number;
            userId: number | null;
            eventTypeId: number | null;
            credentialId: number | null;
            integration: string;
            externalId: string;
            primaryEmail: string | null;
        } | null;
        user: ({
            destinationCalendar: {
                id: number;
                userId: number | null;
                eventTypeId: number | null;
                credentialId: number | null;
                integration: string;
                externalId: string;
                primaryEmail: string | null;
            } | null;
            credentials: {
                type: string;
                id: number;
                userId: number | null;
                teamId: number | null;
                subscriptionId: string | null;
                billingCycleStart: number | null;
                key: import(".prisma/client").Prisma.JsonValue;
                appId: string | null;
                paymentStatus: string | null;
                invalid: boolean | null;
            }[];
        } & {
            name: string | null;
            id: number;
            startTime: number;
            endTime: number;
            metadata: import(".prisma/client").Prisma.JsonValue;
            email: string;
            timeZone: string;
            locale: string | null;
            bio: string | null;
            hideBranding: boolean;
            theme: string | null;
            brandColor: string | null;
            darkBrandColor: string | null;
            timeFormat: number | null;
            weekStart: string;
            smsLockState: import(".prisma/client").$Enums.SMSLockState;
            smsLockReviewedByAdmin: boolean;
            organizationId: number | null;
            username: string | null;
            emailVerified: Date | null;
            avatarUrl: string | null;
            bufferTime: number;
            appTheme: string | null;
            createdDate: Date;
            trialEndsAt: Date | null;
            defaultScheduleId: number | null;
            completedOnboarding: boolean;
            twoFactorSecret: string | null;
            twoFactorEnabled: boolean;
            backupCodes: string | null;
            identityProvider: import(".prisma/client").$Enums.IdentityProvider;
            identityProviderId: string | null;
            invitedTo: number | null;
            allowDynamicBooking: boolean | null;
            allowSEOIndexing: boolean | null;
            receiveMonthlyDigestEmail: boolean | null;
            verified: boolean | null;
            role: import(".prisma/client").$Enums.UserPermissionRole;
            disableImpersonation: boolean;
            locked: boolean;
            movedToProfileId: number | null;
            isPlatformManaged: boolean;
        }) | null;
        references: {
            type: string;
            id: number;
            uid: string;
            bookingId: number | null;
            deleted: boolean | null;
            credentialId: number | null;
            thirdPartyRecurringEventId: string | null;
            meetingId: string | null;
            meetingPassword: string | null;
            meetingUrl: string | null;
            externalCalendarId: string | null;
        }[];
        attendees: {
            name: string;
            id: number;
            email: string;
            timeZone: string;
            locale: string | null;
            noShow: boolean | null;
            bookingId: number | null;
        }[];
    } & {
        status: import(".prisma/client").$Enums.BookingStatus;
        id: number;
        uid: string;
        idempotencyKey: string | null;
        userId: number | null;
        userPrimaryEmail: string | null;
        eventTypeId: number | null;
        title: string;
        description: string | null;
        customInputs: import(".prisma/client").Prisma.JsonValue;
        responses: import(".prisma/client").Prisma.JsonValue;
        startTime: Date;
        endTime: Date;
        location: string | null;
        createdAt: Date;
        updatedAt: Date | null;
        paid: boolean;
        destinationCalendarId: number | null;
        cancellationReason: string | null;
        rejectionReason: string | null;
        dynamicEventSlugRef: string | null;
        dynamicGroupSlugRef: string | null;
        rescheduled: boolean | null;
        fromReschedule: string | null;
        recurringEventId: string | null;
        smsReminderNumber: string | null;
        scheduledJobs: string[];
        metadata: import(".prisma/client").Prisma.JsonValue;
        isRecorded: boolean;
        iCalUID: string | null;
        iCalSequence: number;
        rating: number | null;
        ratingFeedback: string | null;
        noShowHost: boolean | null;
        cancelledBy: string | null;
        rescheduledBy: string | null;
    };
    session: {
        upId: string;
        hasValidLicense: boolean;
        profileId?: number | null | undefined;
        user: import("next-auth").User;
        expires: string;
    };
}, {
    bookingId: number;
}, {
    bookingId: number;
}, typeof import("@trpc/server/unstable-core-do-not-import").unsetMarker, typeof import("@trpc/server/unstable-core-do-not-import").unsetMarker>;
export type BookingsProcedureContext = {
    booking: Booking & {
        eventType: EventType | null;
        destinationCalendar: DestinationCalendar | null;
        user: (User & {
            destinationCalendar: DestinationCalendar | null;
            credentials: Credential[];
        }) | null;
        references: BookingReference[];
        attendees: Attendee[];
    };
};
