export const defaultProfile = {
  name: "",
  email: "",
  username: "",
  role: "",
  calendar: {
    calcom_event_name: "",
    calcom_event_id: "",
    calcom_event_url: "",
    calcom_event_length: "",
    calcom_api_key: "",
    calcom_user_id: "",
  },
  company: "",
  avatar_url: "",
  call_charges: 50,
  bio: "",
  links: [],
  facts: [],
  advice_on: [],
  projects: [],
  experience: [],
  publications: [],
  appearances: [],
  books: [],
  podcast: {},
};
