name: Generate cache-api-v1-build key
description: "Generate the cache key for API v1 production build caching"
outputs:
  key:
    description: "The generated cache key"
    value: ${{ steps.generate-key.outputs.key }}
runs:
  using: "composite"
  steps:
    - name: Generate cache key
      id: generate-key
      shell: bash
      env:
        CACHE_NAME: api-v1-build
        LOCKFILE_HASH: ${{ hashFiles('yarn.lock') }}
        SOURCE_HASH: ${{ hashFiles('apps/api/v1/**.[jt]s', 'apps/api/v1/**.[jt]sx', '!**/node_modules') }}
      run: |
        echo "key=${CACHE_NAME}-${LOCKFILE_HASH}-${SOURCE_HASH}" >> $GITHUB_OUTPUT
