/* v8 ignore start */
import type { TableDefinition } from "../types";
import { timestamps } from "./_helpers";

export const organizationOnboardingTable: TableDefinition = {
  modelName: "OrganizationOnboarding",
  displayName: "Org Onboarding",
  displayNamePlural: "Org Onboardings",
  description: "Organization onboarding records and status",
  slug: "org-onboardings",
  category: "core",
  defaultSort: "createdAt",
  defaultSortDirection: "desc",
  fields: [
    {
      column: "id",
      label: "ID",
      type: "string",
      access: "readonly",
      isPrimary: true,
      showInList: true,
    },
    { column: "name", label: "Name", type: "string", access: "readonly", searchable: true, showInList: true },
    { column: "slug", label: "Slug", type: "string", access: "readonly", searchable: true, showInList: true },
    {
      column: "orgOwnerEmail",
      label: "Owner Email",
      type: "email",
      access: "readonly",
      searchable: true,
      showInList: true,
    },
    { column: "error", label: "Error", type: "string", access: "readonly", showInList: true },
    {
      column: "billingPeriod",
      label: "Billing Period",
      type: "enum",
      access: "readonly",
      enumValues: ["MONTHLY", "ANNUALLY"],
      showInList: true,
    },
    {
      column: "billingMode",
      label: "Billing Mode",
      type: "enum",
      access: "readonly",
      enumValues: ["SEATS", "ACTIVE_USERS"],
    },
    { column: "pricePerSeat", label: "Price/Seat", type: "number", access: "readonly" },
    { column: "seats", label: "Seats", type: "number", access: "readonly", showInList: true },
    { column: "minSeats", label: "Min Seats", type: "number", access: "readonly" },
    { column: "isPlatform", label: "Is Platform", type: "boolean", access: "readonly", showInList: true },
    { column: "isComplete", label: "Complete", type: "boolean", access: "readonly", showInList: true },
    { column: "isDomainConfigured", label: "Domain Configured", type: "boolean", access: "readonly" },
    { column: "logo", label: "Logo", type: "url", access: "readonly", showInList: false },
    { column: "bio", label: "Bio", type: "string", access: "readonly", showInList: false },
    { column: "brandColor", label: "Brand Color", type: "string", access: "readonly", showInList: false },
    { column: "bannerUrl", label: "Banner URL", type: "url", access: "readonly", showInList: false },
    {
      column: "stripeCustomerId",
      label: "Stripe Customer",
      type: "string",
      access: "readonly",
      searchable: true,
      showInList: false,
    },
    {
      column: "stripeSubscriptionId",
      label: "Stripe Subscription",
      type: "string",
      access: "readonly",
      showInList: false,
    },
    {
      column: "stripeSubscriptionItemId",
      label: "Stripe Sub Item",
      type: "string",
      access: "readonly",
      showInList: false,
    },
    {
      column: "invitedMembers",
      label: "Invited Members",
      type: "json",
      access: "readonly",
      showInList: false,
    },
    { column: "teams", label: "Teams", type: "json", access: "readonly", showInList: false },
    {
      column: "createdBy",
      label: "Created By",
      type: "string",
      access: "readonly",
      showInList: true,
      relation: {
        modelName: "User",
        select: { id: true, name: true, email: true },
        displayField: "name",
        linkTo: { slug: "users", paramField: "id" },
      },
    },
    {
      column: "organization",
      label: "Organization",
      type: "string",
      access: "readonly",
      showInList: true,
      relation: {
        modelName: "Team",
        select: { id: true, name: true, slug: true },
        displayField: "name",
        linkTo: { slug: "teams", paramField: "id" },
      },
    },
    ...timestamps(),
  ],
  actions: [],
  panels: [],
};
