/* v8 ignore start */
import type { TableDefinition } from "../types";

import { id, uuid } from "./_helpers";

export const userTable: TableDefinition = {
  modelName: "User",
  displayName: "User",
  displayNamePlural: "Users",
  description: "All Cal.com user accounts",
  slug: "users",
  category: "core",
  defaultSort: "id",
  defaultSortDirection: "desc",
  // Opt out of the excludeLockedUsersExtension so admins can see locked accounts
  defaultWhere: { locked: { in: [true, false] } },
  fields: [
    id(),
    uuid(),
    { column: "username", label: "Username", type: "string", access: "editable", searchable: true, showInList: true },
    { column: "name", label: "Name", type: "string", access: "editable", searchable: true, showInList: true },
    { column: "email", label: "Email", type: "email", access: "editable", searchable: true, showInList: true },
    { column: "emailVerified", label: "Email Verified", type: "datetime", access: "readonly" },
    { column: "bio", label: "Bio", type: "string", access: "editable", showInList: false },
    { column: "avatarUrl", label: "Avatar URL", type: "url", access: "hidden" },
    { column: "timeZone", label: "Timezone", type: "string", access: "editable" },
    { column: "weekStart", label: "Week Start", type: "string", access: "editable", showInList: false },
    { column: "createdDate", label: "Created", type: "datetime", access: "readonly", showInList: true, pgColumn: "created" },
    { column: "lastActiveAt", label: "Last Active", type: "datetime", access: "readonly", showInList: true },
    { column: "trialEndsAt", label: "Trial Ends", type: "datetime", access: "editable", showInList: false },
    {
      column: "role",
      label: "Role",
      type: "enum",
      access: "editable",
      enumValues: ["USER", "ADMIN"],
      showInList: true,
    },
    { column: "completedOnboarding", label: "Onboarded", type: "boolean", access: "readonly", showInList: true },
    { column: "verified", label: "Verified", type: "boolean", access: "editable" },
    { column: "locked", label: "Locked", type: "boolean", access: "editable", showInList: true },
    {
      column: "identityProvider",
      label: "Identity Provider",
      type: "enum",
      access: "readonly",
      enumValues: ["CAL", "GOOGLE", "SAML"],
    },
    { column: "locale", label: "Locale", type: "string", access: "editable", showInList: false },
    { column: "organizationId", label: "Organization ID", type: "number", access: "readonly", showInList: true },
    {
      column: "smsLockState",
      label: "SMS Lock",
      type: "enum",
      access: "editable",
      enumValues: ["UNLOCKED", "REVIEW_NEEDED", "LOCKED"],
    },
    { column: "isPlatformManaged", label: "Platform Managed", type: "boolean", access: "readonly" },

    {
      column: "teams",
      label: "Memberships",
      type: "number",
      access: "readonly",
      showInList: true,
      relation: {
        modelName: "Membership",
        select: { id: true, teamId: true, role: true, accepted: true, team: { select: { id: true, name: true, slug: true, isOrganization: true } } },
        displayField: "_count",
        many: true,
        take: 20,
      },
    },

    { column: "password", label: "Password", type: "string", access: "hidden" },
    { column: "twoFactorSecret", label: "2FA Secret", type: "string", access: "hidden" },
    { column: "backupCodes", label: "Backup Codes", type: "string", access: "hidden" },
    { column: "metadata", label: "Metadata", type: "json", access: "hidden" },
  ],
  actions: [
    {
      id: "lock",
      label: "Lock Account",
      icon: "lock",
      variant: "destructive",
      mutation: "admin.lockUserAccount",
      buildInput: (row) => ({ userId: row.id, locked: true }),
      condition: (row) => !row.locked,
      confirm: { title: "Lock {{name}}?", description: "{{email}} will be unable to log in or use the platform.", confirmLabel: "Lock" },
    },
    {
      id: "unlock",
      label: "Unlock Account",
      icon: "lock",
      variant: "default",
      mutation: "admin.lockUserAccount",
      buildInput: (row) => ({ userId: row.id, locked: false }),
      condition: (row) => row.locked === true,
    },
    {
      id: "send-password-reset",
      label: "Send Password Reset",
      icon: "mail",
      variant: "default",
      mutation: "admin.sendPasswordReset",
      buildInput: (row) => ({ userId: row.id }),
    },
    {
      id: "remove-2fa",
      label: "Remove 2FA",
      icon: "shield",
      variant: "destructive",
      mutation: "admin.removeTwoFactor",
      buildInput: (row) => ({ userId: row.id }),
      confirm: { title: "Remove 2FA for {{name}}?", description: "This will disable two-factor auth for {{email}}. They can re-enable it themselves.", confirmLabel: "Remove 2FA" },
    },
    {
      id: "verify-workflows",
      label: "Verify Workflows",
      icon: "check",
      variant: "default",
      mutation: "admin.verifyWorkflows",
      buildInput: (row) => ({ userId: row.id }),
    },
    {
      id: "whitelist-workflows",
      label: "Whitelist Workflows",
      icon: "check",
      variant: "default",
      mutation: "admin.whitelistUserWorkflows",
      buildInput: (row) => ({ userId: row.id, whitelistWorkflows: true }),
    },
    {
      id: "unwhitelist-workflows",
      label: "Remove Workflow Whitelist",
      icon: "check",
      variant: "default",
      mutation: "admin.whitelistUserWorkflows",
      buildInput: (row) => ({ userId: row.id, whitelistWorkflows: false }),
    },
    {
      id: "lock-sms",
      label: "Lock SMS",
      icon: "phone",
      variant: "destructive",
      mutation: "admin.setSMSLockState",
      buildInput: (row) => ({ userId: row.id, lock: true }),
      condition: (row) => row.smsLockState !== "LOCKED",
    },
    {
      id: "unlock-sms",
      label: "Unlock SMS",
      icon: "phone",
      variant: "default",
      mutation: "admin.setSMSLockState",
      buildInput: (row) => ({ userId: row.id, lock: false }),
      condition: (row) => row.smsLockState === "LOCKED",
    },
    {
      id: "release-username",
      label: "Release Username",
      icon: "trash",
      variant: "destructive",
      mutation: "admin.releaseUsername",
      buildInput: (row) => ({
        username: row.username,
        organizationId: row.organizationId,
        mode: "preview",
      }),
      condition: (row) => !!row.username,
      formId: "release-username",
    },
    {
      id: "delete-user",
      label: "Delete User",
      icon: "trash",
      variant: "destructive",
      mutation: "users.delete",
      buildInput: (row) => ({ userId: row.id }),
      confirm: { title: "Delete {{name}}?", description: "This will permanently delete {{email}} (ID: {{id}}). All their data, bookings, and event types will be removed. This cannot be undone.", confirmLabel: "Delete forever" },
    },
  ],
};
