/*
@calcom/api: Public API for Cal.com

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// ListBookingsAttendeeEmailParameter - struct for ListBookingsAttendeeEmailParameter
type ListBookingsAttendeeEmailParameter struct {
	ArrayOfString *[]string
	String *string
}

// []stringAsListBookingsAttendeeEmailParameter is a convenience function that returns []string wrapped in ListBookingsAttendeeEmailParameter
func ArrayOfStringAsListBookingsAttendeeEmailParameter(v *[]string) ListBookingsAttendeeEmailParameter {
	return ListBookingsAttendeeEmailParameter{
		ArrayOfString: v,
	}
}

// stringAsListBookingsAttendeeEmailParameter is a convenience function that returns string wrapped in ListBookingsAttendeeEmailParameter
func StringAsListBookingsAttendeeEmailParameter(v *string) ListBookingsAttendeeEmailParameter {
	return ListBookingsAttendeeEmailParameter{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ListBookingsAttendeeEmailParameter) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ArrayOfString
	err = newStrictDecoder(data).Decode(&dst.ArrayOfString)
	if err == nil {
		jsonArrayOfString, _ := json.Marshal(dst.ArrayOfString)
		if string(jsonArrayOfString) == "{}" { // empty struct
			dst.ArrayOfString = nil
		} else {
			match++
		}
	} else {
		dst.ArrayOfString = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			match++
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ArrayOfString = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ListBookingsAttendeeEmailParameter)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ListBookingsAttendeeEmailParameter)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ListBookingsAttendeeEmailParameter) MarshalJSON() ([]byte, error) {
	if src.ArrayOfString != nil {
		return json.Marshal(&src.ArrayOfString)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ListBookingsAttendeeEmailParameter) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ArrayOfString != nil {
		return obj.ArrayOfString
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

type NullableListBookingsAttendeeEmailParameter struct {
	value *ListBookingsAttendeeEmailParameter
	isSet bool
}

func (v NullableListBookingsAttendeeEmailParameter) Get() *ListBookingsAttendeeEmailParameter {
	return v.value
}

func (v *NullableListBookingsAttendeeEmailParameter) Set(val *ListBookingsAttendeeEmailParameter) {
	v.value = val
	v.isSet = true
}

func (v NullableListBookingsAttendeeEmailParameter) IsSet() bool {
	return v.isSet
}

func (v *NullableListBookingsAttendeeEmailParameter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListBookingsAttendeeEmailParameter(val *ListBookingsAttendeeEmailParameter) *NullableListBookingsAttendeeEmailParameter {
	return &NullableListBookingsAttendeeEmailParameter{value: val, isSet: true}
}

func (v NullableListBookingsAttendeeEmailParameter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListBookingsAttendeeEmailParameter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


