/*
@calcom/api: Public API for Cal.com

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// ListBookingsUserIdParameter - struct for ListBookingsUserIdParameter
type ListBookingsUserIdParameter struct {
	ArrayOfInt32 *[]int32
	Int32 *int32
}

// []int32AsListBookingsUserIdParameter is a convenience function that returns []int32 wrapped in ListBookingsUserIdParameter
func ArrayOfInt32AsListBookingsUserIdParameter(v *[]int32) ListBookingsUserIdParameter {
	return ListBookingsUserIdParameter{
		ArrayOfInt32: v,
	}
}

// int32AsListBookingsUserIdParameter is a convenience function that returns int32 wrapped in ListBookingsUserIdParameter
func Int32AsListBookingsUserIdParameter(v *int32) ListBookingsUserIdParameter {
	return ListBookingsUserIdParameter{
		Int32: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ListBookingsUserIdParameter) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ArrayOfInt32
	err = newStrictDecoder(data).Decode(&dst.ArrayOfInt32)
	if err == nil {
		jsonArrayOfInt32, _ := json.Marshal(dst.ArrayOfInt32)
		if string(jsonArrayOfInt32) == "{}" { // empty struct
			dst.ArrayOfInt32 = nil
		} else {
			match++
		}
	} else {
		dst.ArrayOfInt32 = nil
	}

	// try to unmarshal data into Int32
	err = newStrictDecoder(data).Decode(&dst.Int32)
	if err == nil {
		jsonInt32, _ := json.Marshal(dst.Int32)
		if string(jsonInt32) == "{}" { // empty struct
			dst.Int32 = nil
		} else {
			match++
		}
	} else {
		dst.Int32 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ArrayOfInt32 = nil
		dst.Int32 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ListBookingsUserIdParameter)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ListBookingsUserIdParameter)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ListBookingsUserIdParameter) MarshalJSON() ([]byte, error) {
	if src.ArrayOfInt32 != nil {
		return json.Marshal(&src.ArrayOfInt32)
	}

	if src.Int32 != nil {
		return json.Marshal(&src.Int32)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ListBookingsUserIdParameter) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ArrayOfInt32 != nil {
		return obj.ArrayOfInt32
	}

	if obj.Int32 != nil {
		return obj.Int32
	}

	// all schemas are nil
	return nil
}

type NullableListBookingsUserIdParameter struct {
	value *ListBookingsUserIdParameter
	isSet bool
}

func (v NullableListBookingsUserIdParameter) Get() *ListBookingsUserIdParameter {
	return v.value
}

func (v *NullableListBookingsUserIdParameter) Set(val *ListBookingsUserIdParameter) {
	v.value = val
	v.isSet = true
}

func (v NullableListBookingsUserIdParameter) IsSet() bool {
	return v.isSet
}

func (v *NullableListBookingsUserIdParameter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListBookingsUserIdParameter(val *ListBookingsUserIdParameter) *NullableListBookingsUserIdParameter {
	return &NullableListBookingsUserIdParameter{value: val, isSet: true}
}

func (v NullableListBookingsUserIdParameter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListBookingsUserIdParameter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


