export * from "@trpc/react-query/shared";

export const ENDPOINTS = [
  "admin",
  "apiKeys",
  "appRoutingForms",
  "apps",
  "auth",
  "availability",
  "appBasecamp3",
  "bookings",
  "deploymentSetup",
  "dsync",
  "eventTypes",
  "features",
  "highPerf",
  "insights",
  "payments",
  "public",
  "timezones",
  "saml",
  "slots",
  "teams",
  "organizations",
  "users",
  "viewer",
  "webhook",
  "workflows",
  "appsRouter",
  "googleWorkspace",
  "oAuth",
  "attributes",
  "routingForms",
  "domainWideDelegation",
] as const;
