import { defineConfig } from "@hey-api/openapi-ts";

export default defineConfig({
  client: "@hey-api/client-fetch",
  input: "../../docs/api-reference/v2/openapi.json",
  output: {
    path: "src/generated",
    lint: "biome",
  },
  plugins: [
    {
      name: "@hey-api/typescript",
      enums: "javascript",
    },
    {
      name: "@hey-api/sdk",
      asClass: false,
      operationId: true,
      include: [
        // User-level endpoints
        "^tag:Me$",
        "^tag:Api Keys$",
        "^tag:Bookings$",
        "^tag:Bookings / Attendees$",
        "^tag:Bookings / Guests$",
        "^tag:Cal Unified Calendars$",
        "^tag:Calendars$",
        "^tag:Conferencing$",
        "^tag:Destination Calendars$",
        "^tag:Event Types$",
        "^tag:Event Types / Webhooks$",
        "^tag:Event Types Private Links$",
        "^tag:OAuth2$",
        "^tag:Routing forms$",
        "^tag:Schedules$",
        "^tag:Selected Calendars$",
        "^tag:Slots$",
        "^tag:Stripe$",
        "^tag:Verified Resources$",
        "^tag:Webhooks$",
        // Team-level endpoints
        "^tag:Teams$",
        "^tag:Teams / Bookings$",
        "^tag:Teams / Event Types$",
        "^tag:Teams / Event Types / Webhooks$",
        "^tag:Teams / Invite$",
        "^tag:Teams / Memberships$",
        "^tag:Teams / Schedules$",
        "^tag:Teams Verified Resources$",
        // Organization-level endpoints
        "^tag:Managed Orgs$",
        "^tag:Organization Team Verified Resources$",
        "^tag:Orgs / Attributes$",
        "^tag:Orgs / Attributes / Options$",
        "^tag:Orgs / Bookings$",
        "^tag:Orgs / Delegation Credentials$",
        "^tag:Orgs / Memberships$",
        "^tag:Orgs / Roles$",
        "^tag:Orgs / Roles / Permissions$",
        "^tag:Orgs / Routing forms$",
        "^tag:Orgs / Schedules$",
        "^tag:Orgs / Teams$",
        "^tag:Orgs / Teams / Bookings$",
        "^tag:Orgs / Teams / Conferencing$",
        "^tag:Orgs / Teams / Event Types$",
        "^tag:Orgs / Teams / Event Types / Private Links$",
        "^tag:Orgs / Teams / Invite$",
        "^tag:Orgs / Teams / Memberships$",
        "^tag:Orgs / Teams / Roles$",
        "^tag:Orgs / Teams / Roles / Permissions$",
        "^tag:Orgs / Teams / Routing forms$",
        "^tag:Orgs / Teams / Routing forms / Responses$",
        "^tag:Orgs / Teams / Schedules$",
        "^tag:Orgs / Teams / Stripe$",
        "^tag:Orgs / Teams / Users / Schedules$",
        "^tag:Orgs / Teams / Workflows$",
        "^tag:Orgs / Users$",
        "^tag:Orgs / Users / Bookings$",
        "^tag:Orgs / Users / OOO$",
        "^tag:Orgs / Users / Schedules$",
        "^tag:Orgs / Webhooks$",
      ],
    },
  ],
});
