export enum BaseField {
  number = "number",
  boolean = "boolean",
  address = "address",
  name = "name",
  text = "text",
  textarea = "textarea",
  email = "email",
  phone = "phone",
  multiemail = "multiemail",
  select = "select",
  multiselect = "multiselect",
  checkbox = "checkbox",
  radio = "radio",
  radioInput = "radioInput",
}
