export const workflows = [
  // SALES WORKFLOWS (4)
  {
    id: "wf-1",
    name: "Sales Discovery Prep",
    description: "Complete sales discovery preparation workflow with pre-meeting questionnaire",
    image: "https://images.unsplash.com/photo-1434626881859-194d67b2b86f?q=80&w=800",
    features: [
      "Pre-meeting questionnaire",
      "Automatic reminder sequence",
      "Company research prompts",
      "Agenda distribution",
      "CRM integration ready",
      "Meeting preparation checklist",
    ],
    useCases: [
      "Initial sales meetings",
      "Product demonstrations",
      "Enterprise sales calls",
      "Partner meetings",
      "Sales consultations",
    ],
    tags: ["sales", "email", "preparation"],
    relatedTemplateIds: ["wf-2", "wf-3", "wf-4"],
    author: {
      name: "Cal.com",
      avatar: "/cal.png",
      bio: "Created by Cal.com's sales automation experts",
    },
    template: {
      trigger: "BEFORE_EVENT",
      time: 48,
      timeUnit: "HOUR",
      steps: [
        {
          stepNumber: 1,
          action: "EMAIL_ATTENDEE",
          template: "SALES_PREP",
          emailSubject: "Prepare for our upcoming meeting",
          reminderBody:
            "Hi {ATTENDEE}, to make our meeting most productive, please complete this brief questionnaire: {FORM_LINK}",
          includeCalendarEvent: true,
        },
      ],
    },
  },
  {
    id: "wf-2",
    name: "Sales Follow-up Sequence",
    description: "Multi-step follow-up sequence for sales meetings",
    image: "https://images.unsplash.com/photo-1512314889357-e157c22f938d?q=80&w=800",
    features: [
      "Multi-touch follow-up sequence",
      "Automated email cadence",
      "Meeting summary templates",
      "Next steps tracking",
      "Proposal attachment",
      "Response tracking",
    ],
    useCases: [
      "Post-sales meetings",
      "Proposal follow-ups",
      "Contract negotiations",
      "Deal closing process",
      "Quote follow-ups",
    ],
    tags: ["sales", "email", "follow-up"],
    relatedTemplateIds: ["wf-1", "wf-3", "wf-4"],
    author: {
      name: "Cal.com",
      avatar: "/cal.png",
      bio: "Created by Cal.com's sales enablement team",
    },
    template: {
      trigger: "AFTER_EVENT",
      time: 1,
      timeUnit: "HOUR",
      steps: [
        {
          stepNumber: 1,
          action: "EMAIL_ATTENDEE",
          template: "SALES_FOLLOW_UP",
          emailSubject: "Next steps from our discussion",
          reminderBody:
            "Hi {ATTENDEE}, thank you for our meeting. Here's a summary and next steps: {MEETING_NOTES}",
          includeCalendarEvent: false,
        },
      ],
    },
  },
  {
    id: "wf-3",
    name: "Contract Review Process",
    description: "Streamlined workflow for contract review meetings",
    image: "https://images.unsplash.com/photo-1554774853-719586f82d77?q=80&w=800",
    features: [
      "Document collection",
      "Legal requirement checklist",
      "Stakeholder notifications",
      "Review timeline tracking",
      "Signature coordination",
      "Compliance verification",
    ],
    useCases: [
      "Contract negotiations",
      "Legal reviews",
      "Partnership agreements",
      "Service agreements",
      "Terms updates",
    ],
    tags: ["sales", "legal", "contracts"],
    relatedTemplateIds: ["wf-1", "wf-2", "wf-4"],
    author: {
      name: "Cal.com",
      avatar: "/cal.png",
      bio: "Created by Cal.com's legal operations team",
    },
    template: {
      trigger: "BEFORE_EVENT",
      time: 72,
      timeUnit: "HOUR",
      steps: [
        {
          stepNumber: 1,
          action: "EMAIL_ATTENDEE",
          template: "CONTRACT_REVIEW",
          emailSubject: "Contract Review Meeting Preparation",
          reminderBody:
            "Hi {ATTENDEE}, please review and prepare the following documents for our meeting: {DOCUMENT_LIST}",
          includeCalendarEvent: true,
        },
      ],
    },
  },
  {
    id: "wf-4",
    name: "Demo Day Preparation",
    description: "Comprehensive preparation workflow for product demonstrations",
    image: "https://images.unsplash.com/photo-1557804506-669a67965ba0?q=80&w=800",
    features: [
      "Technical requirements check",
      "Demo environment setup",
      "Feature showcase outline",
      "Q&A preparation",
      "Follow-up materials",
      "Recording options",
    ],
    useCases: [
      "Product demos",
      "Feature launches",
      "Technical reviews",
      "Platform walkthroughs",
      "Integration demos",
    ],
    tags: ["sales", "demo", "technical"],
    relatedTemplateIds: ["wf-1", "wf-2", "wf-3"],
    author: {
      name: "Cal.com",
      avatar: "/cal.png",
      bio: "Created by Cal.com's product specialists",
    },
    template: {
      trigger: "BEFORE_EVENT",
      time: 24,
      timeUnit: "HOUR",
      steps: [
        {
          stepNumber: 1,
          action: "EMAIL_ATTENDEE",
          template: "DEMO_PREP",
          emailSubject: "Prepare for your product demo",
          reminderBody:
            "Hi {ATTENDEE}, please ensure you have the following technical requirements ready: {TECH_REQUIREMENTS}",
          includeCalendarEvent: true,
        },
      ],
    },
  },

  // MARKETING WORKFLOWS (4)
  {
    id: "wf-5",
    name: "Campaign Brief Distribution",
    description: "Automated distribution of marketing campaign materials",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=800",
    features: [
      "Campaign brief templates",
      "Asset distribution",
      "Timeline sharing",
      "Budget overview",
      "KPI documentation",
      "Stakeholder alignment",
    ],
    useCases: [
      "Campaign kickoffs",
      "Strategy sessions",
      "Creative reviews",
      "Budget planning",
      "Marketing meetings",
    ],
    tags: ["marketing", "email", "preparation"],
    relatedTemplateIds: ["wf-6", "wf-7", "wf-8"],
    author: {
      name: "Cal.com",
      avatar: "/cal.png",
      bio: "Created by Cal.com's marketing automation team",
    },
    template: {
      trigger: "BEFORE_EVENT",
      time: 24,
      timeUnit: "HOUR",
      steps: [
        {
          stepNumber: 1,
          action: "EMAIL_ATTENDEE",
          template: "MARKETING_BRIEF",
          emailSubject: "Campaign Brief for Tomorrow's Meeting",
          reminderBody: "Hi {ATTENDEE}, please review the campaign brief before our meeting: {BRIEF_LINK}",
          includeCalendarEvent: true,
        },
      ],
    },
  },
  {
    id: "wf-6",
    name: "Content Review Workflow",
    description: "Structured workflow for content review and approval process",
    image: "https://images.unsplash.com/photo-1512758017271-d7b84c2113f1?q=80&w=800",
    features: [
      "Content brief review",
      "Feedback collection",
      "Version tracking",
      "Approval workflow",
      "Brand guideline check",
      "Publishing checklist",
    ],
    useCases: [
      "Blog post reviews",
      "Social media content",
      "Email campaigns",
      "Website content",
      "Marketing collateral",
    ],
    tags: ["marketing", "content", "review"],
    relatedTemplateIds: ["wf-5", "wf-7", "wf-8"],
    author: {
      name: "Cal.com",
      avatar: "/cal.png",
      bio: "Created by Cal.com's content strategy team",
    },
    template: {
      trigger: "BEFORE_EVENT",
      time: 48,
      timeUnit: "HOUR",
      steps: [
        {
          stepNumber: 1,
          action: "EMAIL_ATTENDEE",
          template: "CONTENT_REVIEW",
          emailSubject: "Content Review Session Preparation",
          reminderBody:
            "Hi {ATTENDEE}, please review the content materials before our session: {CONTENT_LINK}",
          includeCalendarEvent: true,
        },
      ],
    },
  },
  {
    id: "wf-7",
    name: "Event Marketing Coordination",
    description: "Comprehensive workflow for marketing event coordination",
    image: "https://images.unsplash.com/photo-1511578314322-379afb476865?q=80&w=800",
    features: [
      "Event timeline",
      "Resource allocation",
      "Promotional schedule",
      "Stakeholder updates",
      "Budget tracking",
      "Success metrics",
    ],
    useCases: ["Virtual events", "Product launches", "Webinars", "Trade shows", "Marketing conferences"],
    tags: ["marketing", "events", "coordination"],
    relatedTemplateIds: ["wf-5", "wf-6", "wf-8"],
    author: {
      name: "Cal.com",
      avatar: "/cal.png",
      bio: "Created by Cal.com's event marketing specialists",
    },
    template: {
      trigger: "BEFORE_EVENT",
      time: 72,
      timeUnit: "HOUR",
      steps: [
        {
          stepNumber: 1,
          action: "EMAIL_ATTENDEE",
          template: "EVENT_PREP",
          emailSubject: "Event Coordination Meeting Details",
          reminderBody: "Hi {ATTENDEE}, here's the event planning packet for review: {EVENT_DOCS}",
          includeCalendarEvent: true,
        },
      ],
    },
  },
  {
    id: "wf-8",
    name: "Social Media Campaign Planning",
    description: "Structured workflow for social media campaign planning and execution",
    image: "https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?q=80&w=800",
    features: [
      "Content calendar",
      "Asset management",
      "Platform strategy",
      "Engagement tracking",
      "Hashtag research",
      "Performance metrics",
    ],
    useCases: [
      "Social campaigns",
      "Influencer coordination",
      "Content planning",
      "Community management",
      "Brand awareness",
    ],
    tags: ["marketing", "social-media", "planning"],
    relatedTemplateIds: ["wf-5", "wf-6", "wf-7"],
    author: {
      name: "Cal.com",
      avatar: "/cal.png",
      bio: "Created by Cal.com's social media team",
    },
    template: {
      trigger: "BEFORE_EVENT",
      time: 24,
      timeUnit: "HOUR",
      steps: [
        {
          stepNumber: 1,
          action: "EMAIL_ATTENDEE",
          template: "SOCIAL_CAMPAIGN",
          emailSubject: "Social Media Campaign Planning Session",
          reminderBody:
            "Hi {ATTENDEE}, please review our campaign brief and content calendar: {CAMPAIGN_DOCS}",
          includeCalendarEvent: true,
        },
      ],
    },
  },

  // EDUCATION WORKFLOWS (4)
  {
    id: "wf-9",
    name: "Student Advisory Session",
    description: "Comprehensive workflow for student advisory meetings",
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=800",
    features: [
      "Academic record review",
      "Course planning guide",
      "Progress tracking",
      "Goal setting template",
      "Resource sharing",
      "Action plan creation",
    ],
    useCases: [
      "Academic advising",
      "Course selection",
      "Career planning",
      "Graduate school prep",
      "Academic support",
    ],
    tags: ["education", "advising", "planning"],
    relatedTemplateIds: ["wf-10", "wf-11", "wf-12"],
    author: {
      name: "Cal.com",
      avatar: "/cal.png",
      bio: "Created by Cal.com's education specialists",
    },
    template: {
      trigger: "BEFORE_EVENT",
      time: 48,
      timeUnit: "HOUR",
      steps: [
        {
          stepNumber: 1,
          action: "EMAIL_ATTENDEE",
          template: "ADVISORY_PREP",
          emailSubject: "Prepare for Your Advisory Session",
          reminderBody:
            "Hi {ATTENDEE}, please review your academic progress report before our meeting: {PROGRESS_REPORT}",
          includeCalendarEvent: true,
        },
      ],
    },
  },
  {
    id: "wf-10",
    name: "Research Consultation",
    description: "Structured workflow for academic research consultations",
    image: "https://images.unsplash.com/photo-1532619187608-e5375cab36aa?q=80&w=800",
    features: [
      "Research proposal review",
      "Literature search guide",
      "Methodology planning",
      "Resource access setup",
      "Timeline creation",
      "Documentation templates",
    ],
    useCases: [
      "Research planning",
      "Thesis consultation",
      "Methodology review",
      "Literature review",
      "Data analysis",
    ],
    tags: ["education", "research", "academic"],
    relatedTemplateIds: ["wf-9", "wf-11", "wf-12"],
    author: {
      name: "Cal.com",
      avatar: "/cal.png",
      bio: "Created by Cal.com's research advisors",
    },
    template: {
      trigger: "BEFORE_EVENT",
      time: 72,
      timeUnit: "HOUR",
      steps: [
        {
          stepNumber: 1,
          action: "EMAIL_ATTENDEE",
          template: "RESEARCH_PREP",
          emailSubject: "Research Consultation Preparation",
          reminderBody:
            "Hi {ATTENDEE}, please prepare your research outline and questions: {RESEARCH_TEMPLATE}",
          includeCalendarEvent: true,
        },
      ],
    },
  },
  {
    id: "wf-11",
    name: "Course Material Distribution",
    description: "Automated workflow for course material distribution and preparation",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?q=80&w=800",
    features: [
      "Reading list distribution",
      "Assignment schedule",
      "Learning objectives",
      "Study guides",
      "Resource access",
      "Discussion topics",
    ],
    useCases: [
      "Course preparation",
      "Study sessions",
      "Tutorial planning",
      "Workshop preparation",
      "Group study",
    ],
    tags: ["education", "course", "materials"],
    relatedTemplateIds: ["wf-9", "wf-10", "wf-12"],
    author: {
      name: "Cal.com",
      avatar: "/cal.png",
      bio: "Created by Cal.com's educational content team",
    },
    template: {
      trigger: "BEFORE_EVENT",
      time: 48,
      timeUnit: "HOUR",
      steps: [
        {
          stepNumber: 1,
          action: "EMAIL_ATTENDEE",
          template: "COURSE_PREP",
          emailSubject: "Course Materials for Next Session",
          reminderBody:
            "Hi {ATTENDEE}, here are the materials to review before our next session: {COURSE_MATERIALS}",
          includeCalendarEvent: true,
        },
      ],
    },
  },
  {
    id: "wf-12",
    name: "Academic Progress Review",
    description: "Structured workflow for academic progress review meetings",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=800",
    features: [
      "Grade review",
      "Performance analysis",
      "Goal tracking",
      "Action planning",
      "Resource identification",
      "Support planning",
    ],
    useCases: [
      "Progress reviews",
      "Academic planning",
      "Performance improvement",
      "Goal setting",
      "Support coordination",
    ],
    tags: ["education", "progress", "review"],
    relatedTemplateIds: ["wf-9", "wf-10", "wf-11"],
    author: {
      name: "Cal.com",
      avatar: "/cal.png",
      bio: "Created by Cal.com's academic advisors",
    },
    template: {
      trigger: "BEFORE_EVENT",
      time: 24,
      timeUnit: "HOUR",
      steps: [
        {
          stepNumber: 1,
          action: "EMAIL_ATTENDEE",
          template: "PROGRESS_REVIEW",
          emailSubject: "Academic Progress Review Preparation",
          reminderBody: "Hi {ATTENDEE}, please review your academic progress report: {PROGRESS_REPORT}",
          includeCalendarEvent: true,
        },
      ],
    },
  },

  // HEALTHCARE WORKFLOWS (4)
  {
    id: "wf-13",
    name: "Patient Intake Process",
    description: "Comprehensive workflow for new patient intake",
    image: "https://images.unsplash.com/photo-1584982751601-97dcc096659c?q=80&w=800",
    features: [
      "Medical history collection",
      "Insurance verification",
      "Consent forms",
      "Appointment reminders",
      "Pre-visit instructions",
      "Documentation tracking",
    ],
    useCases: [
      "New patient visits",
      "Specialist referrals",
      "Initial consultations",
      "Health screenings",
      "Annual physicals",
    ],
    tags: ["healthcare", "intake", "onboarding"],
    relatedTemplateIds: ["wf-14", "wf-15", "wf-16"],
    author: {
      name: "Cal.com",
      avatar: "/cal.png",
      bio: "Created by Cal.com's healthcare specialists",
    },
    template: {
      trigger: "BEFORE_EVENT",
      time: 72,
      timeUnit: "HOUR",
      steps: [
        {
          stepNumber: 1,
          action: "EMAIL_ATTENDEE",
          template: "PATIENT_INTAKE",
          emailSubject: "Prepare for Your First Visit",
          reminderBody: "Hi {ATTENDEE}, please complete these forms before your visit: {INTAKE_FORMS}",
          includeCalendarEvent: true,
        },
      ],
    },
  },
  {
    id: "wf-14",
    name: "Treatment Follow-up",
    description: "Structured workflow for post-treatment follow-up",
    image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?q=80&w=800",
    features: [
      "Recovery tracking",
      "Symptom monitoring",
      "Medication reminders",
      "Progress assessment",
      "Care plan updates",
      "Appointment scheduling",
    ],
    useCases: [
      "Post-treatment care",
      "Recovery monitoring",
      "Medication management",
      "Therapy follow-up",
      "Wellness checks",
    ],
    tags: ["healthcare", "follow-up", "treatment"],
    relatedTemplateIds: ["wf-13", "wf-15", "wf-16"],
    author: {
      name: "Cal.com",
      avatar: "/cal.png",
      bio: "Created by Cal.com's healthcare providers",
    },
    template: {
      trigger: "AFTER_EVENT",
      time: 24,
      timeUnit: "HOUR",
      steps: [
        {
          stepNumber: 1,
          action: "EMAIL_ATTENDEE",
          template: "TREATMENT_FOLLOWUP",
          emailSubject: "Your Treatment Follow-up",
          reminderBody: "Hi {ATTENDEE}, please complete this follow-up assessment: {ASSESSMENT_LINK}",
          includeCalendarEvent: false,
        },
      ],
    },
  },
  {
    id: "wf-15",
    name: "Telehealth Consultation",
    description: "Comprehensive workflow for virtual healthcare consultations",
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?q=80&w=800",
    features: [
      "Technical setup guide",
      "Virtual waiting room",
      "Document sharing",
      "Session recording",
      "Follow-up scheduling",
      "Care summary",
    ],
    useCases: [
      "Virtual consultations",
      "Remote check-ups",
      "Mental health sessions",
      "Nutrition counseling",
      "Wellness coaching",
    ],
    tags: ["healthcare", "telehealth", "virtual"],
    relatedTemplateIds: ["wf-13", "wf-14", "wf-16"],
    author: {
      name: "Cal.com",
      avatar: "/cal.png",
      bio: "Created by Cal.com's telehealth experts",
    },
    template: {
      trigger: "BEFORE_EVENT",
      time: 1,
      timeUnit: "HOUR",
      steps: [
        {
          stepNumber: 1,
          action: "EMAIL_ATTENDEE",
          template: "TELEHEALTH_PREP",
          emailSubject: "Your Virtual Appointment Details",
          reminderBody: "Hi {ATTENDEE}, click here to join your virtual consultation: {MEETING_LINK}",
          includeCalendarEvent: true,
        },
      ],
    },
  },
  {
    id: "wf-16",
    name: "Health Education Distribution",
    description: "Automated workflow for health education and resource distribution",
    image: "https://images.unsplash.com/photo-1576671081837-49000212a370?q=80&w=800",
    features: [
      "Educational materials",
      "Resource library",
      "Wellness tips",
      "Progress tracking",
      "Interactive content",
      "Feedback collection",
    ],
    useCases: [
      "Patient education",
      "Wellness programs",
      "Health workshops",
      "Prevention planning",
      "Lifestyle coaching",
    ],
    tags: ["healthcare", "education", "resources"],
    relatedTemplateIds: ["wf-13", "wf-14", "wf-15"],
    author: {
      name: "Cal.com",
      avatar: "/cal.png",
      bio: "Created by Cal.com's health education team",
    },
    template: {
      trigger: "BEFORE_EVENT",
      time: 48,
      timeUnit: "HOUR",
      steps: [
        {
          stepNumber: 1,
          action: "EMAIL_ATTENDEE",
          template: "HEALTH_EDUCATION",
          emailSubject: "Your Health Education Materials",
          reminderBody: "Hi {ATTENDEE}, here are your health education materials: {EDUCATION_MATERIALS}",
          includeCalendarEvent: true,
        },
      ],
    },
  },
];
