declare const removeUserFromOrg: ({ userId, orgId }: {
    userId: number;
    orgId: number;
}) => Promise<{
    membership: {
        user: {
            metadata: import(".prisma/client").Prisma.JsonValue;
            theme: string | null;
            id: number;
            name: string | null;
            email: string;
            organizationId: number | null;
            timeZone: string;
            username: string | null;
            locale: string | null;
            startTime: number;
            endTime: number;
            bio: string | null;
            hideBranding: boolean;
            brandColor: string | null;
            darkBrandColor: string | null;
            timeFormat: number | null;
            weekStart: string;
            smsLockState: import(".prisma/client").$Enums.SMSLockState;
            smsLockReviewedByAdmin: boolean;
            emailVerified: Date | null;
            avatarUrl: string | null;
            bufferTime: number;
            appTheme: string | null;
            createdDate: Date;
            trialEndsAt: Date | null;
            defaultScheduleId: number | null;
            completedOnboarding: boolean;
            twoFactorSecret: string | null;
            twoFactorEnabled: boolean;
            backupCodes: string | null;
            identityProvider: import(".prisma/client").$Enums.IdentityProvider;
            identityProviderId: string | null;
            invitedTo: number | null;
            allowDynamicBooking: boolean | null;
            allowSEOIndexing: boolean | null;
            receiveMonthlyDigestEmail: boolean | null;
            verified: boolean | null;
            role: import(".prisma/client").$Enums.UserPermissionRole;
            disableImpersonation: boolean;
            locked: boolean;
            movedToProfileId: number | null;
            isPlatformManaged: boolean;
        };
        team: {
            metadata: import(".prisma/client").Prisma.JsonValue;
            theme: string | null;
            id: number;
            name: string;
            timeZone: string;
            slug: string | null;
            parentId: number | null;
            createdAt: Date;
            logoUrl: string | null;
            calVideoLogo: string | null;
            appLogo: string | null;
            appIconLogo: string | null;
            bio: string | null;
            hideBranding: boolean;
            isPrivate: boolean;
            hideBookATeamMember: boolean;
            brandColor: string | null;
            darkBrandColor: string | null;
            bannerUrl: string | null;
            timeFormat: number | null;
            weekStart: string;
            isOrganization: boolean;
            pendingPayment: boolean;
            isPlatform: boolean;
            createdByOAuthClientId: string | null;
            smsLockState: import(".prisma/client").$Enums.SMSLockState;
            smsLockReviewedByAdmin: boolean;
        };
    } & {
        id: number;
        userId: number;
        teamId: number;
        role: import(".prisma/client").$Enums.MembershipRole;
        disableImpersonation: boolean;
        accepted: boolean;
    };
}>;
export default removeUserFromOrg;
//# sourceMappingURL=removeUserFromOrg.d.ts.map