export const ADMIN_DI_TOKENS = {
  LOCK_USER_ACCOUNT_ACTION: Symbol("LockUserAccountAction"),
  LOCK_USER_ACCOUNT_ACTION_MODULE: Symbol("LockUserAccountActionModule"),
  DELETE_ORG_ONBOARDING_ACTION: Symbol("DeleteOrganizationOnboardingAction"),
  DELETE_ORG_ONBOARDING_ACTION_MODULE: Symbol("DeleteOrganizationOnboardingActionModule"),
  EDIT_ORG_ONBOARDING_ACTION: Symbol("EditOrganizationOnboardingAction"),
  EDIT_ORG_ONBOARDING_ACTION_MODULE: Symbol("EditOrganizationOnboardingActionModule"),
  ADMIN_USER_REPOSITORY: Symbol("AdminUserRepository"),
  ADMIN_USER_REPOSITORY_MODULE: Symbol("AdminUserRepositoryModule"),
  ADMIN_ORG_ONBOARDING_REPOSITORY: Symbol("AdminOrgOnboardingRepository"),
  ADMIN_ORG_ONBOARDING_REPOSITORY_MODULE: Symbol("AdminOrgOnboardingRepositoryModule"),
  USER_UNBLOCK_SERVICE: Symbol("UserUnblockService"),
  USER_UNBLOCK_SERVICE_MODULE: Symbol("UserUnblockServiceModule"),
  WORKFLOW_REMINDER_REPOSITORY: Symbol("WorkflowReminderRepository"),
  WORKFLOW_REMINDER_REPOSITORY_MODULE: Symbol("WorkflowReminderRepositoryModule"),
  WORKFLOW_REMOVAL_SERVICE: Symbol("WorkflowRemovalService"),
  WORKFLOW_REMOVAL_SERVICE_MODULE: Symbol("WorkflowRemovalServiceModule"),
};
