#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if [ -f .git/MERGE_HEAD ]; then
  echo "Merge detected. Skipping lint-staged and generators."
  exit 0
fi

yarn lint-staged
yarn app-store:build && git add packages/app-store/*.generated.*
