name: Production Build
description: "Creates a production build, caches it and restores if necessary"
runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/cache-db
      id: cache-db
      with:
        DATABASE_URL: ${{ env.DATABASE_URL }}
    - uses: ./.github/actions/cache-build
      id: prod-build-cache
    - name: Next.js production build
      if: steps.cache-db.outputs.cache-hit != 'true'
      shell: bash
      run: yarn db-seed
    - name: Prisma DB seed
      if: steps.prod-build-cache.outputs.cache-hit != 'true'
      shell: bash
      run: yarn build
