import type { inferRouterOutputs } from "@calcom/trpc";
export type UserAdminRouter = typeof userAdminRouter;
export type UserAdminRouterOutputs = inferRouterOutputs<UserAdminRouter>;
export declare const userAdminRouter: import("@trpc/server/unstable-core-do-not-import").CreateRouterInner<import("@trpc/server/unstable-core-do-not-import").RootConfig<{
    ctx: import("@calcom/trpc/server/createContext").InnerContext;
    meta: object;
    errorShape: import("@trpc/server/unstable-core-do-not-import").DefaultErrorShape;
    transformer: {
        stringify: (object: any) => string;
        parse: <T = unknown>(string: string) => T;
        serialize: (object: any) => import("superjson/dist/types").SuperJSONResult;
        deserialize: <T_1 = unknown>(payload: import("superjson/dist/types").SuperJSONResult) => T_1;
        registerClass: (v: import("superjson/dist/types").Class, options?: string | import("superjson/dist/class-registry").RegisterOptions | undefined) => void;
        registerSymbol: (v: Symbol, identifier?: string | undefined) => void;
        registerCustom: <I, O extends import("superjson/dist/types").JSONValue>(transformer: Omit<import("superjson/dist/custom-transformer-registry").CustomTransfomer<I, O>, "name">, name: string) => void;
        allowErrorProps: (...props: string[]) => void;
    };
}>, {
    get: import("@trpc/server/unstable-core-do-not-import").QueryProcedure<{
        input: {
            userId: number;
        };
        output: {
            user: {
                name: string | null;
                email: string;
                id: number;
                organizationId: number | null;
                locale: string | null;
                twoFactorSecret: string | null;
                emailVerified: Date | null;
                identityProviderId: string | null;
                invitedTo: number | null;
                allowDynamicBooking: boolean | null;
                verified: boolean | null;
                username: string | null;
                bio: string | null;
                avatarUrl: string | null;
                timeZone: string;
                weekStart: string;
                startTime: number;
                endTime: number;
                bufferTime: number;
                hideBranding: boolean;
                theme: string | null;
                appTheme: string | null;
                createdDate: Date;
                trialEndsAt: Date | null;
                defaultScheduleId: number | null;
                completedOnboarding: boolean;
                timeFormat: number | null;
                twoFactorEnabled: boolean;
                backupCodes: string | null;
                identityProvider: import(".prisma/client").$Enums.IdentityProvider;
                brandColor: string | null;
                darkBrandColor: string | null;
                allowSEOIndexing: boolean | null;
                receiveMonthlyDigestEmail: boolean | null;
                metadata: import(".prisma/client").Prisma.JsonValue;
                role: import(".prisma/client").$Enums.UserPermissionRole;
                disableImpersonation: boolean;
                locked: boolean;
                movedToProfileId: number | null;
                isPlatformManaged: boolean;
                smsLockState: import(".prisma/client").$Enums.SMSLockState;
                smsLockReviewedByAdmin: boolean;
            };
        };
    }>;
    list: import("@trpc/server/unstable-core-do-not-import").QueryProcedure<{
        input: void;
        output: {
            name: string | null;
            email: string;
            id: number;
            organizationId: number | null;
            locale: string | null;
            twoFactorSecret: string | null;
            emailVerified: Date | null;
            identityProviderId: string | null;
            invitedTo: number | null;
            allowDynamicBooking: boolean | null;
            verified: boolean | null;
            username: string | null;
            bio: string | null;
            avatarUrl: string | null;
            timeZone: string;
            weekStart: string;
            startTime: number;
            endTime: number;
            bufferTime: number;
            hideBranding: boolean;
            theme: string | null;
            appTheme: string | null;
            createdDate: Date;
            trialEndsAt: Date | null;
            defaultScheduleId: number | null;
            completedOnboarding: boolean;
            timeFormat: number | null;
            twoFactorEnabled: boolean;
            backupCodes: string | null;
            identityProvider: import(".prisma/client").$Enums.IdentityProvider;
            brandColor: string | null;
            darkBrandColor: string | null;
            allowSEOIndexing: boolean | null;
            receiveMonthlyDigestEmail: boolean | null;
            metadata: import(".prisma/client").Prisma.JsonValue;
            role: import(".prisma/client").$Enums.UserPermissionRole;
            disableImpersonation: boolean;
            locked: boolean;
            movedToProfileId: number | null;
            isPlatformManaged: boolean;
            smsLockState: import(".prisma/client").$Enums.SMSLockState;
            smsLockReviewedByAdmin: boolean;
        }[];
    }>;
    add: import("@trpc/server/unstable-core-do-not-import").MutationProcedure<{
        input: {
            email: string;
            timeZone: string;
            weekStart: string;
            identityProvider: "CAL" | "GOOGLE" | "SAML";
            role: "USER" | "ADMIN";
            name?: string | null | undefined;
            locale?: string | null | undefined;
            allowDynamicBooking?: boolean | null | undefined;
            username?: string | null | undefined;
            bio?: string | null | undefined;
            avatarUrl?: string | null | undefined;
            theme?: string | null | undefined;
            defaultScheduleId?: number | null | undefined;
            timeFormat?: number | null | undefined;
        };
        output: {
            user: {
                name: string | null;
                email: string;
                id: number;
                organizationId: number | null;
                locale: string | null;
                twoFactorSecret: string | null;
                emailVerified: Date | null;
                identityProviderId: string | null;
                invitedTo: number | null;
                allowDynamicBooking: boolean | null;
                verified: boolean | null;
                username: string | null;
                bio: string | null;
                avatarUrl: string | null;
                timeZone: string;
                weekStart: string;
                startTime: number;
                endTime: number;
                bufferTime: number;
                hideBranding: boolean;
                theme: string | null;
                appTheme: string | null;
                createdDate: Date;
                trialEndsAt: Date | null;
                defaultScheduleId: number | null;
                completedOnboarding: boolean;
                timeFormat: number | null;
                twoFactorEnabled: boolean;
                backupCodes: string | null;
                identityProvider: import(".prisma/client").$Enums.IdentityProvider;
                brandColor: string | null;
                darkBrandColor: string | null;
                allowSEOIndexing: boolean | null;
                receiveMonthlyDigestEmail: boolean | null;
                metadata: import(".prisma/client").Prisma.JsonValue;
                role: import(".prisma/client").$Enums.UserPermissionRole;
                disableImpersonation: boolean;
                locked: boolean;
                movedToProfileId: number | null;
                isPlatformManaged: boolean;
                smsLockState: import(".prisma/client").$Enums.SMSLockState;
                smsLockReviewedByAdmin: boolean;
            };
            message: string;
        };
    }>;
    update: import("@trpc/server/unstable-core-do-not-import").MutationProcedure<{
        input: {
            name?: string | null | undefined;
            email?: string | undefined;
            locale?: string | null | undefined;
            allowDynamicBooking?: boolean | null | undefined;
            username?: string | null | undefined;
            bio?: string | null | undefined;
            avatarUrl?: string | null | undefined;
            timeZone?: string | undefined;
            weekStart?: string | undefined;
            theme?: string | null | undefined;
            defaultScheduleId?: number | null | undefined;
            timeFormat?: number | null | undefined;
            identityProvider?: "CAL" | "GOOGLE" | "SAML" | undefined;
            role?: "USER" | "ADMIN" | undefined;
        };
        output: {
            user: {
                name: string | null;
                email: string;
                id: number;
                organizationId: number | null;
                locale: string | null;
                twoFactorSecret: string | null;
                emailVerified: Date | null;
                identityProviderId: string | null;
                invitedTo: number | null;
                allowDynamicBooking: boolean | null;
                verified: boolean | null;
                username: string | null;
                bio: string | null;
                avatarUrl: string | null;
                timeZone: string;
                weekStart: string;
                startTime: number;
                endTime: number;
                bufferTime: number;
                hideBranding: boolean;
                theme: string | null;
                appTheme: string | null;
                createdDate: Date;
                trialEndsAt: Date | null;
                defaultScheduleId: number | null;
                completedOnboarding: boolean;
                timeFormat: number | null;
                twoFactorEnabled: boolean;
                backupCodes: string | null;
                identityProvider: import(".prisma/client").$Enums.IdentityProvider;
                brandColor: string | null;
                darkBrandColor: string | null;
                allowSEOIndexing: boolean | null;
                receiveMonthlyDigestEmail: boolean | null;
                metadata: import(".prisma/client").Prisma.JsonValue;
                role: import(".prisma/client").$Enums.UserPermissionRole;
                disableImpersonation: boolean;
                locked: boolean;
                movedToProfileId: number | null;
                isPlatformManaged: boolean;
                smsLockState: import(".prisma/client").$Enums.SMSLockState;
                smsLockReviewedByAdmin: boolean;
            };
            message: string;
        };
    }>;
    delete: import("@trpc/server/unstable-core-do-not-import").MutationProcedure<{
        input: {
            userId: number;
        };
        output: {
            message: string;
        };
    }>;
}>;
//# sourceMappingURL=trpc-router.d.ts.map