name: Production Build

on:
  workflow_call:

env:
  DATABASE_URL: ${{ secrets.CI_DATABASE_URL }}
  DATABASE_DIRECT_URL: ${{ secrets.CI_DATABASE_URL }}
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  build:
    name: Build API v2
    permissions:
      contents: read
    runs-on: [craci]
    timeout-minutes: 30
    steps:
      - uses: cracicorp/setup@v1
        with:
          size: "8"
          image: "default"
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - uses: ./.github/actions/craci-services
      - uses: ./.github/actions/cache-checkout
      - uses: ./.github/actions/yarn-install
      - name: Generate Prisma schemas
        working-directory: apps/api/v2
        run: yarn workspace @calcom/api-v2 run generate-schemas
      - name: Build API v2 with Turbo
        run: |
          export NODE_OPTIONS="--max_old_space_size=8192"
          yarn turbo run build --filter=@calcom/api-v2
        shell: bash
