name: Atoms E2E Tests

on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/platform/atoms/**'
      - 'packages/platform/examples/base/**'
      - 'apps/api/v2/**'
      - '.github/workflows/atoms-e2e.yml'

permissions:
  actions: write
  contents: read

env:
  NODE_OPTIONS: --max-old-space-size=8096
  ATOMS_E2E_OAUTH_CLIENT_ID: ${{ secrets.ATOMS_E2E_OAUTH_CLIENT_ID }}
  ATOMS_E2E_OAUTH_CLIENT_SECRET: ${{ secrets.ATOMS_E2E_OAUTH_CLIENT_SECRET }}
  ATOMS_E2E_API_URL: ${{ secrets.ATOMS_E2E_API_URL }}
  ATOMS_E2E_ORG_ID: ${{ secrets.ATOMS_E2E_ORG_ID }}
  ATOMS_E2E_OAUTH_CLIENT_ID_BOOKER_EMBED: ${{ secrets.ATOMS_E2E_OAUTH_CLIENT_ID_BOOKER_EMBED }}
  DATABASE_DIRECT_URL: ${{ secrets.CI_DATABASE_URL }}
  DATABASE_URL: ${{ secrets.CI_DATABASE_URL }}

jobs:
  atoms-e2e:
    timeout-minutes: 15
    name: Atoms E2E Tests
    runs-on: buildjet-4vcpu-ubuntu-2204
    steps:
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v4
      - uses: ./.github/actions/dangerous-git-checkout
      - uses: ./.github/actions/yarn-install
      - uses: ./.github/actions/yarn-playwright-install
      - name: Run Atoms E2E Tests
        working-directory: packages/platform/examples/base
        run: yarn test:e2e
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: atoms-e2e-test-results
          path: test-results
          retention-days: 7
      - name: Upload Playwright Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: atoms-e2e-playwright-report
          path: playwright-report
          retention-days: 7
