name: Create PR containing updated CHANGELOG.md and release packages to NPM once PR is merged

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions:
  id-token: write # for NPM provenance and OIDC trusted publishing
  contents: write # to create release by changesets/action below
  pull-requests: write # to create pull request by changesets/action below

jobs:
  release:
    if: github.repository == 'calcom/cal' # prevent this action from running on forks
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: generate-token
        uses: actions/create-github-app-token@7e473efe3cb98aa54f8d4bac15400b15fad77d94
        with:
          app-id: ${{ secrets.CI_CAL_APP_ID }}
          private-key: ${{ secrets.CI_CAL_APP_PRIVATE_KEY }}
          repositories: 'cal'
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.generate-token.outputs.token }}
      - name: Setup node, yarn and install dependencies
        uses: ./.github/actions/yarn-install
      - name: Setup Node 22 and registry for OIDC trusted publishing
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"
          always-auth: false
      - name: Install npm at version supporting OIDC
        run: npm install -g npm@11.11.0
      # TODO: Implement ENG-754 and remove prisma generation here
      - run: yarn prisma generate
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn changesets-version
          publish: yarn changesets-release
          commit: "chore: version packages" # commit message
          title: "chore: version packages" # PR title
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
          NPM_CONFIG_PROVENANCE: "false"
          VITE_BOOKER_EMBED_OAUTH_CLIENT_ID: ${{ secrets.CI_VITE_BOOKER_EMBED_OAUTH_CLIENT_ID }}
          VITE_BOOKER_EMBED_API_URL: ${{ vars.CI_VITE_BOOKER_EMBED_API_URL }}
          NEXT_PUBLIC_WEBAPP_URL: ${{ secrets.NEXT_PUBLIC_WEBAPP_URL }}
