name: Check Prisma Migrations
on:
  workflow_call:

env:
  DATABASE_URL: ${{ secrets.CI_DATABASE_URL }}

jobs:
  check-prisma-migrations:
    name: Check migrations match schema
    runs-on: [craci]
    steps:
      - uses: cracicorp/setup@v1
        with:
          size: "2"
          image: "default"
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - uses: ./.github/actions/craci-services
      - uses: ./.github/actions/cache-checkout
      - uses: ./.github/actions/yarn-install
      - name: Check if migrations match schema
        working-directory: packages/prisma
        run: |
          npx prisma migrate diff --exit-code \
            --from-migrations ./migrations \
            --to-schema-datamodel ./schema.prisma \
            --shadow-database-url ${{ env.DATABASE_URL }}
