name: PR Label Check
on:
  pull_request_target:
    types: [labeled]
    branches:
      - main
      - gh-actions-test-branch

permissions:
  contents: read
  pull-requests: read
  actions: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  trigger-pr-workflow:
    if: ${{ github.event.label.name == 'ready-for-e2e' }}
    runs-on: ubuntu-latest
    steps:
      - name: Trigger PR workflow via repository dispatch
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.repos.createDispatchEvent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event_type: 'ready-for-e2e',
              client_payload: {
                pr_number: ${{ github.event.pull_request.number }},
                pr_ref: '${{ github.event.pull_request.head.ref }}',
                pr_sha: '${{ github.event.pull_request.head.sha }}',
                pr_base_ref: '${{ github.event.pull_request.base.ref }}'
              }
            });
