name: PR Reviewed

on:
  pull_request_review:
    types: [submitted]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      issues: write
      pull-requests: write
    steps:
      - name: Label PR as ready for E2E
        if: github.event.review.state == 'approved'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.READY_FOR_E2E_PAT }}
          labels: 'ready-for-e2e'
