name: PR Reviewed

on:
  pull_request_review:
    types: [submitted]

jobs:
  label-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Label PR as ready for E2E
        if: github.event.review.state == 'approved'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: 'ready-for-e2e'
