name: PR Reviewed

on:
  pull_request_review:
    types: [submitted]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      issues: write
      pull-requests: write
    steps:
      - name: Label PR as ready for E2E
        if: github.event.review.state == 'approved'
        uses: actions/github-script@v4
        with:
          script: |
            await github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: process.env.labels.split(', '),
            })
        env:
          github_token: ${{ secrets.READY_FOR_E2E_PAT }}
          labels: 'ready-for-e2e'
