name: Provision Infrastructure
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      # TODO: Setup Terraform

      # TODO: Add Terraform init & apply step

      # TODO: Export server IP from Terraform output into $GITHUB_ENV

      # TODO: Install Ansible

      # TODO: Prepare SSH key and vault password from GitHub secrets

      # TODO: Run Ansible bootstrap playbook

      # TODO: Cleanup secrets
