import type { BookerEvent } from "@calcom/features/bookings/types";

export const mockEvent: BookerEvent = {
  id: 1,
  title: "Quick check-in",
  slug: "quick-check-in",
  description:
    "Use this event for a quick 15 minute catchup. Visit this long url to test the component https://cal.com/averylongurlwithoutspacesthatshouldntbreaklayout",
  schedulingType: null,
  length: 30,
  locations: [{ type: "integrations:google:meet" }, { type: "integrations:zoom" }],
  // Required properties from BookerEvent type
  interfaceLanguage: null,
  bookingFields: [],
  lockTimeZoneToggleOnBookingPage: false,
  lockedTimeZone: null,
  recurringEvent: null,
  entity: null,
  metadata: null,
  isDynamic: false,
  requiresConfirmation: false,
  price: 0,
  currency: "USD",
  schedule: null,
  seatsPerTimeSlot: null,
  forwardParamsSuccessRedirect: false,
  successRedirectUrl: null,
  subsetOfHosts: null,
  seatsShowAvailabilityCount: false,
  isInstantEvent: false,
  instantMeetingParameters: null,
  fieldTranslations: null,
  autoTranslateDescriptionEnabled: false,
  disableCancelling: false,
  disableRescheduling: false,
  team: null,
  owner: null,
  subsetOfUsers: [],
  showInstantEventConnectNowModal: false,
  profile: {
    name: null,
    image: null,
    bookerLayouts: null,
  },
};
