export const BOOKING_DI_TOKENS = {
  REGULAR_BOOKING_SERVICE: Symbol("RegularBookingService"),
  REGULAR_BOOKING_SERVICE_MODULE: Symbol("RegularBookingServiceModule"),
  RECURRING_BOOKING_SERVICE: Symbol("RecurringBookingService"),
  RECURRING_BOOKING_SERVICE_MODULE: Symbol("RecurringBookingServiceModule"),
  INSTANT_BOOKING_CREATE_SERVICE: Symbol("InstantBookingCreateService"),
  INSTANT_BOOKING_CREATE_SERVICE_MODULE: Symbol("InstantBookingCreateServiceModule"),
  BOOKING_CANCEL_SERVICE: Symbol("BookingCancelService"),
  BOOKING_CANCEL_SERVICE_MODULE: Symbol("BookingCancelServiceModule"),
  BOOKING_REFERENCE_REPOSITORY: Symbol("BookingReferenceRepository"),
  BOOKING_REFERENCE_REPOSITORY_MODULE: Symbol("BookingReferenceRepositoryModule"),
  BOOKING_ATTENDEE_REPOSITORY: Symbol("BookingAttendeeRepository"),
  BOOKING_ATTENDEE_REPOSITORY_MODULE: Symbol("BookingAttendeeRepositoryModule"),
  BOOKING_EMAIL_SMS_HANDLER: Symbol("BookingEmailSmsHandler"),
  BOOKING_EMAIL_SMS_HANDLER_MODULE: Symbol("BookingEmailSmsHandlerModule"),
  BOOKING_EVENT_HANDLER_SERVICE: Symbol("BookingEventHandlerService"),
  BOOKING_EVENT_HANDLER_SERVICE_MODULE: Symbol("BookingEventHandlerServiceModule"),
  ATTENDEE_REPOSITORY: Symbol("AttendeeRepository"),
  ATTENDEE_REPOSITORY_MODULE: Symbol("AttendeeRepositoryModule"),
};
